### ISSUE TITLE
number missing as argument of loadPage in fitz.py

### ISSUE THREAD

**Issue by julienfr112** [rk700/PyMuPDF#100]
you can fix it with:

    def loadPage(self, number=0,*args):
        """loadPage(self, number) -> Page"""
        if self.isClosed:
            raise RuntimeError("operation illegal for closed doc")

        val = _fitz.Document_loadPage(self, number)

**Comment by JorjMcKie** [comment]
I guess I don't understand. The current definition of this method in `fitz.py` looks like this:

    def loadPage(self, number):
        """loadPage(self, number) -> Page"""
        if self.isClosed:
            raise RuntimeError("operation illegal for closed doc")

        val = _fitz.Document_loadPage(self, number)

        if val:
            val.thisown = True
            val.parent = weakref.proxy(self)
            pageCount = self.pageCount
            n = number
            while n < 0: n += pageCount
            val.number = n
            self._page_refs[id(val)] = val
            val._annot_refs = weakref.WeakValueDictionary()


        return val

**Comment by JorjMcKie** [comment]
you seem to prefer laconic communication.
after doing some exegesis on what you **might** have meant: you would obviously like to omit the page number when you want to load page 0.
no problem - will be included in the next update.
