### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by pmillsap** [rk700/PyMuPDF#102]
Hi
[pymupdf compile.docx](https://github.com/rk700/PyMuPDF/files/1376184/pymupdf.compile.docx)

I am trying to install pymupdf version 1.11.1 on a raspberry pi.  I have installed mupdf version 1.11 from https://mupdf.com/downloads/ mupdf-1.11-source.tar.gz; it seems to be working however it is mupdf-x11.  All the 3rd party items installed except gflfw, I compliled with glfw set to no.  When I try to install pymupdf with 'sudo python3 setup.py install' I get many compile errors.  I am pretty new to linux so I am may have something setup wrong.  Attached file contains the compile errors.  

Fitz version VersionFitz = "1.11"
VersionBind = "1.11.1"
VersionDate = "2017-10-02 06:43:49"
version = (VersionBind, VersionFitz, "20171002064349")

**Comment by JorjMcKie** [comment]
@rk700 - I think we need your help here. I have attached a text-only version of @pmillsap 's comile error list, assuming you might have problems reading DOCX files ...
[pymupdf.compile.txt](https://github.com/rk700/PyMuPDF/files/1376891/pymupdf.compile.txt)

**Comment by pmillsap** [comment]
[compile_error1012i.txt](https://github.com/rk700/PyMuPDF/files/1380523/compile_error1012i.txt)
Just to update I started over with a clean load of the os.  I installed mupdf with no issues including the third party opengl glfw.  I pretty confident that mupdf is installed correctly.   I ran pymupdf setup.py with pretty much the same results as before, the new file is attached.  Any help you can provide is appreciated.

**Comment by JorjMcKie** [comment]
Hm - I am not absolutely sure, but it seems your compiler insists on string literals where I am using string constants (line #56 is the first with an error).
I am going to change the code to using literals instead of variables and let you know when I a have uploaded a new version. Pls give me half a day or so ...

**Comment by JorjMcKie** [comment]
Was able to do the change a little faster. Please have a look at the version being uploaded right now.
Your C compiler is really picky you know ...

**Comment by pmillsap** [comment]
[compile warnings.txt](https://github.com/rk700/PyMuPDF/files/1381125/compile.warnings.txt)
Downloaded the new file, it built with a fair number of warnings but did install.  I attached the file if you need it.  Thanks for you help I will finish installing my programs tomorrow hopefully everything works

**Comment by JorjMcKie** [comment]
I looked at the file. The warnings look non-toxic.
Good luck, keep us posted.

**Comment by pmillsap** [comment]
Thanks for you help we can close this out
