### ISSUE TITLE
MuPDF 1.12 is coming

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#109]
On 23rd of November, MuPDF have published release candidate 1 for MuPDF called v1.12-rc1.
I have commenced working on it. Here is my first take of what is coming onto PyMuPDF.

# MuPDF Publication Text - https://mupdf.com/news.html
```
The release candidate for version 1.12 is now available!

This release has a new Android SDK which is easier to use.

These are the git repositories for the SDK projects:

    mupdf-android-fitz.git has the JNI bindings in a library.
    mupdf-android-viewer.git has the viewer as an activity in a library.
    mupdf-android-viewer-mini.git has the minimalist viewer as an activity in a library. 

There are binary packages for these libraries in our Maven repository:

    com.artifex.mupdf:fitz:1.12.+
    com.artifex.mupdf:viewer:1.12.+
    com.artifex.mupdf:mini:1.12.+ 

Color Management:

    LCMS2 library for color management.
    CMYK rendering with overprint simulation.
    Spot color rendering.
    Transparency rendering fixes. 

Structured text output improvements:

    Reworked structured text API.
    Faster text searching.
    Highlight and copy text by selecting lines instead of by area.
    New semantic XHTML output format.
    New layout preserving HTML output format. 

Features and improvements:

    Improved non-AA rendering with new scan converter.
    Improved LARGEFILE support.
    Improved TIFF support.
    Improved documentation.
    PCLm output.
    PSD output.
    New "mutool trace" tool.
    New "mutool sign" tool (work in progress).
    Text redaction (work in progress). 
    Lots of bug fixes.
```

# First Impression on PyMuPDF Implications
## Color Management
No idea yet. Maybe no impact at all.
I have seen a new "separations" argument for pixmap creation. I don't know what to do with it except ignore.
## Structured Text Output Improvements
* The TextSheet class is gone completely! I plan to dummy it out but keep our API as forgiving as possible.
* Major API changes in TextPage:
    - text spans have disappeared, the TextPage now only consists of blocks, lines and characters. This means we have to **rework major parts of JSON text extraction**. For our users of `extractText("json")` this is bad news: the hierarchy level "spans" will vanish, which will break your code! I am afraid output types `html` and `xml` will see similar impacts.
    - A new output format is available: XHTML
    - text can no longer be extracted for rectangle parts of a page. This has been replaced by selecting lines between two given points.
    - HTML output now produces a valid document, with all formatting information and including images. When shown in a browser, the appearance is close to the PDF original. **A PDF to HTML converter!**

## Features and Improvements
Implications unclear yet.

Any input, suggestion, help would be highly appreciated!

**Comment by JorjMcKie** [comment]
# Some Update
## New PyMuPDF version
I have PyMuPDF v1.12.0 running. I am still regression testing, and I won't publish a new release until MuPDF does so - so far, their version is just a release **candidate**.
## Text Extraction
### JSON
Good news for text extracting: I modified `extractJSON()` such that **spans are back**.

There remains a difference though: spans do longer contain positioning information (no more dict key ""bbox"). Instead, quite detailed font information for the span text is included (name, size, several flags). So in summary, a line consists of at least one span. A line's spans share the same baseline, but may have different fonts.

JSON now extracts images and stores them as base64 encoded binaries in its output. This is a builtin setting for `getText()` / `getPageText()` methods. If JSON output for text only is required, be sure to check the block type. Use low-level functions to also **suppress** image generation (e.g. for performance reasons).

### HTML
This output has greatly improved, includes images and now produces valid documents that can be displayed in browsers.

The display is quite close to the document original, but it is not perfect yet.

Just as with JSON, exporting images alsways takes place with the standard text extraction methods. To change this behavior, low-level functions must be used.

### Text, XML, XHTML
XHTML is new in this release and produces about the same output as the text-only function, except it can also be displayed in a browser.

Text and XML have not significantly changed.

**Comment by JorjMcKie** [comment]
MuPDF has now published the official v1.12.0 on Dec 13, 2017.

The corresponding PyMuPDF is operational and available in branch 1.12.0 together with updated documentation.

I have tested this version on Windows with versions ranging from Python 2.7 to Python 3.6.

As I am unable to perform tests on other platforms (Linux, Mac OS), please help me with this.

@rk700  @deepgully @mozbugbox @gileadslostson

**Comment by gileadslostson** [comment]
I'll test on Ubuntu 16.x/17.x over the next few days.

**Comment by JorjMcKie** [comment]
Great - I am looking forward to this!

**Comment by JorjMcKie** [comment]
@gileadslostson 
in the meantime, I have finally been successful in setting a virtual Ubuntu 32bit 16.4 ...
I also were able to install MuPDF v1.12.0 by following your instructions ;-).
Although I had to add another option to the make: `HAVE_GLUT=no`. Took  me a while to find that one out.
And finally I also installed PyMuPDF v1.12.0 and successfully performed basic tests: opening document, creating and saving Pixmaps, accessing meta information and table of contents, and the new text extraction functions.
Learned a lot about Ubuntu that way.
E.g. I was surprised to learn that a file will not be found if one does not slavishly follow upper / lower case of the filename. In Windows upper and lower case are ignored here.

**Comment by JorjMcKie** [comment]
With publishing the new v1.12.0, I am closing this issue.

**Comment by gileadslostson** [comment]
So sorry I haven't gotten back to you! Work and other stuff really got in
the way. Nevertheless, I still plan on installing and testing; if I see
anything I'll drop you a message. Sorry again!

**Comment by JorjMcKie** [comment]
Never mind - really!
I had planned to get a Linux playground for a long time anyway. Now I have it.
I certainly would appreciate your assessment of the new release!

BTW:
When installing Python (3.6.4) into the Ubuntu (64bit, 17.x), from source (which I seem to have to in Linux, because I need `Python.h`?), I couldn't get tkinter and zlib installed. So my Python runs for the relevant part, but no `IDLE`, no functions depending on `zlib` :-((
Any hint, what I am missing?

**Comment by gileadslostson** [comment]
When compiling from source you need to make sure the following are there:
`sudo apt-get install bzip2 libbz2-dev zlib1g-dev`

**Comment by gileadslostson** [comment]
I mean before you compile =D

**Comment by JorjMcKie** [comment]
ahh, thx, I will try that

**Comment by mozbugbox** [comment]
On Linux system, packages are divided into ones for user and others for the developer.

So to use python as a program, you install the `python/python3.6` package. To develop using python as library, you have to install the `python-dev` or `python3.6-dev` package which includes `python.h` include files. `Python.h` is only necessary when building application. Normal user doesn't need it.

To find out in which package a file belongs to, on ubuntu, you can install `apt-file` package and use it to search through the package depository.

**Comment by JorjMcKie** [comment]
Thanks you guys for the input!
