### ISSUE TITLE
Is there any way to determine if a pdf is scanned has obfuscated fonts

### ISSUE THREAD

**Issue by juviwhale** [rk700/PyMuPDF#112]
Ideally we would like to use **PyMuPDF** for text extraction of all the PDFs we have to process however we receive a lot of scanned pdfs and a fair number of PDFs with obfuscated fonts or other issues.

**The 5 types of PDFs we process are:**

1.  Normal PDF's - digital and all good to go
2.  Scanned with no additional objects added
3.  Scanned with some objects added like text and digital signatures 
4.  Scanned with crappy OCR text gibberish added (someone forgot to disable that scanner setting)
5.  Obfuscated PDFs where we get text but a custom font has been used to remap all the characters to other normal characters or random unicode characters 

Of the types above we try to identify what type each PDF is and if that is not `1.` then process the PDF via OCR.

***

Notes and Observations

**Is a page scanned?**

We have tried using ``Page.getImageList()`` to reimplement our PDFMiner approach which calculates the % of the page images cover but we have not been able to determine how/where the images are displayed/placed via PyMuPDF. Not possible?

**Scanned with crappy OCR or Scanned with some objects?**

These really fall into the same bucket as determining if they are just scanned because OCR is needed either way.

**Identify Obfuscated fonts?**

Honestly we yet to find a good solution for determining this. The only patch we have here is using a port of Google's language detection algorithm.  Here is an example of an [obfuscated pdf](https://github.com/rk700/PyMuPDF/files/1577414/obfuscated.pdf) Maybe there is something we could do by looking at the embedded font objects?

***

**My question for you, is PyMuPDF able to assist in determining any of these for a given PDF?**

**Comment by JorjMcKie** [comment]
It is easy to find out whether there is normal text at all on a page. Every text extraction methods returns nothing, if there isn't (null string "" or [] or similar stuff with the other).
With the new `getTextBlocks` of `fitz.Page` you can also determine where text appears (as well as with JSON and XML) if there is any. The combined area size of these block rectangles could be compared with the page rectangle size:

```
text_area = 0.0
page_area = abs(page.rect)
for b in page.getTextBlocks():
    r = fitz.Rect(b[:4]) # rectangle where block text appears
    text_area += abs(r)

print("space percent covered with text:", (text_area / page_area * 100))
```


I have seen PDFs where text was "synthesized" via the PDF operator mini-language using those elementary drawing commands: every letter consisted of a combination of curves and lines, etc.
There is no way for PyMuPDF to detect such a situation. I tend do believe that only OCR software would be able to "see" something in that case.

As a matter of fact, I have written a Python script that determines all rectangles of a page where images reside. This is done by inspecting the `/Contents` object of the page by back-multiplying matrices which position the referenced image. Currently, this script has its limits: I haven't been able yet to correctly take into account cases where the page's `MediaBox` and `CropBox` are unequal. Still looking around for something that may enlighten me here.
But anyway - it is usable and should mostly work correctly. It is a start at least.

If you look at the new (v1.12.0) JSON output, you will also find image information. The output of page 0 of out manual e.g. looks like this:

```
{"width": 595.276, "height": 841.89,
"blocks": [
{"type": 1, "bbox": [327.526, 88.936, 523.276, 175.186],
"imgtype": 8, "width": 261, "height": 115, "image":
"/9j/4AAQSkZJRgABAQEAYABgAAD/4QBmRXhpZgA (... omitted image data ...) "
},
{"type": 0, "bbox": [195.483, 189.041, 523.243, 218.91],
"lines": [
{"bbox": [195.483, 189.041, 523.243, 218.91], "wmode": 0, "dir": [1, 0],
"spans": [
{"font": "SFSX2488", "size": 24.7871, "flags": 20, "text": "PyMuPDF Documentation"}
]
}
...
```

Block type 1 indicates an image, and location information is provided. Unfortunately not (yet) the page's reference name for the image nor its XREF. May be possible, too, don't know yet.

As for "obfuscated fonts" - I have no idea, if the text extractions don't work.

**Comment by JorjMcKie** [comment]
In your submitted case `obfuscated.pdf`, it is fairly simple to at least determine that one of the fonts used is indeed obfuscated. Here is what I found when looking at the PDF syntax and following a few object definition pointers:

```
>>> doc=fitz.open("obfuscated.pdf")
>>> doc.getPageFontList(0)
[(8, 'cff', 'Type1', 'SKVYEG+LucidaBright', 'R8')]
>>> # look up the object definition of the font (xref = 8)
>>> # Type1 is synonym for a "simple font"
>>> doc._getObjectString(8)
'<</BaseFont/SKVYEG+LucidaBright/FontDescriptor 9 0 R/Type/Font/FirstChar 4/LastChar 252/Widths[404 0 0 313 0 0 0 0 0 0 0 0 0 602 571 0 0 0 0 0 0 0 642 0 0 0 0 0 0 0 0 0 0 611 0 633 0 0 0 0 0 0 0 0 0 0 0 0 325 0 0 0 0 0 557 608 0 0 599 0 741 545 0 0 768 663 0 0 0 0 0 265 0 0 0 0 0 0 0 557 0 0 0 0 0 0 0 0 0 0 0 0 0 440 0 0 0 0 0 0 0 0 0 0 0 0 0 307 0 0 0 0 392 633 504 0 0 0 0 0 0 0 0 0 543 0 0 0 0 0 695 0 0 0 0 0 573 0 0 0 530 0 0 0 0 0 642 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 633 542 0 0 0 0 0 0 0 0 0 0 0 595 0 777 609 0 0 265 0 860 0 509 0 925 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 265 732 0 0 0 0 0 0 0 0 0 0 0 795 0 551 771 0 0 548 0 0 0 0 0 0 0 0 0 0 346 0 617 0 0 0 0 679 0 0 946]/Encoding 13 0 R/Subtype/Type1>>'
>>> # we see that changes to char widths are being made (/Widths entry)
>>> # so we look at the /FontDescriptor definition (xref = 9)
>>> doc._getObjectString(9)
'<</Type/FontDescriptor/FontName/SKVYEG+LucidaBright/FontBBox[-36 -205 946 783]/Flags 4/Ascent 783/CapHeight 783/Descent -205/ItalicAngle 0/StemV 141/MissingWidth 304/CharSet(/ch052/ch065/ch094/ch1193/ch1313/ch1410/ch1482/ch1651/ch1808/ch1825/ch1911/ch193/ch2013/ch204/ch2158/ch2164/ch2306/ch233/ch2334/ch2448/ch2549/ch2686/ch2833/ch2898/ch2960/ch3034/ch3122/ch3207/ch3359/ch338/ch3431/ch360/ch3637/ch3898/ch394/ch3984/ch4033/ch4102/ch4113/ch4214/ch460/ch479/ch500/ch571/ch669/ch735)/FontFile3 12 0 R>>'
>>> # this has a /CharSet entry (specifies special character definition names in the font program)
>>> # actually already clear that the font has been obfuscated
>>> # but let us look at the /Encoding entry, too (xref = 13)
>>> doc._getObjectString(13)
'<</Type/Encoding/BaseEncoding/WinAnsiEncoding/Differences[4/ch1808 7/ch2448 17/ch2833/ch1911 26/ch1482 37/ch1193 39/ch2013 52/ch2158 58/ch338/ch2898 62/ch2334 64/ch1825/ch3984 68/ch094/ch571 75/ch3431 83/ch4102 97/ch3207 111/ch2164 116/ch3637/ch3898/ch3359 128/ch735 134/ch065 140/ch460 144/ch1651 150/ch2960 168/ch2686/ch500 181/ch4214 183/ch394/ch052 187/ch3034 189/ch360 191/ch1313 193/ch669 212/ch1410/ch204 225/ch4033 227/ch4113/ch233 231/ch193 242/ch2306 244/ch3122 249/ch479 252/ch2549]>>'
>>> 
>>> # this guy has a /Differences entry, e.g. codepoint 4 is mapped ch1808, whatever the font program
>>> # has defined for this name is unknown.
```
As you can see, there are chances to find out things by inspecting the PDF syntax directly (regular expressions could be used for this).
Unfortunately, things are not always so simple as for simple fonts. Other font types (e.g. Type0) may have slightly different indicators that betray obfuscation. But it is always possible to programmatically determine that fact.

**Comment by juviwhale** [comment]
Wonderful, thanks for both of those leads!

Regarding `"I have written a Python script that determines all rectangles of a page where images reside."`, is that script available in the repo? I couldn't find it in my first pass through the examples scripts. 

*Side note/ question*

I hadn't realized that the new JSON format had the B64 image data embedded in it. I am kind of concerned about the increased payload size. Is there a setting to omit the image data portion or should that just be done by reformatting (e.g. like in your `PDF2TextJS.py` example)?

**Comment by JorjMcKie** [comment]
There currently only is a way to omit all the image info completely, thereby also loosing the meta image info. The mentioned script is not on the repo, because I was hesitant to publish half-baked stuff. But here is a copy of it:

[get-img-rect.zip](https://github.com/rk700/PyMuPDF/files/1580689/get-img-rect.zip)

**Comment by JorjMcKie** [comment]
In the meantime I have extended method `Page.getTextBlocks(images = False/True)` to accept an additional parameter. It can now extract layout information for text blocks **and** image blocks, **without** actually extracting the image content data themselves.
It can be used to replace my script `get-img-rect.py`. The information is directly taken from the underlying MuPDF C-library and thus does not depend on my (incomplete - to say the least) efforts to interpret the PDF `/Contents` stream. Image blocks of the list are represented by the following entry:
```
[x0, y0, x1, y1, "<image: colorspace, width nnn, height nnn, bpc n>", block_n, 1]
```

The only drawbacks are, that the image's xref and page reference name are not included.
I will upload this version in a separate branch over the next few days.

**Comment by JorjMcKie** [comment]
New version is published.
I have created a little layout analyzer [utility](https://github.com/JorjMcKie/PyMuPDF-Utilities/blob/master/layout-analyzer.py) which hopefully demonstrates all of the above remarks and can serve as a basis for your needs. Also please look at the analyzed example file "demo1.pdf" in that repository.

**Comment by cygniv404** [comment]
the updated [utility](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/examples/layout-analyzer.py) from @JorjMcKie's response.
