### ISSUE TITLE
getFontList throwing uncatchable error

### ISSUE THREAD

**Issue by juviwhale** [rk700/PyMuPDF#116]
**Example PDF causing issue**
[bad_fonts.pdf](https://github.com/rk700/PyMuPDF/files/1588214/bad_fonts.pdf)

The following code never makes it to the exception print, instead I get a console print out 

`error: unhandled font type
uncaught exception: unhandled font type`

```
doc = fitz.open("bad_fonts.pdf")
page = doc.loadPage(0)

try:
    fontlist = page.getFontList()
except:
    print("Oh no! Could not get fontlist")
```

Am I missing something basic here to catch these errors?

**Comment by JorjMcKie** [comment]
Sorry - I have detected this error only recently. It should occur on early PDF formats (1.2 ?) only.
I have corrected it with a hotfix on 2017-12-25 11:05:13.

With this, you should sill see the "unhandled font type" message on stdout, but it is a warning (ignorable) and shouldn't bring down the interpreter any more.

How is your other stuff going meanwhile?

**Comment by JorjMcKie** [comment]
Tested your attached PDF - does no longer crash.
