### ISSUE TITLE
Valid PDF fails to open after different PDF failed to open

### ISSUE THREAD

**Issue by juviwhale** [rk700/PyMuPDF#126]
I am experiencing an issue where once a  *bad* PDF is opened, subsequent PDFs will also fail to open.

#### Example PDF Attached

-  [good_doc.pdf](https://github.com/rk700/PyMuPDF/files/1641042/good_doc.pdf)-  a very simple generic PDF
- corrupted_doc.pdf - a pdf that is corrupted (unclear source of corruption)

#### Example Script to show issue

```
def check_if_pdf_will_open(path):
    doc = fitz.open(path)
    if doc.openErrCode > 0:
        print("OPEN FAILED!!!!")
    else:
        print("OPEN OK")

check_if_pdf_will_open(good_doc.pdf)
# => OPEN OK
check_if_pdf_will_open("corrupted_doc.pdf")
# => OPEN FAILED!!!!
check_if_pdf_will_open(good_doc.pdf)
# => OPEN FAILED!!!!
```

#### Notes

We first noticed this in a deployed AWS Lambda function. I mention this because it is not just a case were there is a short period of time between `.open()` calls, future invocations of the our lambda invocations fail until we force the environment to rebuild.

**Comment by JorjMcKie** [comment]
I looked at the situation.
It seems it's just false alarms: whatever sequence I choose opening the 2 documents - they will open and become accessible.
Only the error code and message are not cleared correctly before a new document.

As a general comment:
If an open does **not** lead to an exception, it has been successful - even if error messages have been issued! If errors were encountered (which was the case here), this only precludes some few subsequent actions (like incremental saves), and nothing more severe.

But I will of course see to reset everything to a virgin state before accessing a new document.

**Comment by JorjMcKie** [comment]
Done, here is a protocol:
```
>>> import fitz
>>> doc = fitz.open("corrupted_doc.pdf")
error: expected trailer marker
warning: trying to repair broken xref
warning: repairing PDF document
error: name too long
warning: skipping ahead to next token
>>> doc = fitz.open("good_doc.pdf")
>>> doc.openErrMsg
''
>>> doc.openErrCode
0
>>>
```
going to upload new version as a hotfix in master branch.

**Comment by juviwhale** [comment]
Great, thanks.

**Comment by JorjMcKie** [comment]
Uploads are all done now, this repo, [optional materials](https://github.com/JorjMcKie/PyMuPDF-Optional-Material) and [wheels.](https://github.com/JorjMcKie/PyMuPDF-wheels)
