### ISSUE TITLE
fitz.open() module object has no attribute name 'open'

### ISSUE THREAD

**Issue by dhakad97** [rk700/PyMuPDF#129]
in python IDLE
>>> import fitz 
>>>pdf = fitz.open('a.pdf')
AttributeError: 'module' object has no attribute name 'open'
>>>help(fitz.open)
AttributeError: 'module' object has no attribute name 'open'

i am using python3.6 and ubuntu 17.10 and anaconda3.

**Comment by JorjMcKie** [comment]
sorry for the delayed reply - I am on a journey.

We have had this issue type numerous times - you may benefit from searching in the issue list. Usually indicates that the `__init__.py` has not been executed. It is responsible for creating the synonym ``open`` for class ``Document`` and a plethora of more things.

The reasons why initialization did not take place may vary: e.g. installation errors, or invoking Python interpreter from the fitz installation directory.

If you cannot solve the issue with the above hints, please provide an installation protocol, a complete invocation log and an installation directory layout.

Being a Linux expert (which I am not), @rk700 may also step in to help.

**Comment by dhakad97** [comment]
Thanks, I solved it. pymupdf and mupdf  working fine  in python3.6 , ubuntu 17.10

**Comment by luke4u** [comment]
@Hellodhakad , hope you are well. Do you mind sharing how you solved it? 
Thanks. Luke

**Comment by armenic** [comment]
I had my `import fitz` in the file named `fitz.py` and it was causing `AttributeError: partially initialized module 'fitz' has no attribute 'open' (most likely due to a circular import)`. After removing my file into `use_fitz.py` the issue is gone 🌞
