### ISSUE TITLE
Memory Leak with loadPage method

### ISSUE THREAD

**Issue by juviwhale** [rk700/PyMuPDF#132]
We are experiencing a memeory leak when loading a page. The context of our memeory leak is specific to our AWS Lambda deployment which may be related or the situational cause of the leak, we are not sure. 

Below is a reduced lambda function that we have narrowed down the memory leak to.

```
import json
import fitz

def handler(event, context):
    doc = fitz.open("sample.pdf")
    page = doc.loadPage(0)
    body = {"text": page.getText("text")}
    response = {
        "statusCode": 200,
        "body": json.dumps(body)
    }
    return response
````

**Note on AWS Lambda Interaction**

To give better context to the function above, AWS Lambda functions execute in a (sandboxed) container that isolates them from other functions and provides the resources, such as memory, specified in the function’s configuration. 

The first time a function executes after being created or having its code or resource configuration updated, a new container with the appropriate resources will be created to execute it, and the code for the function will be loaded into the container. The initialization code (*code outsize the handler function) is executed once per container creation, before the handler is called for the first time.

Future executions simply call the handler function. 

**Memory Leak Test Script**

In ruby for dev speed, 

```
500.times.do |time|
  Typhoeus.post("<lambda_function_url>", body: "{}")
end
```

Which creates the leak as described here

<img width="772" alt="screen shot 2018-02-05 at 11 26 25 pm" src="https://user-images.githubusercontent.com/6657003/35847261-bed2e3fe-0ace-11e8-98ed-782f4d65661b.png">

**Questions** 

- Am I simply doing something fundemental wrong here how I am initing and interacting with PyMuPDF?
- Should I be calling garbage collector after I interact with PyMuPDF?
- Would it be helpful to debug the memory leak in more detail? I wasn't sure how best to do this. Any tips?

**Comment by JorjMcKie** [comment]
I am not 100% sure to understand. You seem to be using not just Document.loadPage method, but also Page.getText. Based on a current issue (#130) I realized that Python object deletion is not always working sifting down to the C level – it seems like an SWIG issue (glue software between Python and C). Whatever, I am developing a fix for this, and it pertains to the following classes: DisplayList, TextPage and Pixmap. These classes are the basis for several methods: getPixmap, getText, getTextBlocks, etc.
Once I am done with this (probably today or tomorrow) I will upload the fix. Please check your situation again with it, to see if the memory leaks are still occurring.
I will notify you of the upload.

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: juviwhale<mailto:notifications@github.com>
Gesendet: Dienstag, 6. Februar 2018 02:51
An: rk700/PyMuPDF<mailto:PyMuPDF@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: [rk700/PyMuPDF] Memory Leak with loadPage method (#132)


We are experiencing a memeory leak when loading a page. The context of our memeory leak is specific to our AWS Lambda deployment which may be related or the situational cause of the leak, we are not sure.

Below is a reduced lambda function that we have narrowed down the memory leak to.

import json

import fitz



def handler(event, context):

    doc = fitz.open("sample.pdf")

    page = doc.loadPage(0)

    body = {"text": page.getText("text")}

    response = {

        "statusCode": 200,

        "body": json.dumps(body)

    }

    return response

Note on AWS Lambda Interaction

To give better context to the function above, AWS Lambda functions execute in a (sandboxed) container that isolates them from other functions and provides the resources, such as memory, specified in the function’s configuration.

The first time a function executes after being created or having its code or resource configuration updated, a new container with the appropriate resources will be created to execute it, and the code for the function will be loaded into the container. The initialization code (*code outsize the handler function) is executed once per container creation, before the handler is called for the first time.

Future executions simply call the handler function.

Memory Leak Test Script

In ruby for dev speed,

500.times.do |time|

  Typhoeus.post("<lambda_function_url>", body: "{}")

end

Which creates the leak as described here

[screen shot 2018-02-05 at 11 26 25 pm]<https://user-images.githubusercontent.com/6657003/35847261-bed2e3fe-0ace-11e8-98ed-782f4d65661b.png>

Questions

  *   Am I simply doing something fundemental wrong here how I am initing and interacting with PyMuPDF?
  *   Should I be calling garbage collector after I interact with PyMuPDF?
  *   Would it be helpful to debug the memory leak in more detail? I wasn't sure how best to do this. Any tips?
