### ISSUE TITLE
No Bounding Box for spans

### ISSUE THREAD

**Issue by asshatter** [rk700/PyMuPDF#137]
pg = doc.loadPage(0)                         
text = pg.getText(output = 'json')

I am not getting the bounding box for spans
This is a snapshot for the json I'm getting from above function.

{u'blocks': [{u'bbox': [683.17, 36.324, 737.026, 45.6876],
   u'lines': [{u'bbox': [683.17, 36.324, 737.026, 45.6876],
     u'dir': [1, 0],
     u'spans': [{u'flags': 16,
       u'font': u'Arial-BoldMT',
       u'size': 6.8,
       u'text': u'2/5/2018 9:58 AM'}],
     u'wmode': 0}],
   u'type': 0},
  {u'bbox': [52.425, 92.0173, 738.781, 98.5353],
   u'lines': [{u'bbox': [52.425, 92.0173, 63.6678, 98.5353],
     u'dir': [1, 0],
     u'spans': [{u'flags': 16,
       u'font': u'Tahoma-Bold',
       u'size': 5.4,
       u'text': u'Unit'}],
     u'wmode': 0},
    {u'bbox': [96.025, 92.0173, 122.01, 98.5353],
     u'dir': [1, 0],
     u'spans': [{u'flags': 16,
       u'font': u'Tahoma-Bold',
       u'size': 5.4,
       u'text': u'Unit Type'}],
     u'wmode': 0},
    {u'bbox': [169.05, 92.0173, 207.091, 98.5353],
     u'dir': [1, 0],
     u'spans': [{u'flags': 16,
       u'font': u'Tahoma-Bold',
       u'size': 5.4,
       u'text': u'Unit Resident'}],
     u'wmode': 0},
    {u'bbox': [226.85, 92.0173, 242.65, 98.5353],
     u'dir': [1, 0],
     u'spans': [{u'flags': 16,
       u'font': u'Tahoma-Bold',
       u'size': 5.4,
       u'text': u'Name'}],
     u'wmode': 0},
    {u'bbox': [357.3, 92.0173, 398.497, 98.5353],
     u'dir': [1, 0],
     u'spans': [{u'flags': 16,
       u'font': u'Tahoma-Bold',
       u'size': 5.4,
       u'text': u'Market Charge'}],
     u'wmode': 0},
    {u'bbox': [442.3, 92.0173, 463.544, 98.5353],
     u'dir': [1, 0],
     u'spans': [{u'flags': 16,
       u'font': u'Tahoma-Bold',
       u'size': 5.4,
       u'text': u'Amount'}],
     u'wmode': 0},
    {u'bbox': [483.33, 92.0173, 507.171, 98.5353],
     u'dir': [1, 0],
     u'spans': [{u'flags': 16,
       u'font': u'Tahoma-Bold',
       u'size': 5.4,
       u'text': u'Resident'}],
     u'wmode': 0},
    {u'bbox': [535.33, 92.0173, 575.998, 98.5353],
     u'dir': [1, 0],
     u'spans': [{u'flags': 16,
       u'font': u'Tahoma-Bold',
       u'size': 5.4,
       u'text': u'Other Move In'}],
     u'wmode': 0},
    {u'bbox': [597.35, 92.0173, 612.756, 98.5353],
     u'dir': [1, 0],
     u'spans': [{u'flags': 16,
       u'font': u'Tahoma-Bold',
       u'size': 5.4,
       u'text': u'Lease'}],
     u'wmode': 0},
    {u'bbox': [640.95, 92.0173, 666.989, 98.5353],
     u'dir': [1, 0],
     u'spans': [{u'flags': 16,
       u'font': u'Tahoma-Bold',
       u'size': 5.4,
       u'text': u'Move Out'}],
     u'wmode': 0},

**Comment by JorjMcKie** [comment]
This Feature has gone with MuPDF v1.12.0 both, for XML and JSON. You only get a bbox on line and on block level (resp. char level), sorry. What you can do as a fallback: use page.getTextBlocks() or page.getTextWords() instead, see the docu. Or stay with MuPDF / PyMuPDF pre-1.12 versions.

Von meinem iPhone gesendet

Am 21.02.2018 um 10:25 schrieb Ankush Bhatia <notifications@github.com<mailto:notifications@github.com>>:


pg = doc.loadPage(0)
text = pg.getText(output = 'json')

I am not getting the bounding box for spans
This is a snapshot for the json I'm getting from above function.

{u'blocks': [{u'bbox': [683.17, 36.324, 737.026, 45.6876],
u'lines': [{u'bbox': [683.17, 36.324, 737.026, 45.6876],
u'dir': [1, 0],
u'spans': [{u'flags': 16,
u'font': u'Arial-BoldMT',
u'size': 6.8,
u'text': u'2/5/2018 9:58 AM'}],
u'wmode': 0}],
u'type': 0},
{u'bbox': [52.425, 92.0173, 738.781, 98.5353],
u'lines': [{u'bbox': [52.425, 92.0173, 63.6678, 98.5353],
u'dir': [1, 0],
u'spans': [{u'flags': 16,
u'font': u'Tahoma-Bold',
u'size': 5.4,
u'text': u'Unit'}],
u'wmode': 0},
{u'bbox': [96.025, 92.0173, 122.01, 98.5353],
u'dir': [1, 0],
u'spans': [{u'flags': 16,
u'font': u'Tahoma-Bold',
u'size': 5.4,
u'text': u'Unit Type'}],
u'wmode': 0},
{u'bbox': [169.05, 92.0173, 207.091, 98.5353],
u'dir': [1, 0],
u'spans': [{u'flags': 16,
u'font': u'Tahoma-Bold',
u'size': 5.4,
u'text': u'Unit Resident'}],
u'wmode': 0},
{u'bbox': [226.85, 92.0173, 242.65, 98.5353],
u'dir': [1, 0],
u'spans': [{u'flags': 16,
u'font': u'Tahoma-Bold',
u'size': 5.4,
u'text': u'Name'}],
u'wmode': 0},
{u'bbox': [357.3, 92.0173, 398.497, 98.5353],
u'dir': [1, 0],
u'spans': [{u'flags': 16,
u'font': u'Tahoma-Bold',
u'size': 5.4,
u'text': u'Market Charge'}],
u'wmode': 0},
{u'bbox': [442.3, 92.0173, 463.544, 98.5353],
u'dir': [1, 0],
u'spans': [{u'flags': 16,
u'font': u'Tahoma-Bold',
u'size': 5.4,
u'text': u'Amount'}],
u'wmode': 0},
{u'bbox': [483.33, 92.0173, 507.171, 98.5353],
u'dir': [1, 0],
u'spans': [{u'flags': 16,
u'font': u'Tahoma-Bold',
u'size': 5.4,
u'text': u'Resident'}],
u'wmode': 0},
{u'bbox': [535.33, 92.0173, 575.998, 98.5353],
u'dir': [1, 0],
u'spans': [{u'flags': 16,
u'font': u'Tahoma-Bold',
u'size': 5.4,
u'text': u'Other Move In'}],
u'wmode': 0},
{u'bbox': [597.35, 92.0173, 612.756, 98.5353],
u'dir': [1, 0],
u'spans': [{u'flags': 16,
u'font': u'Tahoma-Bold',
u'size': 5.4,
u'text': u'Lease'}],
u'wmode': 0},
{u'bbox': [640.95, 92.0173, 666.989, 98.5353],
u'dir': [1, 0],
u'spans': [{u'flags': 16,
u'font': u'Tahoma-Bold',
u'size': 5.4,
u'text': u'Move Out'}],
u'wmode': 0},

**Comment by skylord123** [comment]
@JorjMcKie I've been trying to find a reason why it was removed and I am not having much luck. Do you know why this was the case? It would be really handy for what I am doing.

**Comment by JorjMcKie** [comment]
@skylord123 - I couldn't find an explanation either when that happened. And there is no ``--verbose`` option to make those guys more responsive ...

On the other hand, when there was a bug caused by an ill-behaving font some time ago, I was forced to replicate ``bbox`` calculation in PyMuPDF. So the code is there now and could be used to re-introduce span bboxes in one of the next versions.
If I find the time to do that, this will exclusively happen for JSON, DICT and RAWDICT output options - definitely not for XML, (X)HTML.

**Comment by JorjMcKie** [comment]
@skylord123 - if you feel urgency for a span bbox: why don't you make one yourself: the data are all there:

* retrieve the text in in the form ``page.getText("rawdict")``.
* stepping down inside the returned dictionary structure you will find a dictionary for each character: ``{"origin":  (x, y), "bbox": (x0, y0, x1, y1), "c": "c"}``.
* a span consists of font information and a list of such character dictionaries. Make your span bbox by joining the character bboxes according to the following pseudo code:

```python
span_bbox = fitz.Rect()
for char_dict in span["chars"]:
    span_box |= char_dict["bbox"]
```

That's it!

**Comment by skylord123** [comment]
@JorjMcKie You are the man! It is working perfectly. 

If there was no reason behind removing bounding boxesfrom spans I would like to request that it be added back in for the future.

I'm working on paragraph extraction and had a bunch of paragraphs that were all mixed up and this resolved it. Thanks.

One last thing: Does fitz.rect have a function to get the same bounding box format that is used in the rest of PyMuPDF? Currently I just did this:

```
span_dict["bbox"] = [
    span_rect.x0,
    span_rect.y0,
    span_rect.x1,
    span_rect.y1
]
```

Thanks again.

**Comment by JorjMcKie** [comment]
Glad to hear that, @skylord123!
I am taking a note to include a bbox for spans again.

As per the bbox format:
In only a few situations you actually need to use ``fitz.Rect``, ``fitz.IRect`` or other "geometry" objects in exactly that way. The all are objects complying with the Python "sequence protocol" and can thus be treated as numeric sequences in most situations.
You can also easily convert them to / from other sequence object types using the usual functions, eg.
* ``fitz.Rect(s)`` is always valid for any sequence ``s`` of 4 numbers - meaning it can be a list, a tuple, a `bytearray` or numpy `ndarray` or ``array.array``, etc.
* vice versa, you could say ``span_dict["bbox"] = list(span_rect)`` in your above example. JSON does not know ``Rect`` objects, but understands lists.
* Verry often in pymupdf functions, you can use sequences where actually geometry objects are required. Eg. inserting text starting at a certain point on a PDF page has a signature ``page.insertText(point, text, ...)``. The argument ``point`` should actually be a ``fitz.Point``, but a "point-like" object is acceptable as well, ie. any sequence of 2 numbers.

So, then why would I differentiate my own geometry objects from other sequences at all? For a number of reasons:
* **History:** MuPDF does have those notions, and until recently, PyMuPDF geometry objects even had C shadow counterparts.
* **Algebra:** Separate geometry objects allow me to define algebraic operations for them: you can add and subtract rectangles, multiply them with numbers or matrices, build unions or intersections, and formulate Python syntax like ``if point in rect`` etc.
* **Performance:** When I output geometric information (eg. ``getText("dict")``, ``getTextWords()``, etc.), performance is a concern.

Flat sequences of values are much faster to generate than building more complex structures. So a list ``[x0, y0, x1, y1, "word", blockn, linen, wordn]`` (format of one item in ``getTextWord()``) is faster to build than ``[fitz.Rect(x0, y0, x1, y1), "word", blockn, linen, wordn]``. The rect of the word in this example can easily be extracted with ``fitz.Rect(item[:4])``.
