### ISSUE TITLE
getFontList throws exception with some PDFs

### ISSUE THREAD

**Issue by juviwhale** [rk700/PyMuPDF#138]
`getPageFontList()` is throwing an exception on some of my PDFs

- Example-PDF [has_bad_fonts_alt.pdf](https://github.com/rk700/PyMuPDF/files/1749818/has_bad_fonts_alt.pdf)

**Example**

```
>>> filename = 'has_bad_fonts_alt.pdf'
>>> doc = fitz.open(filename)
>>> doc.getPageFontList(0)
SystemError: Objects/listobject.c:307: bad argument to internal function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/fitz/fitz.py", line 879, in getPageFontList
    return _fitz.Document_getPageFontList(self, pno)
SystemError: <built-in function Document_getPageFontList> returned a result with an error set
```

**Comment by JorjMcKie** [comment]
Uff, interesting! I have reproduced the error on my site.
Let's see, what is happening there ...

**Comment by JorjMcKie** [comment]
I've located the reason: when I am building the returned Python list, I am relying on valid fontnames, i.e. they should be ascii strings. This is not the case in your example (you pointed this out already). I was a little surprised, that MuPDF is not catching this below the surface.

Anyway. The fix now forces all string fields of the response list to be strict ascii (char codes 0x20 thru 0x7f). Characters outside this range are replced with "?".

I am going to upload this as version 1.12.3.

Thanks for catching this!

**Comment by JorjMcKie** [comment]
BTW: you may notice that, as part of this fix, I am now returnning `None` in most cases, where previously a return of `0` occurred - e.g. `Pixmap.writePNG()` and many others.
This will help keeping interactive sessions free from useless noise.
