### ISSUE TITLE
Text related functions are throwing error

### ISSUE THREAD

**Issue by juviwhale** [rk700/PyMuPDF#139]
Text parsing functions like `getPageText()` are throwing an exception on some of my PDFs

- Example-PDF 
[bad_text_alt2.pdf](https://github.com/rk700/PyMuPDF/files/1752830/bad_text_alt2.pdf)

**Example**

```
>>> filename = 'bad_text_alt2.pdf'
>>> doc = fitz.open(filename)
```

```
>>> doc.getPageText(0, output="text")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/fitz/utils.py", line 107, in getPageText
    return doc[pno].getText(output)
  File "/usr/local/lib/python3.6/site-packages/fitz/utils.py", line 95, in getText
    return tp._extractText(f)
  File "/usr/local/lib/python3.6/site-packages/fitz/fitz.py", line 2609, in _extractText
    return _fitz.TextPage__extractText(self, format)
RuntimeError
```

```
>>> page = doc[0]
>>> page.getTextBlocks(images=False)
SystemError: Objects/listobject.c:307: bad argument to internal function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/fitz/utils.py", line 63, in getTextBlocks
    return tp._extractTextLines_AsList()
  File "/usr/local/lib/python3.6/site-packages/fitz/fitz.py", line 2594, in _extractTextLines_AsList
    return _fitz.TextPage__extractTextLines_AsList(self)
SystemError: <built-in function TextPage__extractTextLines_AsList> returned a result with an error set
```

**Note: I apologize that I am making many tickets about PDF specific issues. I recently processed a large batch of PDFs and had logged the errors. Some of these PDFs may just be poorly formatted and cause issues that you do not want to resolve which I completely understand.**

**Comment by JorjMcKie** [comment]
No need to apologize, de verdad. Every error should be investigated. And so far my current internet connection speed (a real horror ...!) wil let me, I am ambitioned enough to make PyMuPDF as bullet-proof as I can.
Let me look into this as well before I publish the v1.12.3 mentioned in your other issue.

**Comment by JorjMcKie** [comment]
Amazingly, everything works fine under Python 2.
I am generating from identical sources, so SWIG is the primary suspect ...

**Comment by JorjMcKie** [comment]
I do not recall the OS you use.
Here is some update for you:
Branch 1.12.2 of PyMuPDF main repo contains fixes to this issue and to issue #138.
To make sure your issues have gone:
* If you are **not Windows** please download the version of this branch.
* If your OS is Windows, please download one of the wheel files in PyMuPDF-wheels which have a version number of 1.12.3.
* Repo PyMuPDF-oprional-material on my PC is currently under re-construction. If you have Windows and want to use a zip binary, please have some more patience ...

**Comment by juviwhale** [comment]
I will give that a shot. I run MacOS locally and deploy to AWS flavored Linux.

**Comment by juviwhale** [comment]
Both issues are fixed for me with your latest branch. Thank you for the quick fix.

**Comment by JorjMcKie** [comment]
Thanks for the rapid confirmation!
And, please, do keep feeding back issues, feature requests, etc.!
Thanks to your input, PyMuPDF has made some siginifant steps forward!
