### ISSUE TITLE
tuple(Fitz.Rec object) yields RecursionError

### ISSUE THREAD

**Issue by juviwhale** [rk700/PyMuPDF#142]
Starting in the latest version I started seeing errors when getting a tuple of a Rec Object

**Example of usage from the script you helped me work out before**

```
doc = fitz.open(<any_pdf>)
page = doc[0]
tlist = []
ilist = []
for b in page.getTextBlocks(images = True):
    r = fitz.Rect(b[:4]) & page.rect
    if abs(r) > 0:
        if b[-1] == 0:
            tlist.append(tuple(r)) # a text block
        else:
            ilist.append(tuple(r)) # an image block
```

Results in 

```
  File "/usr/local/lib/python3.6/site-packages/fitz/fitz.py", line 1466, in __getitem__
    return tuple(self)[i]
  [Previous line repeated 245 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by juviwhale** [comment]
No worries. I already added a temp fix for this so please take your time.

**Comment by JorjMcKie** [comment]
Found a way to access this site again. Fix has been published to this repo, PyMuPDF-wheels and PyPI. Updating the optional material repo will take a few hours more.
Meanwhile going to close this issue.
Thanks for your report!
