### ISSUE TITLE
Travis CI Generation of Wheels

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#151]
The tests for Linux meanwhile have been successful. The test PyPI site now has wheels for all relevant Python versions.

The Travis environment for MacOS seems not to have twine installed, so that upload to PyPI (Test or production) fails.

Another, more general issue is, that the Travis environemt generates MuPDF directly from the downloaded vanilla version. This leads to very large wheels (> 26 MB), because unnecessary NOTO fonts are included in the binaries. Excluding unneeded stuff has the potential of bringing down the binary size to below 5 MB, and, correspondingly the wheel size down to below 3 MB.

I am not sure how to resolve these open points.

The size issue may be resolved by creating an own MuPDF repo with the desired configuration set. I have no idea on how to mix my own config.h with the vanilla download of MuPDF in a way understable for Travis.

Neither do I know how to inject twine into the Travis MacOS.

**Comment by rk700** [comment]
I just find that Travis supports PyPi deployment on itself:
https://docs.travis-ci.com/user/deployment/pypi/

In that document, Python module `twine` is not mentioned, and I think we could do in that way.

As for the fonts, maybe we can make a script striping out those files. Travis seems to be really powerful and flexible, though I still need to learn more about it.

**Comment by jbarlow83** [comment]
This build is unfortunately a lot more complex than most, of necessity, because it's building a binary extension module. 

You can't use Travis's deploy here, because it tries to build wheels on its own (`python setup.py bdist_wheel`) and will fail. (It does work fine for pure Python.)

See https://github.com/joerick/cibuildwheel-autopypi-example for a possible solution to the missing "twine" module.

**Comment by JorjMcKie** [comment]
I do like this stuff!
Ok, I am trying to proceed stepwise:
1.  Smaller wheels and always install twine
2. Try getting around without twine
3. Find a way to store wheels back to a selected GitHub repo

**Comment by JorjMcKie** [comment]
One statement - simply pip-installing twine - solved the problem! The failures stil popping up were due to duplicate file entries in the test-PyPI.

Also your copy command worked, @jbarlow83 (after getting of some foolish errors): wheels are now sized 3 MB as they should.

Now I will try my above step 3: not feeding back wheels to PyPI, but to the wheels repo I am maintaining on GitHub.

**Comment by jbarlow83** [comment]
For the twine error, it looks to me like everything worked except for the duplication. testpypi automatically erases files periodically and they are gone now
    https://test.pypi.org/project/PyMuPDF/1.12.4/#files
so it should work if you trigger the build again.

Maybe you could upload the 1.12.4 wheels to real PyPI manually?

You can use Travis to deploy to GitHub Releases since Travis just copies the files in that case. The deploy features generally work great, they just happen to not work specifically for deploying binary wheels to PyPI.
   https://docs.travis-ci.com/user/deployment/releases/

**Comment by JorjMcKie** [comment]
Yes, I agree.


With the results so far, I am fairly sure, that the next upload to productive PyPI will now work. And this the next thing I would like to do.

What would be the best way? Modifying the yml file? Honestly I actually do not know how to fulfill this tab condition …

**Comment by JorjMcKie** [comment]
… or would the best way be creating all wheels on test-PyPI, download them from there and twine them to productive PyPI?

**Comment by jbarlow83** [comment]
Push whatever changes you want to the master branch and wait for the build and deploy to testpypi. That's to confirm everything is working. You could download and test a wheel from testpypi if you want.

If everything looks good, create a signed tag and push it:

```
# next time
git tag -s v1.12.5
git push v1.12.5
```

Travis will then build the signed tag (even if it's the same commit as it just built), and push the wheels to production PyPI. That's how it is set up. If you also use Appveyor to automate the Windows build, then you can ultimate arrange for everything to be released automatically everywhere you want it, in response to the action of pushing a tag to "sign off" on the build.

You might find it helpful to add [setuptools_scm](https://github.com/pypa/setuptools_scm) which lets you make the most recent Git tag the single source of truth for the version number. That way you're less likely to have a mismatch between setup.py and the tag or anything else. Makes life easier.

**Comment by JorjMcKie** [comment]
Thanks again.
You may have noticed that productive PyPI now, finally, contains those Linux and MacOS wheels.
Ufff!
Having experiened all this hassle, I am more than before willing to let the generated wheels land in my own wheel repository ... and load them up to PyPI whenever I think it is the right time.

So I need to modify travis.yml accordingly. I have studied the Travis docs and found github release deployment for this purpose.

What I need to do is adding an appropriate deployment section, adding the name of my GitHub repo there and enter my personal credentials as well.

For the Windows wheels I have created my own stuff. As I am  working on Windows myself, I have all Python versions installed and test the generated wheels on my machine before I publish them. This process is very fast (about 1 minute for building all Pythons and all bitnesses). So I would not benefit from anything like Travis or Appveyor - in addition to that I am also maintaining the documentation content and media production, integrated with the rest of my machinery.

Actually Linux and MacOS wheels were my only missing pieces and I am more than happy to now having a solution for this, too!

Thanks a lot for your guidance!
