### ISSUE TITLE
"pip install pymupdf" ignores wheels because of 1.12.4.1 source dist

### ISSUE THREAD

**Issue by jbarlow83** [rk700/PyMuPDF#152]
``pip install pymupdf`` currently picks up the source distribution 1.12.4.1 from PyPI and attempts to install from source on any platform, ignoring the wheels.

If I'm not mistaken this is just the recent wheel and related changes, which you want to separate from a previous source release of 1.12.4? If so I believe if you make it an implicit post release v1.12.4-1 PyPI will not prioritize it.
https://www.python.org/dev/peps/pep-0440/#implicit-post-releases

**Comment by JorjMcKie** [comment]
Ahh thanks, I wasn't aware of this.

**Comment by JorjMcKie** [comment]
Done

**Comment by jbarlow83** [comment]
Sorry, I was mistaken about how pip handles the post-release thing. It's still picking up the sdist.

**Comment by JorjMcKie** [comment]
well then I best delete the source component alltogether

**Comment by JorjMcKie** [comment]
Done.
Tis is one of the things I really find annoying about PyPI:
One tiny little error, and you must bump the version of your stuff, and upload everything again with it. Hoping, that nothing went wrong again this time ...
Sorry if I sound a little larmoyant ...

**Comment by jbarlow83** [comment]
Yeah, it's frustrating. That's why it's easier to automate deployment, so you don't have to think about it. :P  Bump version, push, and fix gets deployed everywhere at once.
