### ISSUE TITLE
Attempting to validate Image Integrity using pyMuPDF

### ISSUE THREAD

**Issue by bschollnick** [rk700/PyMuPDF#160]
Folks,

I'm having an issue, where I need to scan a bunch of PDFs, and try to ensure that the stored Image is valid in the PDF structure.  The Images themselves are valid, but the height/width in the PDF structure isn't correct, and is causing Insufficient Data for Image errors.

Does anyone have a good suggestion for how to do this?

I have been trying to check the page.height & page.width, versus the Image's height and width, but even when I create the PDF, the height / width do not match the Image's pixel dimension?

eg.

            extract_image(fname)
            pdfdoc = fitz.open()            
            for count, filename in enumerate(glob.glob("repair_jpg*.jpg"), start=0):
                im = Image.open("repair_jpg%s.jpg" % count)
                width, height = im.size
                im.close()
                pdfdoc.newPage(width=width, height=height)
                page = pdfdoc[count]                          # load page (0-based)
                rect = fitz.Rect(0, 0, width, height)       # where we want to put the image
                pix = fitz.Pixmap("repair_jpg%s.jpg" % count)        # any supported image file
                page.insertImage(rect, pixmap = pix, overlay = False)   # insert image

So for example, the repair0.jpg is 845*536.
When inserted, the PageImageList is reporting:

>>> test.getPageImageList(0)
[(5, 0, 895, 537, 8, 'DeviceGray', '', 'Z_Im0_0')]

Am I missing something here?  I created the page with the correct width & height, and the rect, as well.  So I don't understand why it's off by 50x1?

**Comment by JorjMcKie** [comment]
1. If you use newPage, the result is directly the just created page. No need to load it again. Which is error-prone, anyway (as in your case).
2. Images inserted by PyMuPDF have a 32 byte identification, it is never never "T_Im0_0". Must be a different page, therefore.
3. Images can be inserted directly; you do not PIL/Pillow for this.
4. When you `insertImage`, it will always fill out the comlete provided rectangle, disregarding original width / height ratio. To prevent this, you must apply the same adjustment factor to width and height of the insertion rectangle.

Your statements inside the loop could therefore just be:
```
for ......:
    pix = fitz.Pixmap("...jpg")
    page = doc.newPage(-1, width = pix.width, height = pix.height)
    page.insertImage(page.rect, pixmap = pix)
```

**Comment by bschollnick** [comment]
Okay..  I'm found a decent example.

The issue is that these PDFs with images that were created by other systems...  And the image itself appears to be the issue.

For example

5 0 obj<</Type/XObject/Subtype/Image/Name/XImg/Width 895/Height 537/BitsPerComponent 8/ColorSpace/DeviceGray/Intent//Filter[/DCTDecode]/DecodeParms[<</Columns 845/Rows 73>>]/Length 61744>>stream


Please note that the PDF claims the image is 895x537.  The decode is indicating that it's 845 wide.

If we open the PDF as is, we get an insufficient data for image (and a blank white screen). 

If we try to clean it via pyMuPDF's garbage, clean, and deflate, we still receive the insufficient data for image, but once we clear the error dialog, the image appears.

If I manually change the 895 width to 845, the PDF opens without error...

Is there any way to programmatically detect this scenario?  We are receiving PDF's from a variety of sources, so I can't isolate this to one source or image format.

And I tried exporting this images, and they are distorted, because of the incorrect width.

**Comment by JorjMcKie** [comment]
As an intermediate information:
PyMuPDF also lets you change PDF object definition sources directly. This means, you can read PDF object xref 5 like so:
`obj_src_5 = doc._getXrefString(5)`
You could then find out (via regular expressions or something) that mismatch and correct the string `obj_src_5` accordingly. Then do
`doc._updateObject(5, obj_src_5)`
to re-insert the correct object definition. Which is of course quite hackish ... But it's that PDF's own fault, right? :-)

**Comment by JorjMcKie** [comment]
I am not sure, how the object source update works, if the object also has a stream (which is the case here). If you run into problems because of stream is missing after the object update, do this:

1. Read the associated stream (i.e. the actual image), like so: `img = doc._getXrefStream(5)`.
2. Read object source as shown above.
3 Update object source as shown above.
4. Update the stream (with the old image data): `doc._updateStream(5, img, new = True)`.

You may need PyMuPDF v1.12.6+ for this to work.

**Comment by bschollnick** [comment]
As an intermediate information:

> PyMuPDF also lets you change PDF object definition sources directly. This
> means, you can read PDF object xref 5 like so:
> obj_src_5 = doc._getXrefString(5)
> You could then find out (via regular expressions or something) that
> mismatch and correct the string obj_src_5 accordingly. Then do
> doc._updateObject(5, obj_src_5)
> to re-insert the correct object definition. Which is of course quite
> hackish ... But it's that PDF's own fault, right? :-)
>

Absolutely perfect.

That's solves one problem, I was trying to figure out the best way to
scrape that data.  Now, it's significantly easier...

I'll talk to the boss.  The PDF I am testing should be clean, but I need to
get sign off on it...

                    - Benjamin

**Comment by JorjMcKie** [comment]
`doc.getPageImageList(pno)` is a list of list, so you need to use `[0][0]`.

I have played around a little with your PDF ... this is a hard one to repair!
My above procedure worked ... in this case. But who knows what other cases you might come across.

What seems to work best / safest / cleanest:

``` Python
import fitz
import json
from binascii import a2b_base64
import sys
"""
This tries to create a sanitized output PDF.
Assumption is, that input only contains images - any text is ignored
at the moment.
For each image on each page, a separate output PDF page is generated,
which has the display size (!) of the source image, and the image is completely
covering it.
"""
fname = sys.argv[1]                         # input PDF
docin = fitz.open(fname)
docout = fitz.open()                        # output PDF
for page in docin:                          # read all input pages
    js = json.loads(page.getText("json"))   # and decode content as JSON
    blocks = js["blocks"]                   # skip all except image blocks
    for b in blocks:
        if b["type"] != 1:
            continue 
        imgb64 = b["image"]                 # an image is base64 encoded
        if not imgb64:                      # if at all present
            continue 
        img = a2b_base64(imgb64)            # get original binary img
        # now create output page exactly fitting the image
        pageout = docout.newPage(-1, width = b["width"], height = b["height"])
        pageout.insertImage(pageout.rect, pixmap = fitz.Pixmap(img))
# save as new PDF
docout.save("repair-" + docin.name, garbage=4, deflate=True)

```

**Comment by JorjMcKie** [comment]
Version 1.13.0 is out. So you have the flexibility indicated in my previous comment.
Your issue made me think about one additional improvement. Let me explain some background first.

# Background of the Error
When creating a pixmap from a PDF xref (via method `fitz.Pixmap(doc, xref)`, MuPDF takes the image's object definition seriously, i.e. properties like width, height and what not. It consequently diagnoses an incomplete binary stream, if the properties buried in that stream are different - and adjusts the binary image image representation as well as it can ... which leads to the garbled output or no image at all.
This has happened in your case. It's not just MuPDF doing this, but also the PDF readers you (and I) are using.

# Solution
Of course, one can never know, what is more correct: the PDF source definition or the image's binary stream. But to be able to detect any discrepancies is the first step to any solution.
I have developed a way to directly extract the image's raw binary stream from the PDF. Using this as input for pixmap or PIL-Image creation would (if successful) exhibit any discrepancies mentioned above.
... And there would be no need to involve other methods like `Page.getText()`. It works like in this snippet:

``` python
>>> import fitz
>>> doc = fitz.open("damaged.pdf")
>>> # show what is defined in the PDF source
>>> doc.getPageImageList(0)
[[5, 0, 895, 537, 8, 'DeviceGray', '', 'Z_Im0_0', '']]
>>> fitz.Pixmap(doc, 5)
fitz.Pixmap(DeviceGray, fitz.IRect(0, 0, 895, 537), 0)
>>> # now check what the binary image data of xref 5 say:
>>> img = doc.extractImage(5)    # <=== the new method
>>> fitz.Pixmap(img)             # create pixmap from binary stream
fitz.Pixmap(DeviceGray, fitz.IRect(0, 0, 845, 536), 0)
>>> # we see, there is a problem:
>>> # pixmaps' widths and heights are different!
```

**Comment by JorjMcKie** [comment]
Here is an improved version of my above sanitzer script. It now keeps input page numbers and sizes and image positions. It also can handle several images on same input page.

```python
import fitz
import json
from binascii import a2b_base64
import sys
"""
Utility script
--------------
This tries to create a sanitized version of a PDF which has issues
with embedded images.
Assumption is, that input pages only contains images - any text is ignored.
Think of a scanned-in book ...
For each input page, an output PDF page with the same size is generated.
For every image found, a (hopefully) sanitized version is created
and put on same place of the output page.

Stability assessment
--------------------
Will only work if input PDF has at least intact / repairable XREF,
and page tree.
"""
fname = sys.argv[1]                         # input PDF
docin = fitz.open(fname)
docout = fitz.open()                        # output PDF
for page in docin:                          # read all input pages
    js = json.loads(page.getText("json"))   # and decode content as JSON
    width  = js["width"]                    # input page width
    height = js["height"]                   # input page height
    pageout = docout.newPage(-1,            # output page has equal size
                width = width, height = height)
    for b in js["blocks"]:
        if b["type"] != 1:
            continue                        # not an image block
        imgb64 = b["image"]                 # an image is base64 encoded
        if not imgb64:                      # if at all present (may be None)
            continue 
        img = a2b_base64(imgb64)            # get original binary img
        rect = fitz.Rect(b["bbox"])         # position of image

        # store image in page. 
        # possible enhancement: use try-except sequence and process img with
        # Pillow in case of an exception. If this is successful get Pillow
        # output and insert it.
        pageout.insertImage(rect, stream = img)

# save the sanitized PDF
docout.save("repair-" + docin.name, garbage=4, deflate=True)

```
