### ISSUE TITLE
how to find line segment in xps format file with PyMuPDF

### ISSUE THREAD

**Issue by jerrygit** [rk700/PyMuPDF#163]
Hi, PyMuPDF is only and great to extract texts from xps files.  Is there any method to get line segment information from xps with it? I've seen 
 page._getContents()                                        # xref of page contents
 cont = doc._getXrefStream(4)  
only good for pdf format.
Thanks.

**Comment by JorjMcKie** [comment]
Hi,
I try to make MuPDF functions available as broadly as they are provided. The documentation should be complete in saying what is available only for PDF and what is supported on a broader level – if you find inconsistencies, please do tell me.

That said, the functions you are referring to (_getContents, etc.) provide information on PDF-specific structures. There are no similar things for other document types.
Please do especially note, that all functions writing to documents are PDF-only. MuPDF cannot create XPS or EPUB files.
However, text extraction and searching (page.getText, page.searchFor) and page rendering (pixmaps and SVG) work for all types. This extends to page image extraction, as far as the getText() functions provide it (image binary content, image type, image dimension, position information, etc), as well as text position information (position of each line, word, character, block, font information, etc).
But there exists nothing to investigate the internal structure of an XPS file …
Of course, as they are specialized ZIP archives, there is always that way – outside (Py-) MuPDF.
Hope this helps.

**Comment by jerrygit** [comment]
Thank for your fast and kind reply. My need on xps files is to find out a line over some words that indicates cancel of the words. Now I understand that those functions are effective for PDF-specific structures.  I think I should search the other way as you mentioned like handing ZIP archives directly.
Thanks again.

**Comment by JorjMcKie** [comment]
You're welcome. But I don't give up yet. If you take
```python
textwords = doc[n].getTextWords()
```
for a given page `n` of an XPS document opened with `doc = fitz.open("some.xps")`,  then each word of the page has an entry in the list `textwords`, which looks like so:

```python
>>> textwords[27]
[119.00448608398438, 135.87132263183594, 156.10279846191406, 141.9043731689453, 'Kommunikation', 3, 0, 5]
>>> 
```
which contains the 4 float coordinates of the word's position on the page, the word itself (`Kommunikation`), text block number of the page (3), line number in block (0), word number in line (5).
If you combine this with
```python
textblocks = doc[n].getTextBlocks()
```
and take
```python
>>> textblocks[2]
[20.280000686645508, 128.67132568359375, 342.16156005859375, 134.70437622070312, 'Anbei finden Sie Ihre cleverbridge Referenznummer. Um unverzüglichen und sorgfältigen Kundenservice zu erhalten, geben Sie diese ', 2, 0]
>>> textblocks[3]
[20.280000686645508, 135.87132263183594, 245.09400939941406, 141.9043731689453, 'Referenznummer bitte immer in jeglicher Kommunikation bezüglich Ihres Auftrags mit uns an. ', 3, 0]
>>> 
```
you will see the word "Kommunikation" in the context of its line and the previous line.
If I understood your intention well, I would argue you can find what you are looking for, and that you do not need any low-level XPS structure information.

**Comment by JorjMcKie** [comment]
BTW, when you the 4 floats of each entry in `textwords` or `textblocks`, you can easily make a PyMuPDF rectangle out of them like this:
```python
>>> rect = fitz.Rect(textblocks[3][:4])
>>> rect
fitz.Rect(20.280000686645508, 135.87132263183594, 245.09400939941406, 141.9043731689453)
>>>

**Comment by jerrygit** [comment]
I think I did not make my self understood. 
The term 'line' has two meaning , one is text line  in textpage hierarchy you described in your 'PyMuPDF 1.X0 Documentation', chapter 12.1 General structure of a TextPage. ( page-block-**_line_**-span-char )

The other one meaning of 'line' term is line segment as in xps document source, (
  Path Data="F1 M 138,231.53 L 144.73,231.53"  Stroke="#ffff0000" StrokeThickness="1" StrokeLineJoin="Round" StrokeStartLineCap="Round" StrokeEndLineCap="Round" )
would draw a line starts from 138 x0, 231 y0 to 144 x1, 231 y1.

I want find out lines ( the x, y coordinates of line ) corresponds with texts which means the meanning effect of text is canceled.
Let me show you an example, assume that an xps file has a text line.
<p>My favorite color is <del>blue</del> <ins>red</ins>!</p>

The line over text 'blue' means the color is not blue but red.  I have much of xps files with those cancel lines.
If your above comment is the answer, pleas kindly give me some short real example code with it.
Thank you.

**Comment by JorjMcKie** [comment]
Now I got it: your were talking about things like text revision marks.
So please forget my above comments - they do **not** address that.
I am not sure, but your excerpt looks like syntax that one also finds in SVG images, which in turn can be translated to PDF operator syntax among other by packages like [svglib](https://github.com/deeplook/svglib). Maybe you find help in that direction.

**Comment by jerrygit** [comment]
OK, I will try other solutions like svglib or zip file utilities.
Still I should use your PyMuPdf for the easiness of text extraction.
Thanks.
