### ISSUE TITLE
Is there any way to print the pdf forms options using PyMyPDF

### ISSUE THREAD

**Issue by manish59** [rk700/PyMuPDF#164]
I want to detect wether a pdf is normal pdf or form pdf.  Can we do that using PyMuPDF

**Comment by JorjMcKie** [comment]
Hm.
Handling forms and form fields is an open point in PyMuPDF. MuPDF base library does provide appropriate functions as far as I have looked at it yet.

If it just is the question you have been asking (is it a PDF containing forms or not), there for sure is a way, because we have access to the PDF object source.
So we can check the PDF's catalog to find out whether an AcroForm is present, etc.
Even simpler is the test whether a file is an FDF document, etc.

Do you happen to have a form PDF that you could send me? I am willing to put together a script that can answer this question.

**Comment by manish59** [comment]
Sure . I have so many documents.  I attached a link which is FORM 1572 which I am working on it. Please let me know if you can help to detect if it is a FDF or PDF and if possible get fields from the pdf.
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjd2NrrgePaAhXmw1QKHe5yDF0QFggpMAA&url=https%3A%2F%2Fwww.fda.gov%2Fdownloads%2FAboutFDA%2FReportsManualsForms%2FForms%2FUCM074728.pdf&usg=AOvVaw0nLJe7iORwGQeuPQBF4uxX

**Comment by JorjMcKie** [comment]
**Intermediary update**
If a PDF has (is) a form can be determined by checking the existence of a so-called `AcroForm` object.
PDF is a form if such an object exists. If it does, then only one can exist apparently.

What I will do: create a new `Document` method that retrieves the PDF xref number of the AcroForm object, something like `xref = doc.getFormObject()`. If this (integer) `xref` is positive, then the PDF is a form. Another method would then return a list of form field xrefs, which in turn can then be checked for properties / content. Or something more elegant along this line ...

Apparently, form fields are a special type of annotations: "widgets". You can **already today** check, whether a page has such widgets, and display some of their content:

```python
>>> doc = fitz.open("some-form.pdf")
>>> page = doc[0]
>>> annot = page.firstAnnot
>>> while annot:
        if annot.type[0] != 19:     # 19 = annotation type "widget"
            annot = annot.next      # skip to next annotation
            continue
        xref = annot._getXref()     # get the annot's source code (= field definition)
        # show the field definition (may contain filled-in values)
        print(doc._getXrefString(xref))
        annot = annot.next          # cycle through annots

"<</F 4/P 1367 0 R/T(db_invest_name)/V(Jorj X. McKie, friend of Python)
/AP<</N 1600 0 R>>/DA(/TimesNewRoman 10 Tf 0 g)/FT/Tx/Ff 8388608/MK<<>>
/TU(Please enter the name of the clinical investigator. Note:  ... or other.)
/Rect[35.0583 643.5 576.731 660.248]/Type/Annot/Subtype/Widget/StructParent 44>>"
... etc ...

```
As you can see, I have filled-in some field already. Looks like field `db_invest_name` contains `"Jorj X. McKie, friend of Python"`. So, this logic can already now be used to

1. indirectly determine if the PDF is a form: if annotations of type `(19, "widget")` exist on any page, then YES

2. even look at form field definition and content (however clumsily for the time being).

**Comment by JorjMcKie** [comment]
I have just implemented the above mentioned check (test whether it is a form, not uploaded yet).
Please give me a feeling of what you would like to see happening next.
When you say you want to see field contents, there are basically two ways accessing this:

1. start from the AcroForm object. This contains an array of pointers all (**root!**) fields, no matter on which page each one appears. Root field means, it has no sub-fields.

2. Cycle through each page to select its `"Widget"` annotations. All form fields in fact **are** widgets, so this method would also detect them all. Not sure, how root fields and 

Fields can be of different types: text, checkbox, and what not, and of course have a field name.
Then there may be groups of fields, which each have a name concatenated to their group's name, etc.

To keep things simple, I would start by extending widget annotations with additional attributes, like field type, name and content. OK with you?

**Comment by JorjMcKie** [comment]
Made some preliminary adjustments. Have a look at this. I have filled out page one of your form PDF and now printing out all fields of that page. If this is sufficient, let me know.

```python
>>> annot = page.firstAnnot
>>> while annot:
	if annot.type[0] != 19:
	    annot = annot.next
	    continue
	print(annot.widget_type, annot.info["title"].ljust(25), annot.widget_text())
	annot = annot.next

	
3 db_invest_name            Jorj X. McKie
3 db_inv_address1           Calle Buena Vista 1
3 db_inv_address2           Playa El Agua
3 db_inv_city               Arismendi
3 db_inv_state              Nueva Esparta
3 db_inv_country            Venezuela
3 db_inv_zip                8505
1 db_cv                     <check-button>
1 db_oth_qual               <check-button>
3 db_loc_name               Medical School Name
3 db_loc_address1           Medical School Address 1
3 db_loc_address2           Medical School Address 2
3 db_loc_city               Medical School City
3 db_loc_state              Nevada
3 db_loc_country            USA
3 db_loc_zip                123456
0 btnContinue3              <button>
3 db_lab_name               Clinical Lab Facility Name
3 db_lab_address1           Clinical Lab Facility Address 1
3 db_lab_address2           Clinical Lab Facility Address 2
3 db_lab_city               Lab City
3 db_lab_state              Florida
3 db_lab_country            USA
3 db_lab_zip                654321
0 btnContinue4              <button>
3 db_irb_name               IRB Name
3 db_irb_address1           IRB Address 1
3 db_irb_address2           IRB Address 2
3 db_irb_city               IRB City
3 db_irb_state              Hawaii
3 db_irb_country            USA
3 db_irb_zip                999999
0 btnContinue5              <button>
3 db_sub_inv_names          No subinvestigator
0 btnContinue6              <button>
3 db_prot_name_code         Field 7
3                           2
3 txt_validate              True
3 txt_delete_signature      False
3 db_form_name              1572
3 db_form_version           7/13
1 chk_pageexists3-1         <check-button>
1 chk_pageexists3-2         <check-button>
1 chk_pageexists3-3         <check-button>
1 chk_pageexists3-4         <check-button>
1 chk_pageexists3-5         <check-button>
1 chk_pageexists3-6         <check-button>
1 chk_pageexists4-1         <check-button>
1 chk_pageexists4-2         <check-button>
1 chk_pageexists4-3         <check-button>
1 chk_pageexists4-4         <check-button>
1 chk_pageexists4-5         <check-button>
1 chk_pageexists4-6         <check-button>
1 chk_pageexists5           <check-button>
1 chk_pageexists6           <check-button>
>>> 
```

**Comment by manish59** [comment]
Thats amazing buddy. Thanks it worked like a charm. Can you help me how to find the comments on the pdf. for example people make comments or strike a line on the pdf. can we recognize using this tool

**Comment by manish59** [comment]
Is there any way to extract images from the pdf with adjustable resolution using this tool

**Comment by JorjMcKie** [comment]
Answering last comment first:
1. You can always render a PDF page at whatever resolution
2. Likewise, you can render an annotation (separately from the page where it appears) in any resolution as well

Do this when you create the respective pixmap. One of the Pixmap parameters is `matrix`. To scale (zoom) by a factor of 2 in x and y direction, specify a matrix fitz.Matrix (2,2), etc.

You know how to extract images from a PDF at all, don't you? IF uncertain, consult one of the demo scripts named `extract-img<n>.py`. You can extract images by page, by document, and (especially efficient) for PDF documents.

**Comment by JorjMcKie** [comment]
"Comments" on a PDF page must surely be annotations of some kind. So they can - in principle - be detected by inspecting annotations.

The real challenge is how to detect that there actually some of this did happen. Without knowing details you're alluding to, this could be done comparing before / after states of a file. E.g. a page would have more or different annotations, if someone added a comment or underlined / strike-through something. That difference can be investigated by interpreting the new / changed annotations. Of course something requiring significant programming effort ... but I am unbiased enough to say: PyMuPDF should provide all technical prerequisites for such an undertaking.
