### ISSUE TITLE
File not found - *.[ch]

### ISSUE THREAD

**Issue by killerT1992** [rk700/PyMuPDF#175]
I am following [this installation guide](http://pymupdf.readthedocs.io/en/latest/installation/#option-1-install-from-sources) (Option 1). After downloading mupdf-1.13.0-source.tar.gz from [here](https://mupdf.com/downloads/) and downloading this repo, I try to generate MuPDF by running the command

`make Makefile`

The problem is, I get the error `File not found - *.[ch]. make: Nothing to be done for 'Makefile'` (the error occurs 3 times for the 3 times `*.[ch]` occurs in the Makefile). I appreciate there is a different repo / contributors for MuPDF, but it seems we can't raise issues on the mupdf repo. I've tried both downloading it from the link above and downloading it from the mupdf repo - both times with the same error.

 I am not sure if there is anything else I need to download to generate the MuPDf, but the install guide didn't seem to indicate so.

Is there something missing in the downloads from [here](https://mupdf.com/downloads/) or anything else  I need to download that I missed?

**Comment by JorjMcKie** [comment]
Normally this download includes everything needed for generation, thirdparty software and such.
PyMuPDF generation actually relies on a previous successful MuPDF generation. If this prerequisite is not met, and if the various hints on our web site, e.g.  the [Ubuntu Wiki](https://github.com/rk700/PyMuPDF/wiki/Ubuntu-Installation-Experience) don't help you, then I am afraid you should look for help at resources like [StackOverflow](https://stackoverflow.com).

What is your platform? Any specific reason why you cannot use any of the pregenerated wheels?
BTW: the generation of these for Mac and Linux is done exactly the way you indicated above.
I am mostly working on Windows and use Visual Studio for generating MuPDF (also described in a Wiki), PyMuPDF wheels and zip files.

**Comment by killerT1992** [comment]
Thanks for the quick reply. I am on windows 7, x-64. Is there a windows installation experience link maybe?

**Comment by JorjMcKie** [comment]
Try [this](https://github.com/rk700/PyMuPDF/wiki/Windows-Binaries-Generation).
I am maintaining PyMuPDF on a more or less daily basis being on Windows.
I am taking it: you insist to generate your own binaries, don't you :-) ? If this is true, you definitely should use Visual Studio and not fiddle around with Makefile. I have no experience with this - it would imply using something like Cygwin.
I am using the free VS 2015 / 2013 editions, and it works just fine, once you have figured out, where for heaven's sake are all those SDK libs ...
Otherwise, as said above, use a wheel or a zip prepared for your platform ...

**Comment by killerT1992** [comment]
I'll try that! Thanks so much for the support... honestly this would be a lot easier if I was using my personal mac / an ubuntu system and I'd just use pip (I actually have PyMuPDF working on my mac). But I'm on a work computer and getting around company proxy's, admin permissions etc. is impossible which is why I need to do it like this.

**Comment by killerT1992** [comment]
Appreciate all that, and it's great to see the constant development of such a great library! I ended up not getting this method to work, but I found some way's online to get around proxies, so I just installed PyMuPDF with pip ! (sorry for creating this issue and all the questions).

**Comment by JorjMcKie** [comment]
you are very welcome - every question may be helpful for others seeking answers.
And thanks for the encouraging feedback!
