### ISSUE TITLE
How do i set the resolution of the pixmap for a page 

### ISSUE THREAD

**Issue by asshatter** [rk700/PyMuPDF#181]
I need to convert pdf to images but i'm getting a lower resolution image. 

`pix = page.getPixmap(alpha=True)`
`img = Image.frombytes("RGBA", [pix.width, pix.height], pix.samples)`

**Comment by JorjMcKie** [comment]
Your must use a matrix when creating the pixmap, like so:
```python
zoom = 2    # zoom factor
mat = fitz.Matrix(zoon, zoom)
pix = page.getPixmap(matrix = mat, <...>)
...
```

**Comment by asshatter** [comment]
Great, works like a charm. Thanks.

**Comment by martingaudio94** [comment]
Work very good , exelent! Thanks

**Comment by yoderj** [comment]
@JorjMcKie What is the default zoom factor in DPI? Is it 72 DPI as is built-into the PDF standard (as far as I can tell), or is it something else?

**Comment by JorjMcKie** [comment]
@yoderj - yes, this is correct!

**Comment by fgallaire** [comment]
a zoom argument could be a nice shortcut

**Comment by JorjMcKie** [comment]
> a zoom argument could be a nice shortcut

There now (v1.19.2) is a dpi argument ...: `pix = `page.get_pixmap(..., dpi=300, ...)` which when used causes `matrix` to be ignored.

**Comment by maiiabocharova** [comment]
> ```python
> zoom = 2    # zoom factor
> mat = fitz.Matrix(zoom, zoom)
> pix = page.get_pixmap(matrix = mat)
> ```

Also used it! Worked fantastic, following your advices got exactly what I wanted!
