### ISSUE TITLE
Generated ToC can't be recognized by preview (Mac default App)

### ISSUE THREAD

**Issue by xyliu** [rk700/PyMuPDF#183]
here is my code: https://github.com/xyliu/pdftoc/blob/github/upt_toc.py#L88,   the PDF files are from: https://github.com/Igalia/intel-osrc-gfx-prm/tree/master/010_kbl_-_2016-2017/.

The ToC is generated with standard operations documented, it can be recognized by Adobe Acrobat and Foxit Read, but failed by PDF expert in iOS and default previewer in macOS11. 

Could you please have a check?

**Comment by JorjMcKie** [comment]
I tested your program on Windows - works just fine.
PDF with new TOC can be read by Adobe Reader, SumatraPDF, PDF-XChange Viewer, and Nitro 5 Reader.
The Nitro Reader couldn't read it at first - obviously because you are adding the TOC via incremental update: once I saved it non-incrementally, it was ok also.

I also had no problem at all with the standard file viewer in Linux (Ubuntu).

So I guess it should be a capability lack of the Apple program. I have neither of these, so I can't check myself.
Are you sure these apps can normally display TOCs? And also handle PDFs with TOCs given in incremental updates?

**Comment by xyliu** [comment]
Thanks for the quick response.
The two Apps have two kind of ‘outlines’. One is bookmark, the other is outline. On the way, acrobat and foxit reader have only 1. I guess that might be the cause. 

I add bookmark by hand though foxit reader, which can be recognized by the two apps(iOS/macOS).

**Comment by xyliu** [comment]
Yes. Adobe Manual's 'bookmark' can be shown as ToC, but not in bootmarks category in 'Preview'.

I tried with "https://www.foxitsoftware.com/pdf-reader/" (free to use), and the "https://github.com/Igalia/intel-osrc-gfx-prm/blob/master/010_kbl_-_2016-2017/intel-gfx-prm-osrc-kbl-vol13-mmio.pdf", the bookmark can be recognized as "ToC" in Preview.

**Comment by JorjMcKie** [comment]
I am confused:
If Preview shows the table of contents of the Adobe Manual, how can it do that if not as bookmarks? What other "categories" are there?
I am not talking about the stuff shown on pages 5-8.
Can you send a screen print of Preview doing this?

**Comment by JorjMcKie** [comment]
I suspect, when the Apple app talks of "bookmarks", it means its own method of taking bookmarks, which is independent of PDF. As I said: in PDF bookmark == outline.

If this suspicion is true, then Preview cannot show TOCs - whatever / whoever created them. My iPhone at least does not display the manuals TOC.

**Comment by xyliu** [comment]
Here is the screenshot of Preview doing with  Adobe Manual.  It shows the 'ToC' as Toc instead of bookmark.  Other comments are shown as  "highlights and notes".

<img width="461" alt="screen shot 2018-07-03 at 8 05 33 am" src="https://user-images.githubusercontent.com/561772/42191908-0a809552-7e98-11e8-8f0a-9f4d6a3b7e08.png">
<img width="723" alt="screen shot 2018-07-03 at 8 05 13 am" src="https://user-images.githubusercontent.com/561772/42191909-0ac992e8-7e98-11e8-801e-78cfb09b9ae7.png">

**Comment by JorjMcKie** [comment]
Great, thanks a lot. Now I am convinced.
This means, that there is some difference in the TOC declarations, that Preview finds disturbing - in contrast to everyone else.

I will keep checking. I need your help here, because I do not have a Mac, and I don't want to create patches that I cannot test for their effect beforehand.

I am generating outline items from PDF source syntax in Python. This happens in file `utils.py`. If I send you an "experimental" new version of this file: could you manually replace the one you have in your Python installation with it and try out any effect?

**Comment by xyliu** [comment]
Sure. Glad to help.  

This line https://github.com/rk700/PyMuPDF/blob/master/fitz/utils.py#L652 might have syntax issue. :)

> I am generating outline items from PDF source syntax in Python. This happens in file utils.py. If I send you an "experimental" new version of this file: could you manually replace the one you have in your Python installation with it and try out any effect?

**Comment by JorjMcKie** [comment]
Oops - you are quite right. This error luckily never occurred :-)
Here is a version, that might work for you:
[utils.py.zip](https://github.com/rk700/PyMuPDF/files/2159752/utils.py.zip)
Thanks for your cooperation!

**Comment by xyliu** [comment]
Tried with utils.py.zip, the result is same as before.  :( 
I added log in utils.py to make sure the program use the new version.

$ diff -urN utils.py-old utils.py 
--- utils.py-old	2018-07-03 22:59:46.000000000 +0800
+++ utils.py	2018-07-03 23:07:41.000000000 +0800
@@ -747,6 +761,7 @@
         doc._updateObject(xref[i], txt)     # insert the PDF object
 
     doc.initData()
+    print("new version")
     return toclen

**Comment by JorjMcKie** [comment]
Sh... disappointing.
Some more background:
Outlines have a leading entry, the so-called Outline Root. Among other things it contains a `/Count` of hierarchy level 1 elements. Erroneously I had specified this count as a negative number (e.g. `/Count -5`). This is however only valid for the outlines themselves (and controls whether they are displayed collapsed [< 0] or expanded [> 0]).
This was what had been fixed in the new `utils.py`. But obviously it was not what `Preview` finds so disturbing ...
@rk700 - would you have any advice on how to tackle this? I know you have a Mac, too.

**Comment by rk700** [comment]
Everything seems fine here on my machine:

<img width="358" alt="screen shot 2018-07-04 at 10 13 09 am" src="https://user-images.githubusercontent.com/2336827/42253152-e7c6f8d6-7f72-11e8-8321-9872a8f57b9c.png">

System: 10.12.6
Preview: Version 9.0
Python: 3.7.0
PyMuPDF: 1.13.11

**Comment by rk700** [comment]
Here's the outputs of the script and the generated PDF file:
```bash
liuruikai756@mbp:~/Downloads$ python3 upt_toc.py
docs total page:  38
[2, 38]
row 22 ([3, 'BSD Logical Render Context Address (LRCA)', 18]): hierarchy steps must not be > 1
row 29 ([3, 'Copy Engine Logical Context Data', 24]): hierarchy steps must not be > 1
row 36 ([3, 'Video Enhancement Logical Context Data', 29]): hierarchy steps must not be > 1
intel-gfx-prm-osrc-kbl-vol03-gpu_overview.pdf
```

[intel-gfx-prm-osrc-kbl-vol03-gpu_overview.pdf](https://github.com/rk700/PyMuPDF/files/2161649/intel-gfx-prm-osrc-kbl-vol03-gpu_overview.pdf)

**Comment by xyliu** [comment]
@rk700 The file you generated is fine on my Mac. Thanks! 
My env:
System: 10.13.5 (17F77)
Preview: Version 10.0 (944.5)
Python 3.6.5 :: Anaconda custom (64-bit)
PyMuPDF: 1.13.11

**Comment by JorjMcKie** [comment]
So what is the conclusion - where are we with the issue?

**Comment by rk700** [comment]
@xyliu Also no TOC here in Preview 9.0

Maybe different Python version? I installed Python 3 with brew and PyMuPDF with pip3.

**Comment by xyliu** [comment]
@rk700 ,  I will try with python3 on my Linux box instead of Anaconda.

**Comment by xyliu** [comment]
Tried with Ubuntu16.04 with python3.5 installed through apt, the generated document has ToC and can be recognized.

**Comment by JorjMcKie** [comment]
Any news here? Can we close the issue?

**Comment by ousia** [comment]
@JorjMcKie, I would say the issue has been fixed (if there was one).

@xyliu, it seems that _Preview_ might handle outlines in two different ways (_Evince_ does the same):

1. _Outlines_ shows the outlines that the PDF document has.

1. _Bookmarks_ shows the ones added by the user.

Sorry, my explanation doesn’t use the parlance from the PDF spec, but here you have an image.
 
![evince-two-ways](https://user-images.githubusercontent.com/203767/43674584-9709567e-97d6-11e8-8651-b9058aa64fca.png)

**Comment by ousia** [comment]
@JorjMcKie, it is a pleasure to contribute to this project with the very minimal knowledge I have (no _Python_, but a very basic understanding of PDF 😎).

I have just discovered that _Evince_ doesn’t store what it names as _bookmarks_ in the PDF document. I guess that _Preview_ might be doing the same.

@xyliu, I wonder whether _Preview_ allows the user to create bookmarks. In that case, are they available when browsing the PDF document in another viewing program?

**Comment by xyliu** [comment]
@ousia, Seems I can only add "**highlights and notes**". I can't add "T**able of contents**" nor "**Bookmarks**" with _Preview_.

@JorjMcKie,  I use Ubuntu 16.04 and python3 to create the 'ToC' and now I can use the pdf files for Mac. It's OK for me to close the issue. Just curious on why the problem might be the App or python related.

**Comment by JorjMcKie** [comment]
@xyliu thank you for bringing up the issue - even if no real explanation could be found.
I would agree with you:
Let's close the issue and acknowledge that there are more secrets between heaven and earth than the combined wisdom of mankind can ever explain ...

One last resort might have been submitting an inquiry to Apple with an example PDF and ask them WTF is going on with Preview.

But let's close it for now.
