### ISSUE TITLE
setup.py only accounts for linux + darwin

### ISSUE THREAD

**Issue by rainerduffner** [rk700/PyMuPDF#186]
Hi,

I don't have a patch at hand, but there should also be a section for BSD.
I guess it can be identical to the darwin-case.

The generic case does not work because it does not find the fitz.h header (and other stuff).

**Comment by JorjMcKie** [comment]
What do you suggest:
Alter the darwin branch of the if statement (`elif sys.platform.startswith('darwin'):`) to include what appears in the BSD case? What **does** appear as `sys.platform` string in BSD?
Another option would be to put the windows case in an `elif` and repear the darwin case in the `else`.

**Comment by JorjMcKie** [comment]
May `sys.platform == "freebsd"`?

**Comment by JorjMcKie** [comment]
How about this:
Change line 21 of `setup.py` from this
```python
elif sys.platform.startswith('darwin'):
```
to this:
```python
elif sys.platform.startswith(('darwin', 'freebsd')):
```

You anyway have to adjust the include and lib directories, so you should be fine.

**Comment by rainerduffner** [comment]
I'll try in the evening.
No time right now.

**Comment by JorjMcKie** [comment]
As a side remark: from what I have read, you may be able to also use one of the Linux wheels under BSD ...

**Comment by JorjMcKie** [comment]
Please re-open if your issue was not resolved.
