### ISSUE TITLE
error

### ISSUE THREAD

**Issue by JonhSilver** [rk700/PyMuPDF#188]
without tools i got error

error: Unable to read ICC workflow
warning: Attempt to read Output Intent failed

with tools:
```
import fitz
import re
p = re.compile('[\d*]{8,9,10}')
doc = fitz.open("s2.pdf")
tools = fitz.Tools()
for i in range(doc.pageCount):
	tools.empty_store()
	page = doc[i]
	text = page.getText("text")
	print('%r - %s' % (i, p.findall(text)))

```

Traceback (most recent call last):
  File "C:\Python36\ExtractPDF.py", line 22, in <module>
    tools.empty_store()
  File "C:\Python36\lib\site-packages\fitz\fitz.py", line 3475, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Tools, name)
  File "C:\Python36\lib\site-packages\fitz\fitz.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__nam
e__, name))
AttributeError: 'Tools' object has no attribute 'empty_store'

**Comment by JorjMcKie** [comment]
The method `empty_store()` has been removed. Use `Tools.store_shrink(percent)` to shrink by `percent` percentage instead. A value of 100 or more will empty the store.
Can't remember the version number when this change happened.

**Comment by JonhSilver** [comment]
```
import fitz
import re
p = re.compile('[\d*]{8,9,10}')
doc = fitz.open("s1.pdf")
tools = fitz.Tools()

for i in range(doc.pageCount):
	tools.store_shrink(100)
	page = doc[i]
	text = page.getText("text")
	print('%r - %s' % (i, p.findall(text)))
doc.close()
```

error: Unable to read ICC workflow
warning: Attempt to read Output Intent failed

**Comment by JorjMcKie** [comment]
Please send me a testfile to reproduce the situation

**Comment by JorjMcKie** [comment]
BTW you can make your for loop like so:

```python
for page in doc:
    ...
    print('%r - %s' % (page.number, p.findall(text)))

**Comment by JonhSilver** [comment]
sended

**Comment by JorjMcKie** [comment]
What you sent me is **not** a PDF, but something written in kyrillic letters - maybe a SW installation :-(

**Comment by JonhSilver** [comment]
it is not cyrilic it is ISO-8859-4 - Latin 4
but pdf or no i dont know, hex header shows %PDF-1.6

Text extracted correct, but errors appears, how to disable showing this error?

**Comment by JorjMcKie** [comment]
Ah, now I understand: you are concerned about the error message.
Please just ignore it - it cannot be suppressed unfortunately.

In PyMuPDF, we are not using / supporting ICC profiles. This has no further implications - even if a PDF makes use of such things as in your case.

So I decided to disable this support alltogether in the generation of MuPDF. After all, **enabling** it results in a much larger binary PyMuPDF file (about 0.5 MB) - without any benefit except no such error messages.

**Comment by Alamin-pro** [comment]
'Page' object has no attribute 'set_grayscale' while converting pdf to grayscale in fitz
please someone should help me find this`   for i in range(doc.page_count):
    page = doc[i]
    page.set_grayscale()
    page.save()

doc.save("grayscale.pdf") `

**Comment by Alamin-pro** [comment]
please how can i convert colored pdf to black and white

**Comment by JorjMcKie** [comment]
The only way is this:
```python
import fitz
doc = fitz.open("input.pdf")
new = fitz.open()  # output pdf
for page in doc:
    newpage = new.new_page(width=page.rect.width, height=page.rect.height)
    pix = page.get_pixmap(dpi=150,colorspace=fitz.csGRAY)
    newpage.insert_image(newpage.rect, pixmap=pix)
new.ez_save("grayscale.pdf")
```

**Comment by Alamin-pro** [comment]
thanks sir, but actually when i am trying to read objects inside the pdf and concatenate them inside a pandas data frame it says no object to concatenate, it is seeing the page as an image without any object, is there any way please to convert them directly  without converting the pages to images? thanks

**Comment by JorjMcKie** [comment]
> thanks sir, but actually when i am trying to read objects inside the pdf and concatenate them inside a pandas data frame it says no object to concatenate, it is seeing the page as an image without any object, is there any way please to convert them directly without converting the pages to images? thanks

No, sorry there is not.

**Comment by Alamin-pro** [comment]
okay thanks
