### ISSUE TITLE
cannot find builtin CJK font

### ISSUE THREAD

**Issue by HazyGuo** [rk700/PyMuPDF#189]
I got this error while running the pdfviewer(wx).py file. What is the CJK font?

**Comment by JorjMcKie** [comment]
CJK = China, Japa, Korea
Can you send me an example PDF? Maybe there is a bigger issue underneath ...

**Comment by JorjMcKie** [comment]
Using PDFdisplay.py works ok?

**Comment by HazyGuo** [comment]
sorry, the pdf is confidential data getting from the financial customer.

**Comment by HazyGuo** [comment]
there is no error appear, but the text content can't display.
![image](https://user-images.githubusercontent.com/7529183/43069782-9e61a456-8ea0-11e8-919f-85ef4796aefd.png)

**Comment by JorjMcKie** [comment]
uhhh that's bad!!!

I am afraid I have to change the way how I generate PyMuPDF and MuPDF then.
Currently I am excluding fonts from the MuPDF generation whenever I thought I can do that. Obviously I have to re-consider this ...

How urgent is your issue? I need a few days to change and upload a new version ...

**Comment by HazyGuo** [comment]
thanks for your reply, and maybe one week remains for my issue.

**Comment by JorjMcKie** [comment]
I just checked what will happen if I include minimal CJK support in my MuPDF and subsequent PyMuPDF generation.

1. I do not know if this already solves your problem
2. It increases the size of the PyMuPDF binary (`_fitz<...>.so` or `_fitz.pyd`) from about 3 or 4 MB to 8 or 9 MB.

Are you using Windows? In that case I could send you a wheel to check if your issue is already solved ...

**Comment by HazyGuo** [comment]
yes, i write test code in windows. 
it's pleasure that you can send it to my email(guoqinghe99@gmail.com)

**Comment by JorjMcKie** [comment]
I Need your Python and bitness combination, like Python 3.6, 64bit or similar

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: HazyGuo <notifications@github.com>
Gesendet: Monday, July 23, 2018 7:16:39 AM
An: rk700/PyMuPDF
Cc: Jorj X. McKie; Comment
Betreff: Re: [rk700/PyMuPDF] cannot find builtin CJK font (#189)


yes, i write test code in windows.
it's pleasure that you can send it to my email(guoqinghe99@gmail.com<mailto:guoqinghe99@gmail.com>)

**Comment by HazyGuo** [comment]
my python version is 3.5, and the operating system is windows 64

**Comment by JorjMcKie** [comment]
You should have received `PyMuPDF-1.13.15-cp35-cp35m-win_amd64.whl` by now. Please install it via

```
python -m pip install --upgrade PyMuPDF-1.13.15-cp35-cp35m-win_amd64.whl
```

**Comment by HazyGuo** [comment]
thank you very much, it can extract text content from my pdf.
but the structure of the html page rendered by the extracted content seems not like the original in the pdf.
![image](https://user-images.githubusercontent.com/7529183/43075740-3bb8f5e8-8eb4-11e8-92d2-b058f2825c27.png)
in addition, can i distinguish which content is come from the table and which is not?

**Comment by HazyGuo** [comment]
thanks for your careful answer, and i get it now.

**Comment by JorjMcKie** [comment]
@HazyGuo - Hi again!
I have written a little script that takes the words of a document page and creates a new word list with the following properties:

1. duplicate words omitted (i.e. words with same text and page position - which happened in your example).

2. sorted by ascending vertical position, then by horizontal position

3. combined words into one if the gap between them is very small

In your example document, this script creates a list of 70 words, all numbers are correctly produced, no duplicate words, etc.

Hope it helps!
[unify-words.zip](https://github.com/rk700/PyMuPDF/files/2223198/unify-words.zip)
