### ISSUE TITLE
page.getText() reorders words on extraction

### ISSUE THREAD

**Issue by wave-DmP** [rk700/PyMuPDF#195]
Hi again!

I've encountered a problem extracting text from a manually OCR'ed document.

What I am doing is trying to find multi-word terms in the document

The page.getText() command extracts lines in a skewed order word1 word4 word3 word2.  I'm guessing that this is because the coordinates of the words are not exactly on the same line, i.e. word3 is a little lower than word4 and is hence determined to be after word4.

Is it possible to prioritise the x-coordinate when ordering the text blocks that are grouped to be on the same line?  Is there a threshold that sets off any grouping procedures?

Many thanks!

**Comment by JorjMcKie** [comment]
Hi there,

this is a common problem with all PDFs - not just the OCR-ed ones. Have a look at [this](https://github.com/rk700/PyMuPDF/wiki/How-to-extract-text-from-a-rectangle) Wiki. The script extracts words from a given rectangle, re-establishing reading order.

Try using using it by setting the rectangle to the whole page or whatever.

You will find that the ``itertools.groupby()`` function is used in it.

If the script still doesn't deliver quite the desired result, modify it such that coordinates get rounded to integers or something even coarser.

**Comment by JorjMcKie** [comment]
Just to put things in right perspective:

All text extraction methods retrieve text as it is stored in the document. No effort is undertaken to "re-order" it - let alone that this may be impossible to do (think of text orientation, other languages like Arabian or Chinese, etc.). Where text appears "out of reading sequence", this goes back to the software (or guy) that created the document.

This is quite often the case, e.g. the "total pages" number may have been inserted in each page's header **after end of document production**. In that case that number will appear at the end of any text extraction although a PDF viewer will position it correctly at the top, using its accompanying positioning information.

**Comment by wave-DmP** [comment]
Apologies for not responding earlier!

I've taken a closer look at the results from my OCR dataframe and the specific line I'm looking at seems to be OCR'ed correctly, the bounding boxes of the words are on exactly the same y-coord pixel, of the same height and in the correct order along the x-coord.

I proceed to insert them into the pdf page as non-overlayed textboxes using the precise coordinates from my result, and when performing the getText() command, the read order gets revered in some places for no apparent reason.  Maybe there is an override where I can tell pymupdf to read only form left to right?

Unfortunately, I cannot post my data on here due to data protection issues...

**Comment by JorjMcKie** [comment]
No, there is no such option, sorry. You must fall back to sorting the extracted text yourself.

I cannot tell what might have happened in your case. But all the getText* methods extract return stuff in a sequence as is stored in the file.
You can double check using the `mutool draw` utility using its text output option. There too, you will see the stored sequence of text portions.

Long ago I submitted a similar request via bug report to MuPDF: their response came quickly and clearly: you have all information you need to establish text ordering to your liking ==> won't fix.
