### ISSUE TITLE
[Feature] Add "rawdict" output option to Page.getText()

### ISSUE THREAD

**Issue by mozbugbox** [rk700/PyMuPDF#199]
The current `dict` output of `Page.getText(output)` joins the `char` items together of a `font` span and drops the `bbox` info of the chars.

When doing interactive text selection, we need to know the `bbox` info down to the each `char`. Currently, I parse the `xml` output result to find out the per char `bbox`. Of course the `xml` output dropped info of images. This is bad for select/save image action. 

The code sites at [`TextSelection.text_tree()`](https://gitlab.com/mozbugbox/youshen/blob/master/youshen/muview.py#L342)

It will be great to have an output option which preserves all the information of text/image in a dict tree form. Like a `rawdict` or `dictraw` which contains the `block->line->font->char/image` tree and all the other attached attributes preserved.

Thanks

**Comment by JorjMcKie** [comment]
It sounds to me like a `page.getText("dict")` version with more detail.
Currently, the bottom level information is a "span" which contains chars (1) of the same line (2) having the same font properties.
But even this span level has no longer a bbox, only the line one level higher.

If I would do this:
1. Add a new level below span, called maybe "chars" and obviously containing a list of chars, each with its bbox
2. add bbox information to the span level (nothing else than the rect unification of its characters)
3. give the whole thing a new text parameter value as you suggest

... would you be satisfied?

**Comment by JorjMcKie** [comment]
Another way to go might be extending the XML way.
I am hesitant though, because this currently is wrapped original MuPDF code. I would probably have to rewrite major parts and, prior to this, do research on correct XML syntax for image data

**Comment by mozbugbox** [comment]
The origin intention of the feature request is that constructing a rawdict from inside fitz module will be faster than the go through the round trip from rawdata->xml->dict(basically rawdata). The included image info was just a bonus. 

With image data embedded inside XML, I assume that parsing xml will take much more time.

**Comment by mozbugbox** [comment]
I've made a hack of `rawdict` at commit 10e7ba4800bc1b97c8c75ddc714239e662d1f161

**Comment by JorjMcKie** [comment]
wow - thank you very much. Amazing develpment speed I must say.
Looks good at first sight.
Also good to know that some people are actually looking deep into the code ...
Have you done any tests yet?
I will certainly start working on it today.

**Comment by mozbugbox** [comment]
I did the most simple test: output a tree of text items with `char` as leaves. The code works in that sense. 

However, I skipped accumulating `bbox` from chars to a line bbox/linerect. Actually the code short circuit the loop over lines, not very nice :(.

I guess you do the bbox calculation because the bbox result from mupdf is not always valid/stable?

**Comment by JorjMcKie** [comment]
Yes, exactly that.

I have a PDF sitting in my test files, for which MuPDF returns empty bbox'es for characters encoded in one specific font. This emptiness is always caused by zero height, never by width.
And, because MuPDF calculates the bbox'es for the higher levels as rect unifications of the char rects, those are empty as well when this happens.
I have submitted a bug to MuPDF's months ago  - without reaction yet.
So, what I decided to do is forcing the char bbox to have a height of fontsize if it is empty (remarkably, the **fontsize** for this dubious font is specified correctly).

This decision entailed duplicating MuPDF's code for line and block bbox calculation.

If you have an idea how to handle this differently - great! An obvious suspicion is that the problem is cause by the font itself. I just have not enough detail knowledge about fonts to trace anything down here.

**Comment by mozbugbox** [comment]
For the test.pdf at (https://bugs.ghostscript.com/show_bug.cgi?id=699488), I extracted the embeded fonts with
```
    mutool extract test.pdf
```
And then dumped the resulting fonts with `ftdump` (part of freetype tools).

It seems that even though the `text height` was set properly in the result, the `ascent`, `descent`, `Global BBox` were all set to 0 or maybe unset. I don't know if this is the culprit, but the other embedded fonts which I tested, did have those attributes properly set.

```
$ ftdump EBNPGC+Swiss721BT-Light-0019.cid 
There is 1 face in this file.

----- Face number: 0 -----

font name entries
   family:     Swiss721BT-Light
   style:      Regular
   postscript: Swiss721BT-Light

font type entries
   FreeType driver: cff
   sfnt wrapped:    no
   type:            scalable
   direction:       horizontal
   fixed width:     no
   glyph names:     no
   EM size:         1000
   global BBox:     (0,0):(0,0)
   ascent:          0
   descent:         0
   text height:     1200
   glyph count:     58
```

**Comment by JorjMcKie** [comment]
Thank you for this!
I hear you say, that this font indeed is the problem's cause, and that sounds right to me.
When I did my investigations, I also made sure that the various mutool output variants also produced the same error (among them the HTML / XML outputs), i.e. that it is not PyMuPDF.

Anyway, my take is that building in this shield against such cases is better to have than not, isn't it?

In the meantime I have taken your code and tested it with a number of cases, including non-Latin fonts (Chinese) and non-horizontal text.

It all went fine. Thanks again.

I would like to publish the patch as v.1.13.18. What is your timeframe expecting this? Any hurry?

**Comment by mozbugbox** [comment]
Oh, I'm not in any hurry. It's just a personal project to make reading PDF fit my taste.

**Comment by mozbugbox** [comment]
I just grepped the mupdf source, indeed, it seems that the function at `source/fitz/stext-device.c/add_char_to_line()` does make use of the `ascent`, `decent` and `bbox` of the font to derive the `bbox` of a char.

It could fallback to glyph bbox when the ascent, descent, bbox are invalid. Or maybe freetype has some flag to deal with broken global ascent, descent, this I don't remember well.

**Comment by mozbugbox** [comment]
BTW, there was a leak on `buff` in `JM_extract_stext_textblock_as_dict()` after the loop over `ch`.
```
        if (font)
        {
            JM_style_end_dict(ctx, buff, span, spanlist);
            Py_CLEAR(span);
            font = NULL;
        }
```
Look like it missed a `fz_drop_buffer(ctx, buff);`

**Comment by JorjMcKie** [comment]
Right! Thanks!
