### ISSUE TITLE
fill pdf forms with some values how

### ISSUE THREAD

**Issue by manish59** [rk700/PyMuPDF#201]

**Comment by JorjMcKie** [comment]
here is a little synopsis packed in a ZIP:

* `widgettest.py` creates a new simple form PDF, including field values for some of them: `widgettest.pdf`
* `modify-field.txt` is an IDLE session that modifies the first field of the PDF's page 0, giving it a new field value.
* the result is then stored in a new PDF `changed-field.pdf`. Could also have been updated in-place via `doc.saveIncr()` (incremental save).
* apart from the field value, a whole bunch of other field (= "widget") properties could also have been modified: text color, field position, and what not

[pdf-forms.zip](https://github.com/rk700/PyMuPDF/files/2359698/pdf-forms.zip)
