### ISSUE TITLE
Can we detect any javascript in pdf 

### ISSUE THREAD

**Issue by manish59** [rk700/PyMuPDF#203]
I want to know if a pdf has javascript in it or audio or video in it. Can anyone help me about this.

**Comment by JorjMcKie** [comment]
There are some options. I need a little more time to investigate everything.
What it always possible is analyzing the source of the PDF's objects, and, e.g. check whether an object is a media, or javascript, or whatever object. This is easily doable in PyMuPDF. The main task would be figuring out, how to recognize each of the relevant object types.

This is what I need some more time for  - I'll be back at home early next week.

**Comment by manish59** [comment]
Thanks buddy for the effort to make this beautiful pdf library

**Comment by JorjMcKie** [comment]
Hi again - back at home now.
As I indicated in my previous post, the easiest way to check the presence of these things, is scanning the PDF's object definitions:

```python
import fitz

doc = fitz.open("some.pdf")
xrefl = doc._getXrefLength()           # number of objects in the PDF
javascript = movie = sound = False     # initialize indicators
for xref in range(1, xrefl):           # scan through all objects
    obj = doc._getXrefString(xref)     # read object description
    if "/JavaScript" in obj:
        javascript = True
    if "/Movie" in obj:
        movie = True
    if "/Sound" in obj:
        sound = True

print("JavaScript: %s, Movies: %s, Sounds: %s" % (javascript, movie, sound))
```

More sophisticated answers of course need more detailed analysis.
Movies and sounds usually occur in respective annotation types. So you should also find them if you scan the annotations for each page.
JavaScripts could be used for a lot of things in a PDF - also depending on the PDF version the file is using.
E.g. they could be used for handling form fields (widgets), or for performing actions at certain events (document open / close / print ...).

But for a raw check the above may suffice.

**Comment by JorjMcKie** [comment]
Commenting my previous post:
The 3 separate `if` statements could be glued together using `elif` instead - for a minimally higher execution speed.
Closing the issue for now. Pls. let me know if I can help otherwise.
