### ISSUE TITLE
Broken Link in README.md

### ISSUE THREAD

**Issue by pmariglia** [rk700/PyMuPDF#205]
https://github.com/rk700/PyMuPDF/tree/master/doc/pymupdf.pdf

should be 

https://github.com/rk700/PyMuPDF/blob/master/doc/PyMuPDF.pdf

in the [README.md](https://github.com/rk700/PyMuPDF/blob/master/README.md), line 73

**Comment by JorjMcKie** [comment]
Thanks - will correct this rightaway
