### ISSUE TITLE
Create pdf with utf8 text

### ISSUE THREAD

**Issue by mxposed** [rk700/PyMuPDF#207]
Hi. It would be helpful if you had an example of how to add utf8 text to new pdf.
The demo code here https://github.com/rk700/PyMuPDF/blob/master/demo/text2pdf.py does not work:

```
Traceback (most recent call last):
  File "test2.py", line 73, in <module>
    fwidths = doc._getCharWidths("F0")   # get glyph widths of font
TypeError: _getCharWidths() missing 1 required positional argument: 'limit'
```

Adding text with default font like `Helvetica` results in non-ascii characters to be replaces as `?`

**Comment by JorjMcKie** [comment]
Will do by tomorrow. Key to success is choosing the right font ...
That demo only covers a corner functionality.

Von meinem iPhone gesendet

Am 02.10.2018 um 07:31 schrieb Jay Bird <notifications@github.com<mailto:notifications@github.com>>:


Hi. It would be helpful if you had an example of how to add utf8 text to new pdf.
The demo code here https://github.com/rk700/PyMuPDF/blob/master/demo/text2pdf.py does not work:

Traceback (most recent call last):
  File "test2.py", line 73, in <module>
    fwidths = doc._getCharWidths("F0")   # get glyph widths of font
TypeError: _getCharWidths() missing 1 required positional argument: 'limit'


Adding text with default font like Helvetica results in non-ascii characters to be replaces as ?

**Comment by JorjMcKie** [comment]
Here is a sample script.
[chinese-tb.zip](https://github.com/rk700/PyMuPDF/files/2439407/chinese-tb.zip)
It inserts a Latin-Chinese text mixture in a text box. And does some text rotation in that box and above that in addition rotates the text box itself.
As I wrote above: this works if the right font file is chosen.
With the new MuPDF version 1.14.0 I will probably include y reference to builtin CJK fonts (Chines, Japan, Korea), which do not incur inclusion of additional font file data.

**Comment by mxposed** [comment]
Thank you!
