### ISSUE TITLE
detect text color

### ISSUE THREAD

**Issue by manish59** [rk700/PyMuPDF#208]
Hi,

I already mentioned about this problem but it was closed. I want to detect pdf text color  very badly it is one of the big requirement for me for an experiment. is there any way we can detect text color i searched every where none of it says how except some adobe paid softwares. please let me know if there is any way to detect color there must be a way to detect color of the text

**Comment by JorjMcKie** [comment]
Hi,
sorry, I thought I had answered that: no there is **no way** to do that with (Py-) MuPDF.
Not an easy one at least to my knowledge.
You can of course always write an interpreter for PDF operator syntax, however, and PyMuPDF will give you access to all the information you need.

Here is an example for what you would be faced with. This is a PDF page with 11 text lines in different colors, followed by the page's `/Contents` object producing this output:
![grafik](https://user-images.githubusercontent.com/8290722/46465997-1cfb7c80-c798-11e8-85a7-b46f280a97b0.png)

Here's how to print the /Contents stream:

```python
In [1]: import fitz
In [2]: doc = fitz.open("from-blue-to-red.pdf")
In [3]: xref = doc[0]._getContents()[0] # /Contents object's xref of page 0
In [4]: c = doc._getXrefStream(xref).decode() # get the source
In [5]: print(c)

n q BT
1 0 0 1 50 770 Tm /Helvetica 12 Tf 0 0 1 rg [<6368616e67696e672066726f6d20626c756520746f2072656420696e203131207374657073>]TJ
0 -14.4 TD
ET Q

n q BT
1 0 0 1 55 755.6 Tm /Helvetica 12 Tf 0.1 0 0.9 rg [<6368616e67696e672066726f6d20626c756520746f2072656420696e203131207374657073>]TJ
0 -14.4 TD
ET Q

n q BT
1 0 0 1 60 741.2 Tm /Helvetica 12 Tf 0.2 0 0.8 rg [<6368616e67696e672066726f6d20626c756520746f2072656420696e203131207374657073>]TJ
0 -14.4 TD
ET Q

n q BT
1 0 0 1 65 726.8 Tm /Helvetica 12 Tf 0.3 0 0.7 rg [<6368616e67696e672066726f6d20626c756520746f2072656420696e203131207374657073>]TJ
0 -14.4 TD
ET Q

n q BT
1 0 0 1 70 712.4 Tm /Helvetica 12 Tf 0.4 0 0.6 rg [<6368616e67696e672066726f6d20626c756520746f2072656420696e203131207374657073>]TJ
0 -14.4 TD
ET Q

n q BT
1 0 0 1 75 698 Tm /Helvetica 12 Tf 0.5 0 0.5 rg [<6368616e67696e672066726f6d20626c756520746f2072656420696e203131207374657073>]TJ
0 -14.4 TD
ET Q

n q BT
1 0 0 1 80 683.6 Tm /Helvetica 12 Tf 0.6 0 0.4 rg [<6368616e67696e672066726f6d20626c756520746f2072656420696e203131207374657073>]TJ
0 -14.4 TD
ET Q

n q BT
1 0 0 1 85 669.2 Tm /Helvetica 12 Tf 0.7 0 0.3 rg [<6368616e67696e672066726f6d20626c756520746f2072656420696e203131207374657073>]TJ
0 -14.4 TD
ET Q

n q BT
1 0 0 1 90 654.8 Tm /Helvetica 12 Tf 0.8 0 0.2 rg [<6368616e67696e672066726f6d20626c756520746f2072656420696e203131207374657073>]TJ
0 -14.4 TD
ET Q

n q BT
1 0 0 1 95 640.4 Tm /Helvetica 12 Tf 0.9 0 0.1 rg [<6368616e67696e672066726f6d20626c756520746f2072656420696e203131207374657073>]TJ
0 -14.4 TD
ET Q

n q BT
1 0 0 1 100 626 Tm /Helvetica 12 Tf 1 0 0 rg [<6368616e67696e672066726f6d20626c756520746f2072656420696e203131207374657073>]TJ
0 -14.4 TD
ET Q

In [6]: 
```

Every text piece is enclosed in a string pair `BT - ET` together with font and position information. The color in this example is RGB, so we see 3 floats appended by string `rg`. The color spec in general need not be positioned like in this example.

**Comment by JorjMcKie** [comment]
Addendum: the following PDF operator syntax will produce exactly the same page appearance. The reformatting has been caused by optimizing the PDF (`mutool clean -ggggsz from-blue-to-red.pdf`, equivalent to `doc.save("...", clean=True, garbage=4, deflate=True`). Note how the color specs have changed position ...
```
q
n
q
BT
1 0 0 1 50 770 Tm
0 0 1 rg
/Helvetica 12 Tf
[(changing from blue to red in 11 steps)] TJ
/Helvetica 12 Tf
0 -14.4 TD
ET
Q
n
q
BT
1 0 0 1 55 755.6 Tm
.1 0 .9 rg
/Helvetica 12 Tf
[(changing from blue to red in 11 steps)] TJ
/Helvetica 12 Tf
0 -14.4 TD
ET
Q
n
q
BT
1 0 0 1 60 741.2 Tm
.2 0 .8 rg
/Helvetica 12 Tf
[(changing from blue to red in 11 steps)] TJ
/Helvetica 12 Tf
0 -14.4 TD
ET
Q
n
q
BT
1 0 0 1 65 726.8 Tm
.3 0 .7 rg
/Helvetica 12 Tf
[(changing from blue to red in 11 steps)] TJ
/Helvetica 12 Tf
0 -14.4 TD
ET
Q
n
q
BT
1 0 0 1 70 712.4 Tm
.4 0 .6 rg
/Helvetica 12 Tf
[(changing from blue to red in 11 steps)] TJ
/Helvetica 12 Tf
0 -14.4 TD
ET
Q
n
q
BT
1 0 0 1 75 698 Tm
.5 0 .5 rg
/Helvetica 12 Tf
[(changing from blue to red in 11 steps)] TJ
/Helvetica 12 Tf
0 -14.4 TD
ET
Q
n
q
BT
1 0 0 1 80 683.6 Tm
.6 0 .4 rg
/Helvetica 12 Tf
[(changing from blue to red in 11 steps)] TJ
/Helvetica 12 Tf
0 -14.4 TD
ET
Q
n
q
BT
1 0 0 1 85 669.2 Tm
.7 0 .3 rg
/Helvetica 12 Tf
[(changing from blue to red in 11 steps)] TJ
/Helvetica 12 Tf
0 -14.4 TD
ET
Q
n
q
BT
1 0 0 1 90 654.8 Tm
.8 0 .2 rg
/Helvetica 12 Tf
[(changing from blue to red in 11 steps)] TJ
/Helvetica 12 Tf
0 -14.4 TD
ET
Q
n
q
BT
1 0 0 1 95 640.4 Tm
.9 0 .1 rg
/Helvetica 12 Tf
[(changing from blue to red in 11 steps)] TJ
/Helvetica 12 Tf
0 -14.4 TD
ET
Q
n
q
BT
1 0 0 1 100 626 Tm
1 0 0 rg
/Helvetica 12 Tf
[(changing from blue to red in 11 steps)] TJ
/Helvetica 12 Tf
0 -14.4 TD
ET
Q
Q

```

**Comment by JorjMcKie** [comment]
Just closed it for me easier keeping track of To Dos. Please do not hesitate to re-open or submit another issue if you need any help (or find bugs).

**Comment by manish59** [comment]
n q BT
1 0 0 1 50 770 Tm /Helvetica 12 Tf 0 0 1 rg [<6368616e67696e672066726f6d20626c756520746f2072656420696e203131207374657073>]TJ
0 -14.4 TD
ET Q

Here how to print rgb values of each character? and what is the meaning of this
[<**6368616e67696e672066726f6d20626c756520746f2072656420696e203131207374657073>]TJ**

**Comment by JorjMcKie** [comment]
RGB blue = ``0 0 1 rg`` above. This value remains in effect and applies to all text following until set to another value.
The bracketed stuff ahead of the ``TJ`` operator is the written text (in hex).
For details on PDF opertor syntax see the manual chapter "A Operator Summary" on page 985.

**Comment by rakesh4real** [comment]
The methods are obsolete now. Use

```
def handle_page_highlights(page):
    wordlist = page.getText("words")  # list of words on page
    wordlist.sort(key=lambda w: (w[3], w[0]))  # ascending y, then x

    highlights = []
    annot = page.firstAnnot
    while annot:
        if annot.type[0] == 8:
            highlights.append(_parse_highlight(annot, wordlist))
            print(annot.colors)
        annot = annot.next
    return highlights
```
