### ISSUE TITLE
Transformation Matrix, or similar function

### ISSUE THREAD

**Issue by erlenlh** [rk700/PyMuPDF#210]
I'm trying to use the PyMuPDF library to draw different rectangles over PDF documents. 
I'm running into an issue where if i draw a Rect with coordinates (50,50,100,100) on two different PDF's, one will get drawn in the bottom left corner, while the other while be drawn in the top right. 

Seems like in some PDF's the origin of the coordinates start in the top left, and others in the bottom left. 
Inspecting the Page.rect or media_box will in both cases display top_left as coordinates (0,0).

Obviosuly fixing my code to adapt to the different situations should be easy enough, but I cant find a reliable way to determine where the origin actually is, since top_left always equals 0,0. 
I imagine this would best be solved by some kind of transformation matrix, but can't seem to figure out if such a feature exists. 

Thanks for all your work on the library!

**Comment by erlenlh** [comment]
I'll add that making an annotation on the point returned by the drawRect function, places the annotation in the top left even when my figure gets placed in the bottom left.

**Comment by JorjMcKie** [comment]
Can you please send me two examples showing the unexpected different behaviour?

I need to have look, thanks.

**Comment by JorjMcKie** [comment]
Forgot an even better possibility:

Instead of loading the whole cleaned PDF in memory, one can also just "clean" every page before it actually is being processed. There is a low-level method, `Page._cleanContents()` for that purpose. It will do the same job, is faster and will not need additional memory:

```python

doc = fitz.open("some.pdf")
doc[0]._cleanContents()    # clean the page's operator syntax
page = doc[0]              # now load the page for usual processing

```
