### ISSUE TITLE
Something wrong in the doc

### ISSUE THREAD

**Issue by eEhyQx** [rk700/PyMuPDF#211]
PyMuPDF.pdf page 28
>>> doc.save(p_odd) # and do the same with the odd pages
>>> doc.save("odd.pdf")
prehaps should be
>>> doc.select(p_odd) # and do the same with the odd pages
>>> doc.save("odd.pdf")

**Comment by JorjMcKie** [comment]
You are right: the respective `doc.select` dtatement is missing there - thanks!
Will correct it with the next version.

**Comment by JorjMcKie** [comment]
Correction enclosed in next version.
