### ISSUE TITLE
Extract text produces invalid unicode characters

### ISSUE THREAD

**Issue by skylord123** [rk700/PyMuPDF#212]
I've been using PyMuPDF to process thousands of PDFs. It has been great compared to any other software I have compared it to. I have hit a couple PDFs that don't seem to extract text correctly. This is the example of the text I get for page 1:

```
����������������� �������������������� ������������������� ������������� � ������������������������������������� ���������� �������������������� ��������������������������� ���������� � � � � � � ��� ���������������� ��� ���������������������������������������������� �� � ����������� � � � ������������ � � ������������� � � � ��������������� � �� ���������������� � � � ������������ � ���������������������������������������������������������������������������������������������� �������������������������������������������������������������������������������������������������� ������������������������������������������������������������������������������� � ��� ���������������� ��� ������������������������������������������������� � � ��� ���������������������������������������������������������������������������������������� � ��� �������������������������������������������������������������������������������������� � ��� ����������������������������������������������������������������������������������������� ������������������������������� � ��� �������� � ��� ���������� � ������������������������������������������������������������������������ � ��������������������������������������������������������������������������������������������� ����������������
```

Here is the PDF file that is giving me issues: [example.pdf](https://github.com/rk700/PyMuPDF/files/2511450/example.pdf)

Here is the python script I am using to convert the extracted text to JSON and then output it to stdout: [https://gist.github.com/skylord123/76f4a7cf9f194ce8bc1c7a53cd68e182](https://gist.github.com/skylord123/76f4a7cf9f194ce8bc1c7a53cd68e182)

The text can clearly be copied from the example pdf when opened in a PDF viewing program. So the text is there and accessible it's just that PyMuPDF fails to extract it properly.

Does this have anything to do with this? https://stackoverflow.com/questions/43551945/unable-to-extract-any-text-from-a-visually-text-filled-pdf

Thanks for the great software btw. Really appreciate it.

**Comment by JorjMcKie** [comment]
@skylord123 The example PDF uses fonts with a "fontfile" program - FontFile2 in this case. FontFile2 programs are **TrueType** fontfiles.

Fontfiles, if present, control the visible appearance of a character. This can also mean that the fontfile produces the appearance of, say, character "A" based on a key entirely different from ``ord("A") = 65``. Without de-assembling such a fontfile, there is no way of knowing this mapping ("encoding") between characters and their appearances.
This explains (I hope) why a PDF may look nice in any reader SW, but **ANY** text extraction program (which all are based on exclusively reading the PDF file's **source**) will fail to produce readable output.
The only way to circumvent this would be using an OCR software - sorry.

I experimented a bit:
1. converted your example.pdf to a PDF consisting of PNG images of the original pages
2. OCRed that PDF, using PDF XChange PDF Viewer as an example. [OCRmyPDF](https://github.com/jbarlow83/OCRmyPDF) may work just as well.

The result was fine.

**Comment by skylord123** [comment]
I will just OCR these documents then. Thanks for the quick & detailed response!
