### ISSUE TITLE
PDF decryption GONE!

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#214]
Found out just yesterday, that MuPDF v1.13.0 does no longer make it possible to store decrypted documents!
In v1.12.0 you could - after a successful `doc.authenticate(password)` - store a decrypted document version using `doc.save("decrypted.pdf")`.

**This no longer works!!!**

Neither works the MuPDF CLI tool `mutool clean -p password encrypted.pdf decrypted.pdf`.

IAW it is not a PyMuPDF issue.

But there is a solution to this, using PyMuPDF. The following script will create a decrypted version of the input document via the terminal command
`python decrypt.py encrypted.pdf password decrypted.pdf`
where `decrypt.py` is the following script:

```python
import sys
import fitz

print("Python:", sys.version, "\n")
print(fitz.__doc__)

if len(sys.argv) != 4:
    raise SystemExit("use: decrypt.py in.pdf password out.pdf")
fname = sys.argv[1]
passw = sys.argv[2]
ofile = sys.argv[3]

print("\ndecrypting '%s' to '%s' ...\n" % (fname, ofile))

docin = fitz.open(fname)               # open input
rc = docin.authenticate(passw)         # decrypt it

if not rc > 0:                         # check success
    raise SystemExit("wrong password")

toc = docin.getToC(False)              # save input TOC
meta = docin.metadata                  # save input meta data

docout = fitz.open()                   # new empty PDF
docout.insertPDF(docin)                # insert all input pages
docout.setMetadata(meta)               # copy of metadata
docout.setToC(toc)                     # copy of TOC
docout.save(ofile, garbage=3, deflate = True)
```

There is no similar solution using MuPDF CLI utilities. Just something coming close:

`mutool draw -o decrypted.pdf -p password encrypted.pdf` 

This will create a decrypted copy of the input. But links, annotations and bookmarks (TOC) are lost!

**Comment by JorjMcKie** [comment]
@ousia @deepgully @mozbugbox @jbarlow83 @rk700 @wilfred-kun ... and all users of this repo:

I am currently investigating what could / should be done in v1.14.

* I could restore the old situation. This would also remove advantages detailed out in previous post. I would need to develop my own version of MuPDF file `pdf-write.c`.
* I could just do nothing. After all, we do have some advantages, and there is a way to create decrypted PDF copies - see the first post.
* I could develop my own version of `pdf-write.c` as above but include an additional option, whether or not to encrypt again on `doc.save()`.

I am also digging for a solution to encrypt a PDF from the start - and maybe to also change existing passwords ...

I would appreciate any recommendations / opinions / **help(!)**.

**Comment by jbarlow83** [comment]
If you don't mind a new dependency, you could save without encryption using PyMuPDF as is, and then use my pikepdf library, which is a wrapper around qpdf, to apply encryption. pikepdf would probably be the fastest way to restore functionality. Or you could skip pikepdf and bind to libqpdf to handle encryption.

pikepdf and qpdf are both permissively licensed so you could also copy the interesting bits.

**Comment by JorjMcKie** [comment]
@jbarlow83 thank you very much for the pointer to pikepdf / qpdf!

I will have a look at that one for introducing an option to encrypt files.

As per getting the immediate problem out of the way, I have found a simple way to implement bullet point 3 above:
Document save/write methods will receive an additional option to keep or drop an **existing** encryption. This will default to decrypted save of the document to achieve compatibility with existing code.

**Comment by JorjMcKie** [comment]
**UPDATE:**

Just received a bug fix notification from MuPDF. This is going to be fixed by adding new arguments / options to `mutool clean`, `pdf_save_document` respectively.

A later MuPDF enhancement will include PDF encryption / re-encryption.
