### ISSUE TITLE
Formatting of links added with pyMuPDF

### ISSUE THREAD

**Issue by TheDocSmith** [rk700/PyMuPDF#215]
I'm looking for a way to change the default link format for links added using pyMuPDF. 
I'm adding simple navigation elements to existing PDFs. For various reasons I can't add the links directly in the creation tool. 

I'm using page.insertImage to add in various navigation images to each page, then using page.insertLink to create GOTO links from the images to predefined namedDestinations. However, when I add a link, it is viewed by clients with a visible thin black border. I'd love to make that border invisible or be able to change it's colour. All of which I can do within Acrobat itself, but I'd rather do it at the point of creation. Any ideas?

Cheers,

Rob

**Comment by JorjMcKie** [comment]
When I create links, I currently do not specify anything for the border appearance - thus allowing the reader SW to make its decision: on my Windows, Adobe and Nitro show a rectangle with a thin black border, PDF XChange, MuPDF and SumatraPDF show nothing.

I currently have no way to modify a link's appearance.
But I can add a parameter to show no border ever in the release currently in preparation.

If this is too late for you or otherwise unduly, look at the interactive session I have just done. It uses low-level methods to locate and modify the links "source" - a bit dirty, but reasonably safe:

```python
>>> ll = doc[n].getLinks() # list of all links on page n
>>> ll
[{'kind': 1, 'xref': 68, 'from': Rect(55.83330154418945, 472.4999694824219, 271.6669921875, 489.9999694824219), 'page': 1, 'to': Point(0.0, 0.0), 'zoom': 0.0}]
>>> # assume we want to change this link (xref=68), then get its source:
>>> s=doc._getXrefString(68)
>>> # insert before last 2 bytes (>>) a string commanding width to be 0:
>>> s = s[:-2] + "/BS<</W 0>>>>"
>>> s # this is how the object source looks like now:
'<</Dest[4 0 R/XYZ 0 0 0]/Rect[55.8333 369.42 271.667 351.92]/Subtype/Link/BS<</W 0>>>>'
>>> doc._updateObject(68, s) # update it in the PDF
>>> doc.saveIncr() # save incrementally (or to new file at your choice)
>>> 
```

**Comment by TheDocSmith** [comment]
Awesome thanks and such a quick response! 

Quick and dirty works for me. I'll watch for a less 'dirty' solution later. The following updates all my links in the doc:
```python
for thisPage in range(0,len(doc)):
    allLinks = doc[thisPage ].getLinks()    # allLinks is all links on thisPage
    for thisLink in allLinks:
        xrefValue = thisLink["xref"]
        s = doc._getXrefString(xrefValue)
        s = s[:-2] + "/BS<</W 0>>>>"
        doc._updateObject(xrefValue, s)
```

**Comment by JorjMcKie** [comment]
A pleasure :-)

I am not sure how I might end up with a cleaner solution: either the above /BS-string becomes a permanent part of all links inserted by PyMuPDF (hm ...), making this dirty code obsolete or even erroneous, or I may introduce some maintenance methods for link annotations - similar to the ones I have for the other annots (which would let the dirty code stay valid).

Another remark: if the PDF contains links not inserted by PyMuPDF, this approach might make some links invalid: alien links may already contain a `/BS` or the alternative spec `/Border` ... PDF syntax allows for unpleasent ambiguities.

BTW you can treat documents as an iterator over its pages like so:

```python
for page in doc:
    allLinks = page.getLinks()
    # etc.
```

**Comment by TheDocSmith** [comment]
Thanks again. Checking existing links in my docs, both internal and external to the file, all continue to work correctly so I'm fairly safe I think. Until something changes...

And thanks for the heads up about iterating. A lot simpler. I'm very impressed with speed of operation by the way. 7 secs or thereabouts to crop 300 pages, insert 12 images and links on every page and refactor links to remove border. And 0.2 secs to just do the cropping.

**Comment by manish59** [comment]
How do i see the text which contain hyperlinks

**Comment by JorjMcKie** [comment]
The link rectangle (contained in key "from" of the link dictionary) is the "hot" area of the link. You can use one of the text extraction methods to see what text appears inside it - if there is any: may be just empty, and image, etc.

There are several options, depending on how precise you need to know stuff:

* script [textboxextract.py](https://github.com/JorjMcKie/PyMuPDF-Utilities/blob/master/textboxtract.py) shows 2 ways. One is more restrictive and only accepts text "words" fully contained in a given rectangle. The other alternative in the script includes all words which have a non-zero intersection with this hot area. In any case, the thus selected words are collected and put together to form the respective text line(s).

* You can also go down to each single character. Use page.getText("rawdict") in that case. This will enumerate all **characters** with each of its tiny rectangles they cover on the page. Then more or less do the same thing as before.

**Comment by JorjMcKie** [comment]
You can also determine the image contained in (or intersecting with) the hot area. Use getText("dict") or getText("rawdict") and inspect the image blocks with the list getText("dict)["blocks"]. Image blocks have type==1 and also come with their rectangle (bbox) on the page ...

Of course, this method will bombard you with the binary image data, too.
If you don't need that - there ist yet another way, to just get image meta info: `page.getTextBlocks(True)`. Here, only the image blocks and some image meta data are extracted - no binary contents.

So I hope you find what you are looking for ...

**Comment by JorjMcKie** [comment]
@TheDocSmith 
As I am developing a version 1.14.0, I found a way to extend handling of links (for PDF docs only that is).
Much like annotations, links will have:

1. a **property** `xref` (PDF cross ref number)
2. a **property** `border` - a *dict* containing width, dashes and border sryle of the link rectangle (hot area)
3. a **property** `colors` - a *dict* with colors of the hot area border
4. a **method** `setBorder` to manipulate border properties
5. a **method** `setColors` to manipulate the border color

So your "quick-and-dirty" code will be safe - you will then just have a more elegant method at hand. You can do things like:

```python
for page in doc:
    link = page.firstLink
    while link:
        link.setBorder({"width":0})
        link = link.next
```

to make a link's hot area invisible. This will also copy with PDF syntax ambiguities (which allow setting border properties in 3 different ways!).

Or - in contrast - you can surround hot areas with a red dotted line of width 1.0 if you like:

```python
for page in doc:
    link = page.firstLink
    while link:
        link.setBorder({"width":1, "dashes":(2,2)})
        link.setColors({"stroke":(1,0,0)})
        link = link.next
```

so that it will look like this:

![grafik](https://user-images.githubusercontent.com/8290722/47997322-cf916880-e0d1-11e8-9f28-9e00c92b6b00.png)

Unfortunately, links have by definition no interior color, therefore background coloring is not achievable by manipulating the link object itself.
It is of course possible to highlight the link rectangle by putting an appropriate annotation above it. Just use `page.addHighlightAnnot(link.rect)` or `page.addRectAnnot(link.rect)` or similar to achieve a look like this: 
![grafik](https://user-images.githubusercontent.com/8290722/47997646-f1d7b600-e0d2-11e8-823c-a088756f11ff.png)

... something already possible with v1.13.20.

**Comment by manish59** [comment]
[text.pdf](https://github.com/rk700/PyMuPDF/files/2550781/text.pdf)
Hey Im trying to print all the text words which are hyperlinks 
for example 
This November is the Wikipedia Asian Month ---> https://meta.wikimedia.org/wiki/Wikipedia_Asian_Month_2018
Wikipedia ----> https://en.wikipedia.org/wiki/Wikipedia


we can get uri from page.getLinks() uri section but if I try to get what are the words it is connected to the hyperlink i tried the solution you gave me https://github.com/JorjMcKie/PyMuPDF-Utilities/blob/master/textboxtract.py#L49
but still its not working can you give me any suggestions on how to improve this solution. Atleast we should develop a program where we can print the word and its hyperlinks

**Comment by TheDocSmith** [comment]
Lovely thanks. I'll migrate when the new version comes out to make my code more readable and reliable. Better to format a link as I place it rather than format all links and hope I'm not breaking something! 

Cheers,

Rob

**Comment by JorjMcKie** [comment]
@manish59 
I create this script as a first cut. It's not perfect (as I will indicate), but it already does something meaningful:

```python
import fitz
doc=fitz.open("text.pdf")
page = doc[0]                          # just look at page 0 for this time
wl = page.getTextWords()               # list of all words in the page
links = page.getLinks()                # list of all links on the page
for l in links:                        # iterate through the links
    l_text = []                        # will receive all word texts
    for w in wl:                       # iterate through the words
        wr = fitz.Rect(w[:4])          # this is the word's rect location

        if wr.intersects(l["from"]):   # if it touches the hot area ...
            l_text.append(w[4])        # append the word's text, but consider:
            # we may need to do something for re-establishing correct word
            # sequence using the word rect coordinates (e.g. sort by x coord.).

    link_text = " ".join(l_text)       # concatenate the words
    if link_text:                      # checks if this link has text at all
        print("'%s'" % link_text, "[%s]" % l["uri"])
```
The above script delivered the following list:

```
'This November is the Wikipedia Asian Month. Come join us.' [https://meta.wikimedia.org/wiki/Wikipedia_Asian_Month_2018]
'Jump to navigationJump' [https://en.wikipedia.org/wiki/Main_Page#mw-head]
'navigationJump to search Welcome' [https://en.wikipedia.org/wiki/Main_Page#mw-head]
'Wikipedia, that anyone can edit.' [https://en.wikipedia.org/wiki/Wikipedia]
'Welcome free' [https://en.wikipedia.org/wiki/Free_content]
'Welcome to encyclopedia 5,746,355 articles' [https://en.wikipedia.org/wiki/Encyclopedia]
'Wikipedia, anyone can edit. in English' [https://en.wikipedia.org/wiki/Wikipedia:Introduction]
'encyclopedia 5,746,355' [https://en.wikipedia.org/wiki/Special:Statistics]
'anyone can English' [https://en.wikipedia.org/wiki/English_language]
'Arts Biography' [https://en.wikipedia.org/wiki/Portal:Arts]
'Biography Geography' [https://en.wikipedia.org/wiki/Portal:Biography]
'Geography History' [https://en.wikipedia.org/wiki/Portal:Geography]
'History Mathematics' [https://en.wikipedia.org/wiki/Portal:History]
'Mathematics Science' [https://en.wikipedia.org/wiki/Portal:Mathematics]
'Science Society' [https://en.wikipedia.org/wiki/Portal:Science]
'Society Technology' [https://en.wikipedia.org/wiki/Portal:Society]
'Technology All portals' [https://en.wikipedia.org/wiki/Portal:Technology]
'All portals' [https://en.wikipedia.org/wiki/Portal:Contents/Portals]
'the 39th' [https://en.wikipedia.org/wiki/File:Spiro_Agnew.jpg]
'Spiro Agnew in Baltimore to' [https://en.wikipedia.org/wiki/Spiro_Agnew]
'Vice President of the United States mother and a Greek immigrant father.' [https://en.wikipedia.org/wiki/Vice_President_of_the_United_States]
'ARepublican, political offices' [https://en.wikipedia.org/wiki/Republican_Party_(United_States)]
'Spiro Agnew Baltimore as Baltimore' [https://en.wikipedia.org/wiki/Baltimore]
'Baltimore to a US-born mother Baltimore County Executive. running mate at the 1968 Republican' [https://en.wikipedia.org/wiki/Baltimore_County_Executive]
'became a lawyer, then held Governor of Maryland, regarded as a progressive,' [https://en.wikipedia.org/wiki/List_of_Governors_of_Maryland]
'before his electi Richard Nix after his elect' [https://en.wikipedia.org/wiki/Richard_Nixon]
'County Executive. In 1966, he was unexpectedly 1968 Republican National Convention. conservatives who were wary of stances taken' [https://en.wikipedia.org/wiki/1968_Republican_National_Convention]
'appealing to conservatives kickbacks office. Despite' [https://en.wikipedia.org/wiki/Kickback_(bribery)]
'attacking the news no contest right. (Full' [https://en.wikipedia.org/wiki/Nolo_contendere]
'news media for b tax evasion article...)' [https://en.wikipedia.org/wiki/Tax_evasion]
'contest to tax evasion (Full article...) Recent' [https://en.wikipedia.org/wiki/Spiro_Agnew]
'Recent Eurasian t' [https://en.wikipedia.org/wiki/Eurasian_tree_sparrow]
'Eurasian t Bone Sharps, Cowboys, and Thun •' [https://en.wikipedia.org/wiki/Bone_Sharps,_Cowboys,_and_Thunder_Lizards]
'Cowboys, and Thun God of War: Gho •' [https://en.wikipedia.org/wiki/God_of_War:_Ghost_of_Sparta]
'More featu' [https://en.wikipedia.org/wiki/Wikipedia:Featured_articles]
```

**Comment by JorjMcKie** [comment]
@manish59 
Why does the `intersect` method deliver something, but any test for "containment" doesn't?

As an answer, I did the following to page 0:
* marked all hot areas of links with a thin-ligned **red** rectangle
* surrounded all the page's words with their respective bbox (location rectangle) with a thin **blue** line.

This PDF is attached.

As you can see,

* You have multiple hot areas containing no text at all.
* You have many, many words obviously belonging to a hot area, but which also leak to its outside.

[newtext.pdf](https://github.com/rk700/PyMuPDF/files/2551316/newtext.pdf)


Hope that helps.

**Comment by manish59** [comment]
can we annotate for a word in the pdf if we have fitz.rect

**Comment by JorjMcKie** [comment]
@manish59 
You mean, if we know the location (i.e. rectangle) of some text, can we make an annotation to mark it?

Answer is YES:
If `rect` is the `fitz.Rect` containing the text (e.g. the word), then do this:

```python
page.addHighlightAnnot(rect)
```

This will put a yellowish textmarker over the word. See the highlighted word "MuPDF" in a picture a few posts earlier.
Instead highlighting, you can also underline or strike through the text.

You can also make a link out the word by the way ...
