### ISSUE TITLE
Document.close()

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#22]
Hi @rk700,
it seems that this function works in simpler situations only ...
When testing my MuPDF_OLedit.py my python session abended altogether.
I then compiled fitz.i with MEMDEBUG. For the simple program

-----------------------------------------------------------------
import fitz
f="C:/Users/.../test.pdf"
doc = fitz.Document(f)
print doc.pageCount
print doc.ToC()
page = doc.loadPage(0)
print doc.close()

------------------------------------------------------------------

everything seems to work fine with the following output:

------------------------------------------------------------------
40 ==> the number of pages
[[...]...] ==> the table of contents
free outline
free doc
None
free page

------------------------------------------------------------------
When I use  MuPDF_OLedit.py to open the same file. The following happens:
For each page displayed (function pdf_show()) the following lines appear (per page displayed):
free rect
free colorspace
free page
free irect
free pixmap
free device

When I then invoce the doc.close() function, the following 2 lines appear and then the python interpreter is abended:
free outline
free doc

**Comment by JorjMcKie** [comment]
Update:
If I do this with the above simple program ...

-----------------------------------------------------------------------
doc = fitz.Document(f)
page = doc.loadPage(0)
irect = page.bound().round()            
pix = fitz.Pixmap(fitz.Colorspace(fitz.CS_RGB),
                      irect)            
pix.clearWith(255)                      
dev = fitz.Device(pix)                  
page.run(dev, fitz.Identity)            
pix.writePNG("test.png")
print doc.close()

---------------------------------------------------------------------

The following output appears:

free rect
free colorspace
free outline
free doc

Then python interpreter is being abended.
My guess: an additional "free page" is being tried **after** the Document is already destroyed?

**Comment by rk700** [comment]
@JorjMcKie right, and same issue also happened on my linux machine. I think the ref count problem is still not resolved yet, and I'll reopen the previous issue https://github.com/rk700/PyMuPDF/issues/16

**Comment by JorjMcKie** [comment]
Closed because original issue was re-opened
