### ISSUE TITLE
Docker: ModuleNotFoundError: No module named 'frontend'

### ISSUE THREAD

**Issue by abieler** [rk700/PyMuPDF#220]
EDIT: Solved! 

Sorry installed `fitz` instead of `PyMuPDF`. Please Ignore this issue.

Docker setup below
python 3.6.6

pip installed `fitz` in docker and it fails with the following error on import

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-cd3ff425d28b> in <module>
----> 1 from docparser import SpatialDocument

/usr/local/lib/python3.6/dist-packages/docparser/__init__.py in <module>
      9 import logging
     10 
---> 11 from .documents import SpatialDocument
     12 # from .documentpages import DocumentPage, ImageDocumentPage
     13 # from .categorization import TextCategorizer

/usr/local/lib/python3.6/dist-packages/docparser/documents.py in <module>
      6 from matplotlib import cm
      7 import cv2
----> 8 import fitz
      9 
     10 from .text_detectors import SmearTextDetector, MuPdfTextDetector

/usr/local/lib/python3.6/dist-packages/fitz/__init__.py in <module>
----> 1 from frontend import *
      2 import tools
      3 import os.path as op
      4 
      5 __version__ = '0.0.1dev2'

ModuleNotFoundError: No module named 'frontend'
```

And here the Dockerfile

```
FROM ubuntu:bionic

ENV LANG C.UTF-8  
ENV LC_ALL C.UTF-8 
ENV PYTHONIOENCODING utf-8   
ENV PYTHON_VERSION=3.6.6
ENV PYTHON_MAJOR=3.6

RUN \
    apt-get update -y \
    && apt-get install -y \
    build-essential \
    curl \
    git \
    ghostscript \
    imagemagick \
    libfile-mimeinfo-perl \
    libglib2.0.0 \
    libcurl4-openssl-dev \
    libcairo2-dev \
    libssl-dev \
    mime-support \
    openssh-client \
    poppler-utils \
    python3 \
    python3-dev \
    python3-pip \
    && apt-get install -y software-properties-common \
    && apt-get update \
    && apt-get install -y \
    libtesseract-dev \
    libleptonica-dev \
    tesseract-ocr \
    tesseract-ocr-deu \
    tesseract-ocr-eng \
    && pip3 install pip --upgrade

COPY requirements.txt .
RUN pip3 install -r requirements.txt

CMD ["python3"]
```

The modiule `frontend.py` is present in the `fitz` directory.

Thanks for the help

**Comment by Devlujfeng** [comment]
Hi Abieler, I had the same error when import the frontend, fitz. How did you solve it?

**Comment by svcvit** [comment]
> Hi Abieler, I had the same error when import the frontend, fitz. How did you solve it?

I use this Dockerfile

```
FROM ubuntu:bionic

ENV LANG C.UTF-8  
ENV LC_ALL C.UTF-8 
ENV PYTHONIOENCODING utf-8   
ENV PYTHON_VERSION=3.6.6
ENV PYTHON_MAJOR=3.6

RUN \
    apt-get update -y \
    && apt-get install -y \
    curl \
    git \
    libzbar0 \
    mupdf \
    libzbar-dev \
    python3 \
    python3-dev \
    python3-pip \
    && pip3 install pip --upgrade 
    
COPY requirements.txt .
ADD . /code
WORKDIR /code

RUN pip3 install -r requirements.txt
```

**Comment by abieler** [comment]
@Devlujfeng I installed `fitz` instead of `PyMuPDF` by accident. So if you install `PyMuPDF` it should just work.

**Comment by naspuka** [comment]
the solution to the problem  "No module named 'frontend' " is for you to install PyMuPDF first thats the frontend framework for fitz to work.

**Comment by vaidhin** [comment]
I had this same problem while using fitz and pymupdf in google colaboratory.... problem solved by installing (or calling)  fitz first and then installing pymupdf next.

**Comment by bharath-kumarn** [comment]
i solved this problem by upgrade python pip:

pip install --upgrade pip
pip install -U PyMuPDF

**Comment by JorjMcKie** [comment]
Both, PyMuPDF and the package [fitz](https://pypi.org/project/fitz/) have the same top-level text, namely "fitz".
Therefore, they **_cannot coexist_** in the same Python environment.

**Comment by Shohreh** [comment]
I'm no Python expert.

I followed the [tutorial](https://pymupdf.readthedocs.io/en/latest/tutorial.html), and ended up making the mistake of installing both PyMuPDF and fitz.

After removing fitz, "print(fitz.__doc__)" says "None".

What could I try to get going?

Thank you.

```
"""
pip install PyMuPDF-1.18.10-cp38-cp38-win32.whl
pip install fitz
pip uninstall fitz
"""

print(fitz.__doc__)
#None
```

**Comment by JorjMcKie** [comment]
To clean up the spoiled situation, do 
```shell
py -38-32 -m pip uninstall pymupdf
py -38-32 -m pip uninstall fitz
py -38-32 -m pip install pymupdf
```

That package fitz cannot coexist with PyMuPDF - in the same (virtual) environment.

**Comment by Shohreh** [comment]
Thank you.

**Comment by HissaanAli** [comment]
> I had this same problem while using fitz and pymupdf in google colaboratory.... problem solved by installing (or calling) fitz first and then installing pymupdf next.

For me the solution was uninstalling both, followed by installing fitz first and then PyMuPDF .

**Comment by rohit-humne** [comment]
Hi everyone, i am also facing the same problem. 
i tried 
- pip install --upgrade pip
- pip install -U PyMuPDF


- pip uninstall pymupdf
- pip uninstall fitz
- pip install pymupdf

Still it is showing module not found error, Trying to install fits first and then pymupdf
- pip install fitz
- pip install pymupdf

still the same error:-
Traceback (most recent call last):
  File "/Users/humnerohit/python_pdf_to_text/main10.py", line 1, in <module>
    import fitz
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/fitz/__init__.py", line 1, in <module>
    from frontend import *
ModuleNotFoundError: No module named 'frontend'

**Comment by JorjMcKie** [comment]
The message appears if some other package called `fitz` is installed in the same Python.
Don't do that.
If you still need this package (unmaintained, archived on GitHub and in alpha version since ever), then  use anything of PyMuPDF **_exclusively_** vie the `pymupdf` module name.

**Comment by rohit-humne** [comment]
@JorjMcKie 
Thank you so much!

I have another issue in converting pdf to text using python. while searching i found that you have a great knowledge about these things. i wanted to connect with with you with this issue. if possible please let me know how can i get a guidance on it from you?

**Comment by JorjMcKie** [comment]
> @JorjMcKie Thank you so much!
> 
> I have another issue in converting pdf to text using python. while searching i found that you have a great knowledge about these things. i wanted to connect with with you with this issue. if possible please let me know how can i get a guidance on it from you?

Certainly - this is what our [Discussions](https://github.com/pymupdf/PyMuPDF/discussions) tab is for!

**Comment by rohit-humne** [comment]
JoriMcKie,

Thank you for sharing the discussion tab with me, i have made a discussion
please go through it.

Thank you
