### ISSUE TITLE
Provide an way to iterate over each object (instead of blocks/words)

### ISSUE THREAD

**Issue by turicas** [rk700/PyMuPDF#225]
I'm implementing different PDF backends on [rows table extraction library](https://github.com/turicas/rows/tree/feature/plugin-pdf) and working now on PyMuPDF backend - the only available backend right now is [pdfminer.six](https://pypi.org/project/pdfminer.six/), but it's too slow (BTW, thanks for the great work on PyMuPDF!).

The heuristics I've created depend on object's positions: two of them extract only text objects from the document, but one extract both text and rect objects. I could not find a way to extract rect objects using PyMuPDF and the available `getTextWords()` and `getTextBlocks()` methods do not seem to return the objects as in pdfminer.six. With `mutool show` I can see the separate objects, but cannot access them separately using the library.

Using PyMuPDF I've got 30 blocks or 311 words (see attached text file to look the objects' contents):

```python
import fitz
doc = fitz.open('balneabilidade-2018-02-16.pdf')
page = doc.loadPage(0)
print(len(page.getTextBlocks()))  # 30
print(len(page.getTextWords()))  # 311
for block in page.getTextBlocks(): 
   print(repr(block[4]))
```

Using pdfminer.six I've got 33 objects (see attached text file to look the objects' contents):

```python
import logging

from pdfminer.converter import PDFPageAggregator
from pdfminer.layout import LAParams, LTTextBox, LTTextLine, LTChar
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfparser import PDFParser

logging.getLogger("pdfminer").setLevel(logging.ERROR)
TEXT_TYPES = (LTTextBox, LTTextLine, LTChar)

filename = 'balneabilidade-2018-02-16.pdf'
fobj = open(filename, mode='rb')
parser = PDFParser(fobj)
doc = PDFDocument(parser)
parser.set_document(doc)
rsrcmgr = PDFResourceManager()
laparams = LAParams()
device = PDFPageAggregator(rsrcmgr, laparams=laparams)
interpreter = PDFPageInterpreter(rsrcmgr, device)
page = next(PDFPage.create_pages(doc))
interpreter.process_page(page)
for obj in device.get_result():
    if isinstance(obj, TEXT_TYPES):
        print(repr(obj.get_text()))
```

Is there any way I can:

- Return text objects as pdfminer.six returns (or as `mutool show` returns)?
- Look for rect objects?

**Comment by JorjMcKie** [comment]
could you please send me the text file? It is not attached here.

The 2 methods you used, getTextWords() and getTextBlocks(), are performance-oriented ways to analyze page text. There are other methods which provide far more detail:
* getText("dict") provides font detail for every text piece and position information on single **line level**.
* getText("rawdict") goes a level down to **single characters**

Both also provide information about text orientation and writing mode for text that is neither horizontal nor vertical and writing modes (like up-down, left-right, right-left, etc.)

**Comment by JorjMcKie** [comment]
ah forgot to mention: both methods create Python dictionaries. The _dict_ structures are explained [here](https://pymupdf.readthedocs.io/en/latest/textpage/).

**Comment by JorjMcKie** [comment]
can you tell me how you invoke `mutool show` to get the desired output?

**Comment by turicas** [comment]
Sorry, I forgot to attach the files.
[pymupdf-objects.txt](https://github.com/rk700/PyMuPDF/files/2595583/pymupdf-objects.txt)
[pdfminer.six-objects.txt](https://github.com/rk700/PyMuPDF/files/2595584/pdfminer.six-objects.txt)

I invoke the command like this:
```bash
mutool show balneabilidade-2018-02-16.pdf pages/1/Contents
 ```

I think I can solve my problem by parsing the `getText('dict')` result (will try to feed this code into the algorithm to see if the table extraction works):
```python
import fitz
filename = 'balneabilidade-2018-02-16.pdf'
doc = fitz.open(filename)
page = doc.loadPage(0)
print(len(page.getTextBlocks()))  # 30
print(len(page.getTextWords()))  # 311

text_blocks = []
for block in page.getText('dict')['blocks']:
    if block['type'] != 0:
        continue

    for line in block['lines']:
        line_text = ' '.join(span['text'] for span in line['spans'])
        text_blocks.append([*line['bbox'], line_text])
print(len(text_blocks))  # 44
for block in text_blocks:
    print(repr(block[4]))
```

The result is: 
[pymupdf-objects-blocks.txt](https://github.com/rk700/PyMuPDF/files/2595771/pymupdf-objects-blocks.txt)

**Comment by JorjMcKie** [comment]
if you are looking for something like the ``grep`` option of `mutool show`, then PyMuPDF supports this:

```python
>>> doc = fitz.open("some.pdf")
>>> xreflen = doc._getXrefLength() # number of PDF objects
>>> for xref in range(1, xreflen):      # print them item 0 is prohibited
	print("%i 0 obj" % xref, doc._getXrefString(xref)) # print PDF object source

	
1 0 obj <</Type/Pages/Kids[3 0 R]/Count 1/MediaBox[0 0 595.28 841.89]>>
2 0 obj <</ProcSet[/PDF/Text/ImageB/ImageC/ImageI]/Font<</F2 7 0 R/F3 14 0 R/F4 21 0 R>>/ExtGState<</GS1 5 0 R/GS2 6 0 R>>/XObject<</I1 28 0 R/I2 29 0 R/I3 30 0 R/I4 31 0 R>>>>
3 0 obj <</Type/Page/Parent 1 0 R/MediaBox[0 0 595.28 841.89]/TrimBox[0 0 595.28 841.89]/Resources 2 0 R/Group<</Type/Group/S/Transparency/CS/DeviceRGB>>/Contents 4 0 R>>
4 0 obj <</Filter/FlateDecode/Length 2762>>
5 0 obj <</Type/ExtGState/BM/Normal/ca 1/CA 1>>
6 0 obj <</Type/ExtGState/BM/Normal/ca .4/CA .4>>
...
```

You can find out a page's xref directly: `page.xref`
You can also find out the xref numbers of a page's /Contents objects: `page._getContents()` which is a list of integers.
Then you print the command "source" contained in such content objects via `doc._getXrefStream()`:

```python
>>> doc[0].xref # the object 3 source is shown above
3
>>> doc[0]._getContents() # this page has only 1 /Contents object
[4]
>>> doc._getXrefStream(4)
b' q 1.000 1.000 1.000 rg\n0.000 0.000 595.280 841.890 re f Q\n q 0 w 22.677 827.717 m 22.677 782.000 l 572.603 782.000 l 572.603 827.717 l 22.677 827.717 l  W n \nq 0.192 0.494 0.749 rg\n22.677 827.717 549.926 -45.717 re f Q\nQ 2 J\n0.567 w\nBT /...'
```
