### ISSUE TITLE
How to crop a page with given bbox ?

### ISSUE THREAD

**Issue by satyaaditya** [rk700/PyMuPDF#231]
I have a pdf page and i need to exclude some part of text present in top and bottom parts of page and get remaining text with getText() functionality, how to do that ?

i need to basically crop the page by excluding some of the top and bottom content and extract text from remaining page.

**Comment by JorjMcKie** [comment]
You can set a page's /CropBox via `page.setCropBox(rect)`. This will ensure that PDF viewer only display the `rect` part.

If you reload the page, the new page rectangle will equal that new cropbox.

However, text extraction always extracts **all** text on the page. You have to select the interesting parts of the text yourself.
You have several variants of text extraction to do this:

* Use `page.getTextBlocks()`. Retrieves text blocks, each with its rectangle. Check if this rect is inside the wanted bbox. The text part of each block consists of single lines which are separated by line breaks.
* If blocks are not granular enough, you can use `page.getText("dict")`. This also delivers text blocks, but with rectangles for each single line.
* finally there is `page.getTextWords()`, which is similar to the frist one, but delivers each word with its rectanlge.
