### ISSUE TITLE
Get page as image for a pdf

### ISSUE THREAD

**Issue by satyaaditya** [rk700/PyMuPDF#235]
i tried with following code
`
 page = self.pdf.loadPage(page_no)`
` pix = page.getPixmap(matrix=fitz.Identity, colorspace='RGB')`
` pix = fitz.Pixmap(self.pdf, pix)`
` pix.writePNG('satya.png')
`

i am getting this error 

` line 29, in get_page_as_image
    pix = fitz.Pixmap(self.pdf, pix)
  File "/home/satyaadityabaratam/venv/local/lib/python2.7/site-packages/fitz/fitz.py", line 2659, in __init__
    this = _fitz.new_Pixmap(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_Pixmap'.
  Possible C/C++ prototypes are:
    fz_pixmap_s::fz_pixmap_s(struct fz_colorspace_s *,struct fz_irect_s const *,int)
    fz_pixmap_s::fz_pixmap_s(struct fz_colorspace_s *,struct fz_pixmap_s *)
    fz_pixmap_s::fz_pixmap_s(struct fz_pixmap_s *,float,float,struct fz_irect_s *)
    fz_pixmap_s::fz_pixmap_s(struct fz_pixmap_s *,int)
    fz_pixmap_s::fz_pixmap_s(struct fz_colorspace_s *,int,int,PyObject *,int)
    fz_pixmap_s::fz_pixmap_s(char *)
    fz_pixmap_s::fz_pixmap_s(PyObject *)
    fz_pixmap_s::fz_pixmap_s(struct fz_document_s *,int)

Exception TypeError: "in method 'delete_Pixmap', argument 1 of type 'struct fz_pixmap_s *'" in <object repr() failed> ignored`

what is wrong in the above code?

**Comment by JorjMcKie** [comment]
Well, as the message says: there is no constructor signature like ``fitz.Pixmap(doc, pix)``.

* Your line number 2 already creates the page pixmap (and **successfully** so).
* On line 3 you then **re-assign** that pixmap, using it also as an argument. What are you trying to achieve?

There are the following possibilities to create a pixmap **from another pixmap** (see [here](https://pymupdf.readthedocs.io/en/latest/pixmap/)):

* `` __init__(self, colorspace, pix)`` - Copy and set colorspace
* `` __init__(self, pix, width, height[, clip])`` - Copy and scale
* `` __init__(self, pix, alpha = 1)`` - Copy and add or drop alpha

There is one overloaded constructor, where the PDF document appears as an argument:

* `` __init__(self, doc, xref)`` - From a PDF image (xref is one of the PDF's xref numbers of an image).

**Comment by JorjMcKie** [comment]
Be reminded, that if you create a **page pixmap**, to also consider thoroughly to request alpha=0/False. The default creates a pixmap with transparency channel, so your image is larger (33% in the RGB case) and may look ugly.

BTW: I am seriously considering changing the default here (exists for old code compatibility only).

**Comment by satyaaditya** [comment]
thanks a lot for the quick reply, I just want to create an image of the page and I saw example code for finding images in a page and combined both (foolish). I removed the third line, and everything is fine now.
BTW I am parallelly using another library for similar use cases and believe PyMUPDF is executing with Godspeed

**Comment by JorjMcKie** [comment]
thanks for the feedback :-)

That's why I am proudly stating that PyMuPDF is the fastest. This goes back to underlying C-library MuPDF of course. You may find it useful to look at the performance comparison chapter in the docs.

Which other libraries have you tried?

**Comment by satyaaditya** [comment]
pdfplumber,
BTW do you support cropping page by bbox and getting image of the cropped page. This is main reason i also use that library

**Comment by JorjMcKie** [comment]
Sure! You really should read the documentation ... :-)
Just do this: ``page.getPixmap(..., clip=bbox)``, where ``bbox`` is the rectangle you want. If you actively use the matrix parameter, you will also find that the method is very powerful: you can get rotated, mirrored, flipped, sheared, ... page images.

Together with a little example script, you can also exclude annotations from the pixmap. You can also create pixmaps of annotations separately from the page - with the full range of parameters, etc.

Pixmap handling in general is quite sophisticated, too. You can copy parts of one pixmap into another, you can shrink a pixmap down to thumbnails, you can directly read from files or memory areas, drop or add alpha channels, convert colorspaces, ... and what not.

**Comment by satyaaditya** [comment]
going through this https://github.com/rk700/PyMuPDF/issues/54

**Comment by JorjMcKie** [comment]
There is a [document browser](https://github.com/JorjMcKie/PyMuPDF-Utilities/blob/master/doc-browser.py) which can display all supported document types using Tkinter and also supporting zooming into pages by using the clip parameter.

**Comment by JorjMcKie** [comment]
Also, since some time now, the documentation contains a chapter with [usage recipes](https://pymupdf.readthedocs.io/en/latest/faq/#images). The chapter is organized around typical situations, and your cases are explicitely mentioned there, together with appropriate code snippets.
