### ISSUE TITLE
Annotation coordinate consistency

### ISSUE THREAD

**Issue by bjhowie** [rk700/PyMuPDF#239]
Annotation coordinates returned by the annot.Rect method appear to be in a different coordinate system to coords returned by the annot.vertices method. Specifically they appear to be rotated at 90 degrees to each other, possibly dependent on page rotation.
This seems to have occurred in one of the 1.14 releases

**Comment by JorjMcKie** [comment]
can you please provide an example?

**Comment by bjhowie** [comment]
Running the below code on the attached PDF yields a different result using 1.13.18 versus using 1.14.3:

Looks like only the y coordinate of annot.vertices is affected in this example, though on other PDFs i've tried there also seems to be a rotation/reflection of the annot.vertices coordinates.


```
import fitz

import numpy as np

import matplotlib.pyplot as plt
import matplotlib
from matplotlib.patches import Polygon
from matplotlib.collections import PatchCollection

doc = fitz.open("test_pdf.pdf")

page = doc[0] 
annot = page.firstAnnot             

pts=[]
while annot is not None:
    if annot.type[0]==fitz.ANNOT_SQUARE:
        pts.append((annot.rect.x0,annot.rect.y0))
    elif annot.type[0]==fitz.ANNOT_POLYGON:
        poly_pts=annot.vertices

    annot=annot.next

doc.close()

fig, ax = plt.subplots()
patches = []

polygon = Polygon(poly_pts, True)
patches.append(polygon)

p = PatchCollection(patches, cmap=matplotlib.cm.jet, alpha=0.4)

colors = 100*np.random.rand(len(patches))
p.set_array(np.array(colors))

ax.add_collection(p)

ax.plot(matplotlib.pyplot.scatter([x[0] for x in pts],[x[1] for x in pts]))

ax.autoscale()
plt.show()
```

[test_pdf.pdf](https://github.com/rk700/PyMuPDF/files/2682365/test_pdf.pdf)

Using 1.13.18:
![pymupdf 1-13-18 test](https://user-images.githubusercontent.com/45848617/50038382-10868080-0073-11e9-8ad2-565579f4284d.PNG)

Using 1.14.3:
![pymupdf 1-14-3 test](https://user-images.githubusercontent.com/45848617/50038386-19775200-0073-11e9-980c-a8d69b676eb8.PNG)

**Comment by JorjMcKie** [comment]
received - thank you.
Interesting problem!
Let's see ...

**Comment by JorjMcKie** [comment]
Found the bug and created a fix.
Was a tricky one, going back to MuPDF's massive changes in dealing with geometry objects in v1.14.0.
So the error exists since that version.

How urgent is the solution for you?

**Comment by bjhowie** [comment]
Thank you .
I've rolled back to 1.13 now so not super urgent. Just wanted to make sure it was on the radar for a future fix.
