### ISSUE TITLE
Cannot find startxref

### ISSUE THREAD

**Issue by bschollnick** [rk700/PyMuPDF#241]
Folks,

We have found some PDFs that are reporting "Cannot find startxref".  These were created a while back, and I can't repair them.  If I try to with PyMuPDF, it reports "pdf object stream missing (19 0 R)".  

Is there any good way to investigate repairing these files?

**Comment by JorjMcKie** [comment]
Are these files confidential or can you share an example?
(Py-) MuPDF are quite good at recovering from such errors.
Also I have implemented low-level functions for investigating the PDF structure. So I would certainly like to demonstrate the capabilities ... or, if all fails, die Segel streichen

**Comment by bschollnick** [comment]
I’ll take a look and see if we can hunt down an example that does not contain PHI..

	- Benjamin
