### ISSUE TITLE
newannots.py doesnt work on windows10

### ISSUE THREAD

**Issue by return71** [rk700/PyMuPDF#246]
Hello,
i installed python 3.7.2 and PyMuPDF 1.14.5 on Windows10. Then i loaded the newannots.py and run it.
Here are is the output from Idle:
```
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\Ralf\Documents\programmieren\python\pdf\src\annotationtest\newannots.py 
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32 

PyMuPDF 1.14.5: Python bindings for the MuPDF 1.14.0 library,
built on 2019-01-04 10:29:25 

added 'FreeText'
added 'Sticky Note'
Traceback (most recent call last):
  File "C:\Users\Ralf\Documents\programmieren\python\pdf\src\annotationtest\newannots.py", line 59, in <module>
    r1 = rl[1]
IndexError: list index out of range
>>> 

```

**Comment by return71** [comment]
Hello,
the error is that PyMuPDF or its unterlying MuPDF doesnt insert text as expectet.

```
text = "text in line\ntext in line\ntext in line"

page.insertText(pos, text, fontsize=11)
rl = page.searchFor("text in line")
r0 = rl[0]
r1 = rl[1]
r2 = rl[2]
annot = page.addHighlightAnnot(r0)
print_descr(r0, annot)
print("added 'HighLight'")
```
The line `page.insertText(pos, text, fontsize=11)` fails.

**Comment by JorjMcKie** [comment]
please download the new version of this demo script - forgot to update it in the repo.

**Comment by JorjMcKie** [comment]
the reason for this change:
demonstrate the new support of Quads (= rectangles that no longer have sides in parallel to x or y-axis) by text marking annotations.

**Comment by JorjMcKie** [comment]
Thanks for the submission. It appears you are new to using the package.
So, welcome and have fun with it.

**Comment by return71** [comment]
Hello,
yes im new here and had a lot of fun with the package. But i run into other issues. I will open a new
report for this.
Thanks for your help.
