### ISSUE TITLE
Can not read form PDF

### ISSUE THREAD

**Issue by shubhpy** [rk700/PyMuPDF#252]
Hey,

[https://s3.ap-south-1.amazonaws.com/public-sharing-purpose/aoc_gooded_tech.pdf](url)

I have been trying since a long time to read the data inside this PDF with any python library.
Somehow I landed here.

I tried opening this PDF but can not see the data.

History:
So when I open this PDF in Adobe Acrobat Reader, I see security warning of if you trust ... site and it asks to either allow or block. When I allow I can see the data.
But when I open it in Preview(Mac), It doesn't ask anything and shows data.

When I passed this PDF to any Python Library (PyMuPDF, PyPDF2, pdfminer, tabula), I didn't see the data but only fields.

One day, I opened it in Preview(Mac) and exported as PDF.
And Voila It was working and libraries were able to read full data.

Can anyone help me how can I see the full data in python?
Thanks

**Comment by JorjMcKie** [comment]
Hi,
I am trying to download the PDF. Seems not / no longer to be there ...

**Comment by shubhpy** [comment]
Please copy the URL and paste in a new tab.
Just clicking on it is taking it to some github page.

**Comment by JorjMcKie** [comment]
PyMuPDF has some ways to read out (and also fill in) PDF form fields.
Just as a demo, here is a little utility that scans through all fields of all pages of a given PDF and prints out what it understood about each field. The ZIP contains the script and its output for your PDF.

[pdf-forms.zip](https://github.com/rk700/PyMuPDF/files/2784804/pdf-forms.zip)

I am not sure if that was your question at all. Making a picture of a page with everything on there is also no problem ...

**Comment by shubhpy** [comment]
@JorjMcKie Thanks a lot man,
This way of getting fields and values is working for most of my PDFs, but still some PDFs (which are FormPDF coz doc.isFormPDF still gives True) fields I am not able to extract in this way.

https://s3.ap-south-1.amazonaws.com/public-sharing-purpose/Form+AOC-4-101115.pdf
https://s3.ap-south-1.amazonaws.com/public-sharing-purpose/Form+AOC4-CFS-121215.OCT.pdf

I am not sure but I think there is some concept of PDF signed or not signed which is used in govt documents, coz all the signed PDFs fields i am getting with your script but which are not signed, seems like there isn't any field.

**Comment by JorjMcKie** [comment]
Glad I could help.
* Form fields are just a special type of annotation. So you can at least check the existence as am annotation. Annots are a forward chain list of objects living on a PDF page.
* page.firstAnnot is the first annotation on a page.
* the next annot is reachable via annot.next``. This property is `None` if ``a`` is the last annot.
* ``print(a.type, a.info)`` gives some information ab an annot.
* Again, I cannot download the above PDFs. Even when copying the link to a separate borwser tab. Can you attach one here?
* I set ``doc.isFormPDF`` to ``True`` if (1) there exists a PDF object ``/AcroForm``, and (2) there exists at least one form field (PDF keeps a list of them centrally, in addition to the annot chain of each page).
* Currently, I am not supporting signature tye form fields.
* I am not sure about MuPDF (my external C library on which I am basing my binding on) support of signed PDFs. You meanwhile can check `doc.permissions` and see if that gives some clue.

**Comment by shubhpy** [comment]
Sorry my bad,
Didn't make those public.
You can try now, These wont open in browser you would have to download and open in Adobe PDF Reader or any same reader.

**Comment by JorjMcKie** [comment]
Anything else I can help with?
okay to close the issue?

**Comment by shubhpy** [comment]
Yes, Thanks a lot for your help.
