### ISSUE TITLE
compatible with 1.8?

### ISSUE THREAD

**Issue by ousia** [rk700/PyMuPDF#28]
@rk700,

sorry for asking that after the recent release of PyMuPDF, but what about compatibility with mupdf-1.8?

Many thanks for your excellent work.

**Comment by JorjMcKie** [comment]
@ousia,
I have already generated and successfully tested a 1.8 version under Windows. I will try and generate MuPDF 1.8 under Linux over the next days. When the Linux library modules exist, I will update PyMuPDF. But maybe @rk700 is faster ... :-) ?

**Comment by rk700** [comment]
The mupdf v1.8 was available for my distribution the other day, and I created a new branch named '1.8' for this one. However, it failed with segmentation fault when I run the newly built module, even though there were totally no errors during compilation.

**Comment by rk700** [comment]
Finally I figured out that I was using the 1.7a mupdf lib when linking and it was incompatible with the 1.8 header. I'll update and push the lib later and let's see if there would be any other issues of the new version.

**Comment by JorjMcKie** [comment]
Just delivered Windows versions of the library files. Also updated help to release 1.8.
I also tested the changes (Windows only).
I suggest to close this issue. Any errors occurring would lead to separate issues.
