### ISSUE TITLE
MuPDF 1.8 Performance

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#31]
@rk700, @deepgully, @ousia and friends:
I have been investigating somewhat on performance changes in MuPDF 1.8. You will be pleased to hear about improvements in the area of text extraction. There may be a other improvements  - they will pop in here when they are being observed.
* Text extraction speed of our bindings seem to have improved by a factor of more than 2. @rk700 - remember when I measured 7 seconds on my machine to extract simple text from a large PDF? This value is now less than 3 seconds for the exact same file
* The relative gap between the more complex methods ``extractJSON()``/``extractXML()`` and the simple ``extractText()`` shrunk significantly: instead of having processing time relationships (TEXT <> HTML <> JSON <> XML) ~ (1 <> 2 <> 145 <> 4120), we now have (1 <> 1 <> 3 <> 52)!!!

Please do inform me if you have any questions on this, or information to share ...

**Comment by rk700** [comment]
Awesome! The MuPDF guys really did a great job.

@JorjMcKie Thank you for the test!
