### ISSUE TITLE
Decrypt does not work on outlines

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#32]
In the process of establishing a more formal testing approach for PyMuPDF, I ran into the following problem:

I password protected a test pdf. Then I used the demo program ``removePass.py`` to create a non-protected version. This version was readable allright, but **all outline data were still encrypted!!**.
If I open the **encrypted** pdf with a standard viewer like Nitro, the outline looks fine.
Also no problem occurs with SumatraPDF.exe (which is based on MuPDF).

**Comment by JorjMcKie** [comment]
here is what ``removePass.py`` does with ``test_encrypted.pdf``:
[x.pdf](https://github.com/rk700/PyMuPDF/files/41855/x.pdf)

**Comment by JorjMcKie** [comment]
If I may guess: it is probably a timing issue.
I believe @rk700 you told me once that we instantiate the outline when the Document object is created. If we later decrypt a document, these outline data (and maybe metadata too) do not get updated.

**Comment by rk700** [comment]
Yes I think it's very likely to be true. Maybe we should update the outline when the doc is decrypted. 

I'll try later and see if that works.

**Comment by rk700** [comment]
I just updated ``fitz.i`` and ``removePass.py``. Now the outline of an encrypted document will not be initialized until it is decrypted. Hope that I didn't break other things.

**Comment by JorjMcKie** [comment]
I tested the new version:
It works ok for my test cases with non-encrypted files, but decryption seems to no longer work.
What happens is:
* ``doc.authenticate()`` returns 1
* ``doc.save()`` does create a copy which is not flagged as encrypted, but it in fact is still encrypted.

**Comment by rk700** [comment]
@JorjMcKie could you please provide an encrypted pdf and password as well?

**Comment by JorjMcKie** [comment]
Unencrypted:
[test.pdf](https://github.com/rk700/PyMuPDF/files/45345/test.pdf)
[test.pdf.txt](https://github.com/rk700/PyMuPDF/files/45344/test.pdf.txt)
[test.pdf](https://github.com/rk700/PyMuPDF/files/45348/test.pdf)

encryption password: "encrypt_pw"
encrypted pdf:
[encrypted.pdf](https://github.com/rk700/PyMuPDF/files/45349/encrypted.pdf)

**Comment by rk700** [comment]
I did make a mistake:(

Now the updates are:
* `doc.authenticate()` returns 1(True)  if authenticated successfully, that is, the password is correct. I made this update for consistency with the mupdf upstream and our document.
* I found that besides outline, metadata like author name, document title, are not decrypted either. So I move all those stuffs in a new function called `initData`, which will only be invoked either the doc is plain or when it is decrypted.

**Comment by JorjMcKie** [comment]
I executed my tests again with the new version - everything works fine again!
I will document the implied changes to the API.
I will also do a few minor things to prevent unexpected behaviors in case of encrypted and not yet authenticated files, like e.g. ``doc.metadata``, ``doc.outline`` attributes exist, but lead to exceptions when being used, etc.
