### ISSUE TITLE
Wrong JSON format in TextPage.extractJSON() method

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#33]
Testing text extraction with the following XPS 1-page example file produced an error:
input file and corresponding text file (with .JSON extension) can be found in test directory.
In essence, decimal values provides for one bbox are invalid, see lines 562 and following in the JSON file. I am extracting them here for clarity:
![json-error](https://cloud.githubusercontent.com/assets/8290722/11573025/534815ac-99d6-11e5-9bb1-c76202cd7dd1.PNG)

**Comment by rk700** [comment]
I guess those negative numbers are the y-axis coordinates of the bounding box and the negative direction is upward? The text "Seite 1 von 1" and "Acronis - Online Shop" are at the very top of the page, so is it possible that they do have negative y-coordinates?

**Comment by JorjMcKie** [comment]
Obviously this does occur ... however, it cannot make sense in the real world!
It definitely makes the the return string of the method extractJSON() an invalid JSON string, so it cannot be decoded by the standard json module.
My hot fix therefor replaces any negative bbox value by zero in this method.

**Comment by JorjMcKie** [comment]
Another comment:
As you noticed, it was an XPS example in German language, and "Seite 1 von 1" just means "page 1 of 1". The method looks at a page's /MediaBox, which is defined as "the boundaries of the physical medium on which the page is intended to be displayed or printed" ... "Content falling outside this boundary can safely be discarded without affecting the meaning of the PDF file". At least for a PDF, this is the default page's rectangle, if no others (bleed box, crop box, etc.) are provided. So, negative values seem to make no sense. It is again not our problem, and probably not even MuPDF's.

Anyway, maybe a cleaner way of resolving this:
Make sure that negative coordinates are always expressed like "-0.nnnnn", i.e. including a zero before the decimal point.

**Comment by JorjMcKie** [comment]
Sorry for recurring to this issue:
The problem is actually not that bbox coordinates may be negative - this may indeed be valid.

The issue is that ``extractJSON()`` generates an invalid JSON format when a coordinate value is greater -1 and less than 0: e.g. ``y0 = -0.123456``. In such cases the method's output contains ``-.123456`` which invalid in JSON.

JSON **requires** that floats must have at least one digit before the decimal point.

BTW the output of ``extractXML()`` also contains floats in this format. It is however not a JSON issue in this case.

I have been unable to figure out a format specification that would yield correct numbers (instead of using ``%f``).

**Comment by rk700** [comment]
This is because `fz_printf` is used for the float number formatting. By tracing function calls, I find that it finally calls `static void fmtfloat(struct fmtbuf *out, float f)` in file `fitz/printf.c`, and `fmtfloat` would not print the digit before decimal if it is zero.

The comment of function `fmtfloat` says "Convert float to shortest possible string that won't lose precision", and I believe that it would be hard to ask the mupdf developers for a new format function.
So I add some workarounds in our code: first print the float into a buffer and then `fz_printf` that buffer into the output.
