### ISSUE TITLE
Document.save(...) only for PDF?

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#34]
@rk700 - are you aware whether the save function of fitz might only work for PDF files?
I tested with an XPS file, tried to save it and got return code 0.
But no output file was created.

**Comment by rk700** [comment]
Seems to be right. I've searched mupdf-1.8 source code for write_document, and found that only PDF has a *_write_document implementation.

**Comment by JorjMcKie** [comment]
Well - ok, thank you.
What we have to do then is to update our documentation, making clear it's not a problem of our binding, but of MuPDF.
To make sure they know, I will open an issue at MuPDF. They will probably respond with something like "will not be fixed" :-)
