### ISSUE TITLE
Simplifications

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#36]
@rk700  - I have been thinking about further simplifying PyMuPDF's use.
Before changing anything, I would like to hear your thoughts ...
* An average user would probably never voluntarily use objects like TextSheet, TextPage or Device.
* But he has to if he wants to do simple things like accessing contents of pages - it is counter-intuitive.
* But of course we need to keep those things for users who need to do heavy optimization.
* I dislike blowing up ``fitz.i`` with Python specific code. One example is the code of ``Document.getToc()`` - it's an alien thing inside ``fitz.i``, and I would like to get rid of it there.
* Comparing the functions of PyMuPDF and other similar tools, there are still features missing in PyMuPDF - particularly in the area of output ...

So my idea in essence is to add functions / features outside ``fitz.i`` whenever possible by extending ``__init__.py`` (see provided example).

When you look at ``dir(fitz)`` after the import, lots of things pop up which no meaning or importance to the (normal) developper, or which are even dangerous to touch (e.g. cvar, or ``<class>_swigregister``).
I don't know yet how to get rid of such entries, but I would like to try ...

Please let me know what you think.

[``__init__ .py.txt``](https://github.com/rk700/PyMuPDF/files/73197/__init__.py.txt)

**Comment by rk700** [comment]
1. Agreed. We could provide both direct APIs and wrapped helper functions
2. I think SWIG has the feature of `include`. Maybe we can split `fitz.i` into multiple units and include them in a single file. I guess this might be better sine `__init__.py` would be overwritten each time we run SWIG.
3. Things like `<class>_swigregister` are generated automatically by SWIG, and I'm not sure neither if it's possible to remove them.
4. New features are always welcome. Actually PyMuPDF only provides a small part of all the exposed APIs in MuPDF. As for those not implemented in MuPDF, we might add them in PyMuPDF just like `printJSON`.

**Comment by JorjMcKie** [comment]
Meanwhile, I have been further experimenting with the ``__ini__.py``.
1. Function inside the init are available and work absolutely well.
2. If I include ``del <class>_swigregister`` statements immediately after the initial import statements, then those classes are gone. And everything so far still seems to work:

    from __future__ import absolute_import
    from fitz.fitz import *
    del Colorspace_swigregister
    del Device_swigregister
    del DisplayList_swigregister
    del Document_swigregister
    ...

I will continue testing the approach - it looks promissing!

I had been looking at wxPython's code: I knew they are also using SWIG, but you see hardly any traces of it when you do ``dir(wx)`` or ``dir(wx,_Core`` or similar statements. Their solution is very similar to the above.

**Comment by JorjMcKie** [comment]
I have submitted a bunch of new methods to PyMuPDF. Each of them can be invoked in 2 ways, e.g. getting a table of contents for a document:

    toc = fitz.GetToC(doc)          # standalone version
    # or
    toc = doc.getToC()               # class method

Similarly GetText / getText, GetLinks / getLinks, GetPixmap / getPixmap, SearchFor / searchFor.
All of them internally create any required DisplayList, Device, TextPage, TextSheet objects and reuse these later on as necessary.
This results in quite noticable reductions of coding (and thinking!) efforts - as I wrote before: many of these classes are very technical and probably rather obscur for a normal user of PyMuPDF.
Any of these changes only take place in the ``__init__.py`` - no changes to ``fitz.i``.
This init-file is being ignored by SWIG and copied around by ``setup.py`` as required.
As I have seen in products like wxPython, adapting the init-file is frequently used to give their products a richer and more elegant touch-and-feel.

Deleting the ``_swigregister`` classes is perfectly possible, too. I have, however, evaded the effort for an (almost) purely cosmetic change.
If someone touches things like ``fitz.cvar`` or messes around with some of the ``_swigregister`` classes, he will crash his Python interpreter. So we may still decide to do something here later.
