### ISSUE TITLE
PyMuPDF / fitz Performance

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#37]
@rk700 , @ousia , @deepgully :
Have you seen my performance investigations? It is contained in the documentation, and a WIKI page is pointing to the chapter.
I hope these data underpin what has always been said: It is very hard to beat MuPDF in terms of speed ...

**Comment by rk700** [comment]
@JorjMcKie Yes I've read it. It's super impressive, in both the result and the experiment itself. 
I've heard that Germans are very serious when at work :)

Anyhow thank you for the great work! I really appreciate it.

**Comment by JorjMcKie** [comment]
@rk700 that you for the flowers :-)
Maybe it's true that it is typically German ... but as a Mathematician I generally like things that can be proved.
Like a German (or Austrian) Science Cabaret group said it:
"The one who knows nothing, must believe everything!"
