### ISSUE TITLE
Invalid JSON text feeback of method extractJSON()

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#38]
@deepgully , @rk700 

On very rare occasions, the text string returned by this method is too long: it then returns data with arbitrary trailers.
This causes the JSON string to be invalid (exception generated by json.loads()).

I have found this issue with only one file so far: the Adobe Manual "Adobe PDF Reference 1-7.pdf".
It is peculiar, that I have seen this error only on **pages 660 and 1138 (zero-based)**.

Here is an output of the string returned for page 660:
[jsonerr.txt](https://github.com/rk700/PyMuPDF/files/73998/jsonerr.txt)
Another example is
[jsonerr2.txt](https://github.com/rk700/PyMuPDF/files/74001/jsonerr2.txt)

**Observations**
* It only occurs on the mentioned pages, but not always: sometimes on both, sometimes on only one
* An invalid text string apparently is always longer - never shorter than is legal
* The extra length varies: I have seen 5, 7, 10 or even over **100 extra bytes**
* If I run the program on only those pages (e.g. "JSON-izing" only page 660), the error occurs, too. Obviously we do not have a buffer overrun because of the many (1310) pages of that manual.
* As a circumvention, I look for the last occurrence of ``\n}`` and accordingly shorten the method's output string - this has worked so far. Maybe this is a bsis for a fix on the C level

**Comment by JorjMcKie** [comment]
**More information to help locate the error**

Program output for a bunch of consecutive runs: the extgra length varies each time
[errorlog.txt](https://github.com/rk700/PyMuPDF/files/74025/errorlog.txt)

This is the program running:
[testjsonerr.py.txt](https://github.com/rk700/PyMuPDF/files/74026/testjsonerr.py.txt)

The function ``GetText(pg, output = 'json')`` has the following content:
[GetText.txt](https://github.com/rk700/PyMuPDF/files/74032/GetText.txt)

**Comment by rk700** [comment]
I've dig into the problem and find that it's an upstream issue. I'll check whether it's fixed in the latest MuPDF and put the details later.

**Comment by rk700** [comment]
Seems to be caused by upstream and I filed a bug:
http://bugs.ghostscript.com/show_bug.cgi?id=696489

**Comment by JorjMcKie** [comment]
Great analysis!
Let's see what the reaction is.
Still it amazes me that it occurs in so rare circumstances.

**Comment by rk700** [comment]
MuPDF developer replied and pointed out that `fz_buffer_vprintf` is not supposed to write a trailing null byte. So I changed the typemap of `fz_buffer` accordingly and now the bug should be fixed.

Also the SWIG on my machine is updated to 3.0.8, which results in some slight changes in the .c file.

**Comment by JorjMcKie** [comment]
I have tested the new version, including employing SWIG version 3.08.
The error is gone and I am closing the issue.
