### ISSUE TITLE
Install failed on OSX 10.11.3

### ISSUE THREAD

**Issue by gbarnabic** [rk700/PyMuPDF#41]
Got a bunch of warnings and a final error.  Note I did have difficulty getting mupdf to compile but was finally able to do it by changing all the openssl includes with a hard path to where they were located on my system.  Also had to use the following on the make: make HAVE_X11=no

Here is the terminal output:
```
Georges-MBP:PyMuPDF gbarnabic$ python3 setup.py install
running install
running build
running build_py
creating build/lib.macosx-10.6-intel-3.4
creating build/lib.macosx-10.6-intel-3.4/fitz
copying fitz/__init__.py -> build/lib.macosx-10.6-intel-3.4/fitz
copying fitz/fitz.py -> build/lib.macosx-10.6-intel-3.4/fitz
copying fitz/utils.py -> build/lib.macosx-10.6-intel-3.4/fitz
running build_ext
building 'fitz._fitz' extension
creating build/temp.macosx-10.6-intel-3.4
creating build/temp.macosx-10.6-intel-3.4/fitz
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I./mupdf/include -I./mupdf/include/mupdf -I/Library/Frameworks/Python.framework/Versions/3.4/include/python3.4m -c ./fitz/fitz_wrap.c -o build/temp.macosx-10.6-intel-3.4/./fitz/fitz_wrap.o
./fitz/fitz_wrap.c:3316:45: warning: passing 'char *' to parameter of type
      'unsigned char *' converts between pointers to integer types with
      different sign [-Wpointer-sign]
                data = fz_open_memory(gctx, stream, streamlen);
                                            ^~~~~~
./mupdf/include/mupdf/fitz/stream.h:66:59: note: passing argument to parameter
      'data' here
fz_stream *fz_open_memory(fz_context *ctx, unsigned char *data, int len);
                                                          ^
./fitz/fitz_wrap.c:3555:62: warning: passing 'char *' to parameter of type
      'unsigned char *' converts between pointers to integer types with
      different sign [-Wpointer-sign]
                pm = fz_new_pixmap_with_data(gctx, cs, w, h, samples);
                                                             ^~~~~~~
./mupdf/include/mupdf/fitz/pixmap.h:83:109: note: passing argument to parameter
      'samples' here
  ...*ctx, fz_colorspace *colorspace, int w, int h, unsigned char *samples);
                                                                   ^
./fitz/fitz_wrap.c:3563:40: warning: passing 'char *' to parameter of type
      'unsigned char *' converts between pointers to integer types with
      different sign [-Wpointer-sign]
                pm = fz_load_png(gctx, data, size);
                                       ^~~~
./mupdf/include/mupdf/fitz/image.h:87:56: note: passing argument to parameter
      'data' here
fz_pixmap *fz_load_png(fz_context *ctx, unsigned char *data, int size);
                                                       ^
3 warnings generated.
./fitz/fitz_wrap.c:3316:45: warning: passing 'char *' to parameter of type
      'unsigned char *' converts between pointers to integer types with
      different sign [-Wpointer-sign]
                data = fz_open_memory(gctx, stream, streamlen);
                                            ^~~~~~
./mupdf/include/mupdf/fitz/stream.h:66:59: note: passing argument to parameter
      'data' here
fz_stream *fz_open_memory(fz_context *ctx, unsigned char *data, int len);
                                                          ^
./fitz/fitz_wrap.c:3555:62: warning: passing 'char *' to parameter of type
      'unsigned char *' converts between pointers to integer types with
      different sign [-Wpointer-sign]
                pm = fz_new_pixmap_with_data(gctx, cs, w, h, samples);
                                                             ^~~~~~~
./mupdf/include/mupdf/fitz/pixmap.h:83:109: note: passing argument to parameter
      'samples' here
  ...*ctx, fz_colorspace *colorspace, int w, int h, unsigned char *samples);
                                                                   ^
./fitz/fitz_wrap.c:3563:40: warning: passing 'char *' to parameter of type
      'unsigned char *' converts between pointers to integer types with
      different sign [-Wpointer-sign]
                pm = fz_load_png(gctx, data, size);
                                       ^~~~
./mupdf/include/mupdf/fitz/image.h:87:56: note: passing argument to parameter
      'data' here
fz_pixmap *fz_load_png(fz_context *ctx, unsigned char *data, int size);
                                                       ^
3 warnings generated.
/usr/bin/clang -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.4/./fitz/fitz_wrap.o -L./PyMuPDF-optional-material/LibWin32 -llibmupdf -llibthirdparty -o build/lib.macosx-10.6-intel-3.4/fitz/_fitz.so /NODEFAULTLIB:MSVCRT
clang: error: no such file or directory: '/NODEFAULTLIB:MSVCRT'
error: command '/usr/bin/clang' failed with exit status 1
Georges-MBP:PyMuPDF gbarnabic$ 
```

**Comment by JorjMcKie** [comment]
Unfortunately, none of the PyMuPDF contributors has a MAC, so it wasn't tested for this configuration.
With some embarassment, I have to admit that the ``setup.py`` file assumes one of "Linux" or "MS Windows". The latter was assumed in your case, as it is not Linux.
Sorry about that!
Looking at your generation output it seems you have 3 warnings and only 1 error. This error comes from the setup parameter ``extra_link_args=['/NODEFAULTLIB:MSVCRT'],``, which is Windows-specific.
So - your time permitting - there is hope that things will be fine if you delete it from your ``setup.py``.

**Comment by gbarnabic** [comment]
Ok, I understand.  I'll give that a try tomorrow when I'm at my Mac again.  Actually I'm on my PC now and had problems there as well.  I'm guessing that none of you have a Windows computer without Visual Studio installed either??  I'll start a separate Issue with what I have encountered on the PC.

**Comment by rk700** [comment]
Actually I have a Mac at work, and I'll take a look at it later.

**Comment by rk700** [comment]
@gbarnabic I've made it on OSX 10.11.3 as follows:

1. Install the dependencies:
`brew install mupdf-tools jpeg jbig2dec freetype openssl`
2. Since the `libmupdf.a` library file is just for arch x86_64, we need to set the ARCHFLAG before building PyMuPDF:
`export ARCHFLAGS='-arch x86_64'`
3. Set the `include_dirs` and `library_dirs` in `setup.py`(I'll update the `setup.py` file later, and if you use `brew install` too then these paths should be almost the same as mine)
4. Build and install
`sudo python setup.py install`
5. Since the library `libmujs.a` is not included in `mupdf-tools`, symbols like `_js_copy` would be missing. However those utils are not exposed in our python binding, and we can ask `dlopen` to load the module in lazy mode:
```
import sys 
sys.setdlopenflags(0)
import fitz
```

I tried `demo/extract.py` as a quick test and it worked. (Remember to use `setdlopenflags` as above). Maybe we should put the `setdlopenflags` in `fitz.py` file.

**Comment by gbarnabic** [comment]
Success!  Thank you. Got the demo/extract.py to work...

Note: I had a bit of difficulty on Step 1 as freetype had a dependency of libpng.  This needed to write to both /usr/local/share/man/man3 and man5 which had permissions to write only for system.  I guess I should have just used sudo brew but I set the permissions to write for everyone, did the brew, then set them back.  I'm just mentioning it since you may want to put sudo in the instructions for others.  

One other note.  When I first was trying to get this to install I kept getting errors on the openssl includes in the file pdf-pkcs7.c .  I did some searching on the topic and there were all kinds of posts about Apple not using it.  When I did do the brew install openssl I got the message that it was already installed. "Warning: openssl-1.0.2e_1 already installed".  Anyway I hunted down where the .h files were had to change all the include statements in pdf-pkcs7.c:
#include "openssl/err.h" to #include "/usr/local/opt/openssl/include/openssl/err.h".  Then I had to change all the #includes in /usr/local/opt/openssl/include/openssl/ to a hard path reference to themselves.  Maybe after following the instructions that were given to me by k700 I wouldn't have had to do this but again I wanted to mention it for the possible benefit of others.

**Comment by gbarnabic** [comment]
I just found this link which explains why the brew failed as explained above with messages like:
/usr/local/share/man/man3 is not writable. 

Apparently by design Homebrew (brew) requires the contents of /usr/local to be owned by you. You can fix this by running:

$ cd /usr/local
$ sudo chown -R <your-username>:<your-group-name> *

(get your group name by $ id -g)

Here is the source of my information:
http://apple.stackexchange.com/questions/192227/make-files-in-usr-local-writable-for-homebrew
