### ISSUE TITLE
Demo - sierpinki.py error

### ISSUE THREAD

**Issue by gbarnabic** [rk700/PyMuPDF#43]
Now that I have it installed, I'm experimenting.  So I found this demo is not working.  Here is the error:

Georges-MBP:demo gbarnabic$ python3 sierpinski.py
Traceback (most recent call last):
  File "sierpinski.py", line 58, in <module>
    punch(pm, 0, 0, d, d)
  File "sierpinski.py", line 31, in punch
    ir = fitz.IRect(x01, y01, x02, y02)  # rectangle of middle square
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/fitz/fitz.py", line 432, in __init__
    this = _fitz.new_IRect(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_IRect'.
  Possible C/C++ prototypes are:
    fz_irect_s::fz_irect_s()
    fz_irect_s::fz_irect_s(struct fz_irect_s const *)
    fz_irect_s::fz_irect_s(int,int,int,int)

Georges-MBP:demo gbarnabic$

**Comment by rk700** [comment]
This happens because of the difference in integer division between python2 and python3. `5/3=1` in python2, while `5/3=1.66667` in python3. 

I just updated the script for python3. Please check it out.

Also note that I moved the `sys.setdlopenflags(0)` call into file `__init__.py` and would invoke it only for OSX. It should be fine I guess.

**Comment by gbarnabic** [comment]
Sorry for my lack of knowledge on this. I'm new to Python and figured there would be no need to even look at 2.7.  It amazes me how many folks still use 2.7 but I understand legacy code coming from a long career in programming.  Believe it or not there are still some auto repair shops in my local area that are still using a DOS program I wrote in a dBase language call Clipper over 25 years ago.
