### ISSUE TITLE
Files for V1.9 & a text extraction issue

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#45]
@rk700 - created branch 1.9 and populated fitz sub dir with updated files (fitz.i etc.)

They passed the tests on my Python 2.7 32-bit installation and thus are ready to be tested on other platforms (Linux, OSX).

Interesting issue:
---------------------
If you use ``fitz.Device(ts, tp)`` in a certain way, then the TextPage's text extraction functions will return no text! More specifically:

This will work (``dl`` is a DisplayList):
```
ts = fitz.TextSheet()
tp = fitz.TextPage()
dl.run(fitz.Device(ts, tp), fitz.Identity, rect)
txt = tp.extractXML()
```

This will **not** work (i.e. will deliver no text):
```
ts = fitz.TextSheet()
tp = fitz.TextPage()
dv = fitz.Device(ts, tp)
dl.run(dv, fitz.Identity, rect)
txt = tp.extractXML()
```

However, ``tp.search()`` will work correctly either way.

**Comment by rk700** [comment]
@JorjMcKie I tried the latest PyMuPDF with MuPDF 1.8 on my x86_64 linux machine, using both python2 and python3. And there's the code(just a little modification to the demo/extract.py):

```
#!/usr/bin/env python
import fitz
import sys

if len(sys.argv) != 3:
    print('Usage: %s <input file> <page num>' % sys.argv[0])
    exit(0)

#get the page
d = fitz.Document(sys.argv[1])
pg = d.loadPage(int(sys.argv[2]))

#setup the display list
dl = fitz.DisplayList()
dv = fitz.Device(dl)
pg.run(dv, fitz.Identity)

#setup the text page
ts = fitz.TextSheet()
tp = fitz.TextPage()
rect = pg.bound()
tdv = fitz.Device(ts, tp)
dl.run(tdv, fitz.Identity, rect)

#get the text content
text = tp.extractXML()
print('%s' % text)
```

The above code worked well with several different PDF documents. So I'm not sure if it's an issue for Windows only.

**Comment by JorjMcKie** [comment]
Sorry, I did not express myself clearly enough:
Yes it works under 1.8 without problem.
**It is an issue with V1.9.**

Independently (?), MuPDF V1.9 also has the issue, that ``fz_print_stext_page_xml`` falsely returns the mediabox as zero. I issues a bug to their web site already.
So, even when I do everything correctly correctly so that the text comes out, it still would say width='0' and height='0':

```
<page width="0" height="0">
<block bbox="44.017328 58.79541 358.15534 89.52941">
<line bbox="44.017328 58.79541 358.15534 89.52941">
<span bbox="44.017328 58.79541 358.15534 89.52941" font="Helvetica-Bold" size="22">
<char bbox="44.017328 58.79541 57.459329 89.52941" x="44.017328" y="82.33541" c="T"/>
...
```
In our PyMuPDF

**Comment by rk700** [comment]
MuPDF 1.9 finally came into the Archlinux repo, but I found that some structures are no longer available in the the header files now, e.g., fz_text_page, fz_text_sheet.

**Comment by JorjMcKie** [comment]
All structured text components have been renamed in this release following this scheme:

fz_text_something ==> fz_stext_something

I sent you a PDF with these changes, but you may not have received it. Here is a text copy of my findings:

Disclaimer
========
This is just a list of what we encountered when adapting the PyMuPDF binding. So this overview may very well not be complete and different for other languages.
It is also an intermediate result and may change as we progress in testing. Another set of changes may also occur with the final version 1.9.

Saving a Document
================
Variables and interfaces for writing / saving documents are no longer contained in the fitz directory, but only in pdf directory. Document output has ever been a capability available to PDF documents only, so this decision of MuPDF team was only consequent.
Now, saving documents therefore cannot be done using the fitz.Document object directly.
Before saving a pdf, its respective  fitz.Document must first be converted to a pdf document. This can be done by calling ``pdf_specifics(context, fz_document)`` (contained in ``source/pdf/pdf-xref.c``).
As a further consequence, ``fz_write_options`` has also gone away, and pdf_write_options must be used instead.
Saving a Pixmap Image
===================
Names have been changed, see the following table. 
```
    Old Name        New Name
    fz_write_png	fz_save_pixmap_as_png
    fz_write_pnm	fz_save_pixmap_as_pnm
    fz_write_pam	fz_save_pixmap_as_pam
    fz_write_tga	fz_save_pixmap_as_tga

```
Creating Pixmaps from Image Files
============================
In version 1.8 the creation of pixmaps directly from PNG files or PNG buffers was possible. All technical information, like color space and size were taken from the image input.
This same type of support is now also available for other image file types like JPEG, GIF, TIFF.

Structured Text
=============
Names have changed following the scheme ``fz_text_*`` => ``fz_stext_*``, obviously in an effort to emphasize “structured text”.

```
Old Name            New Name
fz_new_text_device  fz_new_stext_device
fz_new_text_page    fz_new_stext_page
fz_new_text_sheet   fz_new_stext_sheet
fz_text_block       fz_stext_block
fz_text_char        fz_stext_char
fz_text_line        fz_stext_line
fz_text_span        fz_stext_span

```
Output
======
Names have changed, see the following:
```
Old Name                    New Name
fz_new_output_to_filename	fz_new_output_with_path
```
Includes a new bool option to append to the specified file (instead of creating a new one).

**Comment by JorjMcKie** [comment]
@rk700 - BTW, I have of course adapted ``fitz.i`` in the 1.9 branch to reflect all of the above changes. So, in theory, generating for other platforms should work out of the box.

**Comment by rk700** [comment]
The code above results in memory corruption on Linux, and it seems that the `fz_stext_device_s` being freed before `TextSheet` and `TextPage` is the reason. Again we might need to add a reference count to ensure the order of object destruction.

**Comment by rk700** [comment]
It seems that some text span rendering work is done when closing the `fz_stext_device_s`. If the device is not destructed before calling `extractXXX()`, then the text would be missing.

**Comment by JorjMcKie** [comment]
I have checked it out, and you are right:
If I do this:
```
dv = fitz.Device(ts, tp)
dl.run(dv, fitz.Identity, rect)
#dv = None
text = tp.extractText()
```
then nothing will be in ``text``.
Uncommenting ``dv = None`` will yield the correct result.
if I use this
```
dl.run(dv, fitz.Identity, rect)
text = tp.extractText()
```
Then also everything seems to work.

As this obviously is how MuPDF 1.9 works - what do we do? Just accept it and document how this must be done?

**Comment by rk700** [comment]
Exactly. And I also notice that if the destruction is just after the `extractXXX()`method like this:
```
dv = fitz.Device(ts, tp)
dl.run(dv, fitz.Identity, rect)
text = tp.extractText()
dv = None
```
Then there would be nothing again.

Therefore, maybe we could put all the dirty work in the PyMuPDF library so that normal users do not need to take care of the object management. I'm considering whether we can create some kind of new API for calling the `DisplayList.run()` method. And in the new API, the Device destruction is done as soon as the `run()` finishes. Of course, this could lead to a lot of changes in our previous code, but it may make PyMuPDF easier to use.

**Comment by JorjMcKie** [comment]
I fully agree. For example, I cannot think of a normal user who wants to get the text **after** any matrix transformation. Anyone who needs the text, needs it from the full, un-tranformed page.
So, in these cases, he should not be bothered with devices, text sheets and so on.
He should be able to say: "give me the text of page 20 in JSON format" - nothing more. And similarly "Look for string ``abrakadabra`` on page 123".
He does not need to know that there are any of the other, very technical objects in the play for this.
I am currently experimenting with exactly the same stuff and have the following type of code already fully working:

```
# This script deletes all pages from a doc that do not contain any text
from __future__ import print_function
import fitz
doc = fitz.open("pymupdf.pdf")         # "open" is an alias for "Document" here
lst = list(range(doc.pageCount))       # integer list of all pages

for p in fitz.Pages(doc):  # fitz.Pages is a new iterator over a doc's pages
    txt = p.getText()     # method "getText" hides all detail stuff (TextSheet, Device etc.)
    if not txt:
        lst.remove(p.number)
        print ("page", p.number, "contains no text - removed.")

# new in 1.9:
# select is a method that reduces the doc in memory to just the wanted pages        
doc.select(lst)  
doc.save("out.pdf", garbage=3)
```
All this was not too difficult, except for the ``select()`` method. Every code else is already contained in ``utils.py``, pure Python in other words.

I did a similar thing with Pixmap:

```
# getting a page's pixmap is a 1-liner
pix = page.getPixmap(matrix = xxx, colorspace = 'rgb')

# same on the document level:
pix = doc.getPagePixmap(pno, matrix = xxx, colorspace = 'rgb')

```
Behind the scenes, our existing fitz.i code (Device, DisplayList, etc.) is continued to be used and remains available for the "expert mode".
Maybe we should include a chapter about a low level expert mode in our documentation ...
