### ISSUE TITLE
PyMuPDF binary file size

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#46]
At least under Windows, the size of the binary file (``_fitz.pyd``, I presume ``_fitz.so`` in Linux) has increased significantly, practically doubled from 9.4 MB to now 17.5 MB.

This is due to hundreds of new font definitions now incorporated. Most notable the Google NOTO (= "no tofu") fonts. In Windows, we now need to build _fitz.pyd out of 3 library files: libmupdf, libthirdparty and now also libfonts.

In our bindings, we actually do not need fonts, or do we? Maybe we do during rendering?

If we don't need them, it may be worthwhile to find a way to exclude them during MuPDF generation.

Just omitting the libfonts won't work, because libmupdf references the object file NOTO (which is generated by compiling ``noto.c``) and the linker step will generate hundreds of unresolved references ....

**Comment by rk700** [comment]
On Linux, the output libraries are libmupdf.a and libmupdfthird.a. The fonts related code(noto.o) is contained in libmupdf.a, which is 23 MB. Yes it is very large. However, currently I don't have any good way to split the library file and remove the fonts definitions. 

Library loading on Linux can be in lazy mode, which means the addresses are not resolved until used. So if NOTO objects are not used in PyMuPDF, then it should be OK to build PyMuPDF without the fonts. But I'm not sure whether lazy resolving is supported on Windows. Python documents says that it can be controlled by `dlopenflags`, which is available only on *nix platform:
https://docs.python.org/2/library/sys.html#sys.setdlopenflags

**Comment by JorjMcKie** [comment]
Thank you for looking into this. I was afraid your answer would be like that ... :-)
When I looked at the code, I saw that NOTO fonts are only inquired when other searches for adequate fonts do not succeed.
Of course we could change the MuPDF source to avoid this behaviour, e.g. by replacing noto.c by our own version ... But of course this is no real option.
On Windows systems, there is a binary executable code compressor, UPX, which dynamically decompresses any executable **after** it has been loaded from disk into memory.
I am using this systematically since 1.9. It brings down the original 17 MB ``_fitz.pyd`` (= *.so) to just under 8 MB. Which is the size of previous PyMuPDF binaries.
In this way the effect of NOTO is back under control a little.
The description says that UPX (http://upx.sourceforge.net/) also is available on Linux.

**Comment by JorjMcKie** [comment]
I had another look at ``noto.c´´.
There are several ``#ifdef`` statements available that exclude major parts of the fonts to be supported like ``NOTO_SMALL``, etc.
I will try to use some of these options when I experiment with the 1.9a release ...

**Comment by JorjMcKie** [comment]
sorry for the bombardement of messages ...
I just re-generated my MuPDF 1.9 for 32bit. I inserted ``#define NOTO_SMALL`` in the header file ``fitz.h``.
The generated lib files did not decrease, but my Python load module ``_fitz.pyd`` came down to 12 MB (from 17 MB), and the UPX-compressed version is now only 5.6 MB (8 MB before).

**Comment by JorjMcKie** [comment]
for people generating MuPDF like in Linux, we should recommend changing the header file ``fitz.h`` to look like this:

```
#ifndef MUDPF_FITZ_H
#define MUDPF_FITZ_H

#define NOTO_SMALL            // take small subset of NOTO fonts
#define TOFU_CJK              // exclude Android specific CJK fonts

#ifdef __cplusplus
extern "C" {
#endif
....
```
When doing so, the final ``_fitz.so`` / ``_fitz.pyd`` files will have a similar size as with version 1.8.
