### ISSUE TITLE
Porting and Tests for MuPDF 1.9a concluded

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#48]
@rk700 - I have finished porting and testing our stuff to / with MuPDF 1.9a. This sub-version did not impact our code for version 1.9 in any way.

As discussed recently, text extraction is now also represented by methods directly under the Document and Page classes. Users can be ignorant of DisplayList, TextSheet, TextPage and text Device classes altogether if they are just dealing with text extraction.

More or less the same is true for the Pixmap class: it too now has new methods directly connected to the Document and Page classes.

I dare say that this approach has no negative performance impact for "normal" users. This is certainly true for text extraction.

Only for rendering pages, explicitely using the DisplayList can yield a performance advantage, e.g. when a user displaying a document decides to zoom in or out a currently displayed page.

Of course, all these classes (DisplayList, Device, TextSheet, TextPage) are still there and available for use to those who dare ...

Question:
Do you want to publish a new release given the current status?

**Comment by rk700** [comment]
@JorjMcKie wow that's amazing. I'd be glad to have your code released since it definitely simplifies the usage. I've just merged the 1.9 branch into the master, and we can now create a release based on it.

Thank you so much for the work:)

**Comment by JorjMcKie** [comment]
Thank you very much ... :-)
