### ISSUE TITLE
Doc for type of Link.dest is wrong

### ISSUE THREAD

**Issue by mozbugbox** [rk700/PyMuPDF#49]
The API document for Link class has the wrong type for `Link.dest`. 

* the type of `Link.dest` should be a `LinkDest` instead of `int`.

* the type of `LinkDest.dest` should be `string` since it will point to `fileSpec` if valid.

* the type of `LinkDest.named` should be `string` too.

**Comment by JorjMcKie** [comment]
Confirmed - thank you very much!
Please watch out for the update during the day ...

**Comment by JorjMcKie** [comment]
changes applied
