### ISSUE TITLE
more matrix methods

### ISSUE THREAD

**Issue by mozbugbox** [rk700/PyMuPDF#51]
Since the matrix was wrap, the most other matrix operation should be included.

Because once a user start using transform matrix, then all kind of matrix operations will likely be used.

* matrix.invert
* matrix.translate
* matrix.compose (is it called concat in mupdf?)
* transform point

**Comment by JorjMcKie** [comment]
Nice idea!
Let me make sure I understood everything correctly:
* matrix.invert means: given a matrix M, find a matrix N such that (matrix multiplaction) ``N*M = E`` (unit matrix)?
* matrix.translate: actually covered by manipulation of components ``e`` and ``f`` isn't it?
* matrix.compose means: given matrices M, N, determine ``N*M``?
* transforming a point p with matrix M means: calculate the new point ``p*M``?

**Comment by rk700** [comment]
FYI
The mathematics is contained in the `include/mupdf/fitz/math.h` header file.

**Comment by mozbugbox** [comment]
You are completely right.

The implementation of matrix operations are in source/fitz/geometry.c

**Comment by JorjMcKie** [comment]
OK, fine. I'll will take that then.

**Comment by JorjMcKie** [comment]
Just uploading new methods - hopefully as requested.
As part of that several other new methods were also included, like rectangle union and intersection.
I will update the Wiki page as well shortly to reflect what we have.
Documentation should be up to date. You are an attentive reader - so please have a look. Any feedback is very welcome.

**Comment by JorjMcKie** [comment]
I have just uploaded an update which introduces numerical arithmetics for the ``fitz.Matrix`` class. Now expressions like ``m1 + m2``, ``m1 * m2``, ``-m``, ``~m`` are defined and can be used to elegantly formulate complex matrix computations.

**Comment by mozbugbox** [comment]
Thanks, I do like that the convenient methods that return new matrix.
