### ISSUE TITLE
linkDest._getFileSpec cause segfault

### ISSUE THREAD

**Issue by mozbugbox** [rk700/PyMuPDF#56]
According to http://mupdf.com/docs/browse/include/mupdf/fitz/link.h.html:

    gotor.file_spec: If set, this destination should cause a new
    file to be opened; this field holds a pointer to a remote
    file specification (UTF-8). Always NULL in the FZ_LINK_GOTO
    case.

When `kind == FZ_LINK_GOTO`, the file_spec should be NULL. However, it's not really the case and file_spec could point to some invalid pointer (so this could be a mupdf code bug or doku bug). When access file_spec with `kind == FZ_LINK_GOTO` in some PDF, I got segfault.

The code should exclude `FZ_LINK_GOTO`:
```
        char *_getFileSpec() {
            return ($self->kind == FZ_LINK_GOTOR) ? $self->ld.gotor.file_spec : ($self->kind==FZ_LINK_LAUNCH ? $self->ld.launch.file_spec : NULL);
        }
```

The same could happens to `linkDest._getDest`: `FZ_LINK_GOTO` should be excluded.

**Comment by rk700** [comment]
:+1: 
Code updated accordingly.
