### ISSUE TITLE
New: PDF Document method setToC()

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#59]
The outlines of a PDF can now be added, changed or deleted by using ``Document.setToC(list)``.
This will replace the **complete outline tree** with the entries in the Python ``list``. An empty list ``[]`` will delete all outlines.
The general format is ``list = [[lvl, title, pno, top], [...]]``.
Outputs of ``getToc(simple = True)`` and ``getToC(simple = False)`` (with any required modification) are also supported as input to this function.

**Comment by rk700** [comment]
Great! So the outline tree is no longer kept right?

**Comment by JorjMcKie** [comment]
Technically, the following is happening:
---------------------------------------------------
1. Get the outline root ("/Type/Outlines") from the document root and create a list of all xref numbers for objects in the current outline tree.
2. Delete all outline objects referenced by these xref numbers, so they are marked free, and the respective outline items become unused (being physically deleted by some utility like mutool clean).
3. Update the outline root to having no kids and /Count = 0. At this point, the PDF shows to no longer having outlines.
4. If the list of new outlines is not empty: Allocate a list of new xref numbers for these items and create a new outline tree as a **list of strings** (all of this part is happening in Python code for a number of reasons, see below).
5. Create PDF objects from the generated strings and update the new xref numbers to point to these objects appropriately. Now the document has a new outline tree.

Why did I choose this approach?
--------------------------------------------
Alternatively, a single outline item in the current tree could have been exposed to Python for update / delete. Likewise, a new item could have been accepted from Python for insertion.

This would require significantly more challenging logic, like:
- For an INSERT, I must allocate a new object and update /Next and /Prev of its predecessor and follower, and increase the parent's /Count, and potentially also its /First and /Last fields. Which in reality means allocating new parent, predecessor and follower objects to contain those new values.
- Similarly for a DELETE. Additionally, if the item has kids, all of those must be deleted, too.
- A REPLACE requires allocation of a new object with the new content.
- Because I need xref numbers for all the above actions, those must be handed back to the Python level and be provided again for further processing. This implicates **a lot** of required logic to immunize against Python programming errors.

Compared to this, the approach chosen seems a lot more straightforward and it is also compatible with what we already have with ``getToC()``.

In addition, as a side effect, we are positioned for further enhancements / features: now we have the following (low level technical) methods:
- determine the xref number of a given page (xref and generation number)
- allocate a new xref number
- insert an arbitrary PDF object provided as a string

**Comment by JorjMcKie** [comment]
Error checking with the current approach is not yet implemented.
However, it will consist of only a few basic things to be applied to the handed-in Python list:

1. Hierarchy levels must be integers > 0
2. First item must have hierarchy level 1
3. Hierarchy level of any item must be at most 1 higher than the previous one
4. Page number must be valid (implemented)
5. ``0 < top <= page.bound().y1``

Conditions 1 to 4 should lead to exceptions. Condition 5 should silently be corrected by ``top = page.bound().y1 - 36``, i.e. bookmark target goes to 1/2 inch below top of the page.

**Comment by JorjMcKie** [comment]
Obviously, bookmark maintenance features, and PDF output in general, are in fairly high demand among the Python programming community. Yesterday I published a [code snippet](https://code.activestate.com/recipes/580684-simple-pdf-bookmark-table-of-contents-maintenance/?in=user-4193772) about this new feature and within less than 12 hours more than 300 people had viewed it. Other PyMuPDF recipies I had been publishing there have received 2.000 to 3.000 views within 3 months or less.

**Comment by JorjMcKie** [comment]
I have uploaded an improved version containing the above mentioned error checking.
These checks occur before any changes to the document object.

**Comment by rk700** [comment]
Nice! It makes sense to me now. Thank you!
