### ISSUE TITLE
Draw annotation

### ISSUE THREAD

**Issue by mozbugbox** [rk700/PyMuPDF#60]
Current PyMuPDF don't draw annotations.

From the [code in  mupdf](/ArtifexSoftware/mupdf/blob/master/platform/x11/pdfapp.c), to display annotation:
1. a page need to track annotation through `fz_first_annot()` and  run annotations through `fz_run_annot()`.
2. accept mouse button click event through `pdf_pass_event()`.
3. If `pdf_pass_event()` return `True`, get updated annotations through `pdf_poll_changed_annot()` and re-run the updated annotations, or simply re-run all the annotations.

**Comment by rk700** [comment]
@JorjMcKie Any idea about it? It seems to be quite low-level and maybe we should no longer expose the details.

**Comment by mozbugbox** [comment]
On further look, PyMuPDF use `fz_run_page` to run a page. `fz_run_page` *does* run over annotation.

**Comment by JorjMcKie** [comment]
As I understand it, we currently only take care of annotation subtype **link**.
I think we should prioritize what we want to do medium term.
Before that, we should agree on what we want to achieve with PyMuPDF long term. Maybe a "mission stament" could be: "Compete with other free PDF software in all major aspects" - please correct / adjust.
If, however, we agree on this, then an obvious gap analysis contains the following items:
**Input:**
* support all annotation subtypes
* support form / field filling (like ``pdftk``)
* more general information (images / fonts used - like ``mutool info``)

**Output:**
* merging / concatenating page ranges of PDFs (preserving annotations, bookmarks, etc., like ``PyPDF2``, ``pdfrw``, ``pdftk``)
* insert annotations (``Nitro PDF``)
* buffer output (like ``pdfrw``, ``PyPDF2``, ``pdftk``)
* encryption (``PyPDF2``, ``pdftk``)
* watermarks (``pdfrw``, ``PyPDF2``)
* posterizations, 2-up, 4-up, etc. (``pdfrw``)

Whatever you think about the above list (I already arranged it according to my personal preferences): let's first agree on it / change it / extend it / strip it down, and then create an implementation plan.
I am enthusiastic about the power still buried in the MuPDF library - we just need to decide what to do next - it is all there in the code. Looking at the new `mutool run` javascript feature demonstrates what we can achieve for PyMuPDF.

**Comment by JorjMcKie** [comment]
I should have been more specific to your question, @rk700 -
PyMuPDF does of course not itself have a frontend: it only provides access to **existing** features of the underlying MuPDF for the Python programmer.
I agree with @mozbugbox that we should extend PyMuPDF in a way that ``Page`` objects have an ``loadAnnots`` property that points to the first annotation of a page - very much like ``loadLinks`` now.
A new ``Annotation`` class then contains all properties and methods that the MuPDF level provides, including a ``next`` property as pointer to the next annotation.
If I understood everything right, the so-created new annotation chain would be a superset of the existing link chain of a page.
For a talented Python GUI programmer, it would then be possible to create an application that does the following:
![test](https://cloud.githubusercontent.com/assets/8290722/16362171/f894c9b6-3b74-11e6-9b66-447d3ba215fa.png)

**Comment by mozbugbox** [comment]
There can be a layer of low level wrapper that wraps MuPDF API directly, maybe with some additional exception handling code. Then a lot of high level pythonic API can be created in Python based on the low level functions, instead of in C at the swig layer.

For example, listing fonts used, can be done with python codes:
```py
    font_list = set()
    doc = fitz.open(sys.argv[1])
    pdoc = fitz.pdf_specifics(doc)
    for i in range(doc.pageCount):
        pageref = pdoc.lookup_page_obj(i)
        pageobj = pageref.resolve_indirect()
        rsrc = pageobj.dict_get(fitz.PDF_NAME_Resources)
        font = rsrc.dict_get(fitz.PDF_NAME_Font)
        if not font:
            continue
        n = font.dict_len()
        for i in range(n):
            font_dict = font.dict_get_val(i)
            basefont = font_dict.dict_get(fitz.PDF_NAME_BaseFont)
            name = font_dict.dict_get(fitz.PDF_NAME_Name)
            if basefont:
                font_list.add(basefont.to_name())
            if name:
                font_list.add(name.to_name())
    for f in sorted(font_list):
        print(f)
    print("Total: {}".format(len(font_list)))
```
There, `pdf_specifics`, `lookup_page_obj`, `resolve_indirect`, `dict_get`, `dict_len`, `dict_get_val`, `to_name` are the few MuPDF low level functions wrapped to Python.

Of course, not all features can be easily realized in Python code. Those features can be done in the C code with swig.

**Comment by JorjMcKie** [comment]
@mozbugbox - I think this goes in the right direction. And I wouldn't be afraid of users wanting more features, because it shows that our software is being accepted :-)
I am actually already working at such low-level functions. Some of them you mention are already there, because I needed them for the methods ``setMetada()`` and ``setToC()``. So far, they are all methods of the ``Document`` class:
* ``_getPageObjectNumber(pno)`` return a list of integers ``[xref, gen]``, where ``xref`` is the XREF number of page ``pno`` and ``gen`` the generation number.
* ``_getOLRootNumber()`` returns the XREF of the outline root (``/Type/Outlines``). If there is no outline, it will be created empty.
* ``_getNewXref()`` creates and returns a new, free XREF entry (int).
* ``_updateObject(xref, string)`` interprets the string as a PDF definition of a dictionary or  an array object and assigns the provided ``xref`` number to it. The underlying C functions ``pdf_new_obj_from_str(gctx, pdf, text)`` and ``pdf_update_object(gctx, pdf, xref, new_obj)`` are also used during initial parse of the PDF during open. If this XREF number has had a previous object assigned, that object will become unused / deletable.

All of the above are just a start. Quite expressive exception handling is now also part of PyMuPDF as you may have noticed.

**Comment by JorjMcKie** [comment]
Work on PyMuPDF is continuing ...
David Hughes, the repo owner of the new wxPython version "Phoenix" has expressed his intention to include PyMuPDF as a standard PDF viewer library in Phoenix.
In response to that, @rk700 has created a new branch, v1.9.2, which will be our next sub-release.
I have already populated this branch with an updated PyMuPDF. Most prominent new feature is the ability to join PDFs directly under PyMuPDF. Documentation is up to date.
Please do have a look into this version. It is based on the same MuPDF version 1.9a, so no new generation of that part is required ...

I also have added a [Wiki](https://github.com/rk700/PyMuPDF/wiki/Inserting-Pages-from-other-PDFs) explaining how this works.

**Comment by JorjMcKie** [comment]
I am currently finalizing work to make v1.9.2 the new master.
Contained in this are the following major new features:

* joining PDF documents (``insertPDF()``)
* list images used per PDF page
* list fonts referenced per PDF page
* new pixmap constructor allowing PDF-internal images as input
* new pixmap constructor allowing other pixmaps as input - includes colorspace conversion

To illustrate what that accomplishes:
You can now extract all images of a PDF and store them as separate PNG files ...

**Comment by JorjMcKie** [comment]
I am testing an update that supports annotations - for display only as a first step.
These are the features:

**All Document types:**
1. A new ``Annot`` class
2. Step through all annotations of a ``Page`` as a forward-linked list (like links)
3. Poperty ``rect`` (`fitz.Rect`) describes location of an annotation on the page
4. Method ``getPixmap(matrix, colorspace)`` generates a pixmap of an annotation's image

**PDF Documents:**
- Property ``type`` is an integer describing the annotation type.

**Comment by JorjMcKie** [comment]
@mozbugbox - I think the new v1.10.0 addresses this issue. Could please have a look decide whether to close this issue?
