### ISSUE TITLE
Bytearray API changes

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#61]
I am going to introduce some API changes required to improve consistency between the Python 2 and Python 3 versions:

Background
-----------------
The SWIG handling of char * parameters lead to different Python source code handling between Py2 and Py3. E.g. when creating a pixmap from memory with image data, an area created under Python3 with ``open("img.xxx", "rb").read()`` will not be accepted because its type is ``bytes`` and not ``str``.
In this and all similar - see below - cases I changed the interface from ``str`` to ``bytearray``.
It is my hope that this has limited impact to your existing code. On the positive side:
- improved source code compatibility between Python 2 and Python 3
- length parameters for bytearrays need not be specified
- more internal consistency

Affected methods
-----------------------
The affected methods pertain to opening a document from memory, creating a pixmap from memory or from a ``samples`` area and the pixmap output method ``getPNGData()``:
![bytearray-changes](https://cloud.githubusercontent.com/assets/8290722/16378698/4ccfbd08-3c3b-11e6-8c72-266b7fcd2aa0.PNG)

**Comment by rk700** [comment]
I just find that some of my previous code does have problems when reading pixmap sample bytes with the latest PyMuPDF. But I haven't figure out the reason yet.

**Comment by JorjMcKie** [comment]
I know what it is I believe:
Since one of the recent enhancements requested by @mzugbox, an additional irect parameter is required for draw devices, which can be None if the whole page should be taken.
If you talk about old programs, then you probably use draw devices directly. The other methods encapsulate draw device usage …

Von: Ruikai Liu [mailto:notifications@github.com]
Gesendet: Montag, 27. Juni 2016 09:09
An: rk700/PyMuPDF <PyMuPDF@noreply.github.com>
Cc: Jorj X. McKie <jorj.x.mckie@outlook.de>; Author <author@noreply.github.com>
Betreff: Re: [rk700/PyMuPDF] Bytearray API changes (#61)


I just find that some of my previous code does have problems when reading pixmap sample bytes with the latest PyMuPDF. But I haven't figure out the reason yet.

**Comment by JorjMcKie** [comment]
@rk700 could you fix your problem? Anything I can do?

**Comment by rk700** [comment]
Hmm, I think it's fine to close the issue now since it may take me some time before finding the real cause.

**Comment by rk700** [comment]
@JorjMcKie Yes you are right. The issue went away after I used the new API for drawing device. Thank you!
