### ISSUE TITLE
ImportError during "import fitz" in Python 3.5 virtualenv on OS X 10.11

### ISSUE THREAD

**Issue by david-hughes** [rk700/PyMuPDF#62]
I built pymupdf according to your instructions, then activated my virtual env (env3.5) and started Python

[error.txt](https://github.com/rk700/PyMuPDF/files/371833/error.txt)

This is beyond my technical range, Does the error give any indication of what I'm doing wrong?

Regards, David

**Comment by rk700** [comment]
Thank you!

I've updated `setup.py` for OSX: https://github.com/rk700/PyMuPDF/commit/d4229cfd6442fdab83743212a91253a91534155d. Hopefully the issue is resolved now.

**Comment by david-hughes** [comment]
Thanks for the rapid response!

Everything is working fine now.
