### ISSUE TITLE
Support of Unicode

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#63]
@rk700 
when introducing new methods ``setToC`` and ``setMetadata`` I realized that only a certain PDF character set really is supported by these functions: PDFDocEncoding. This character set is one of two options to be used for this type PDF information data. Other text like that of the actual PDF content is independent from this.
PDFDocEncoding is a superset of ASCII and latin-1, but only supports characters of one byte - see appendix D of the PDF manual.
My question to you (as the owner and as someone who certainly uses characters from a wider Unicode range on a daily basis ...):
**Should we not extend PyMuPDF's capabilities to the full unicode scope?**
Wouldn't a Chinese person likes to see outline item titles and metadata information in Chinese letters instead of those of the Latin alphabet? Currently, we cannot support this.

Apart from **PDFDocEncoding**, PDF does support full unicode, but in the **UTF-16BE** encoding only. This means that text encoded this way has to start with U+FEFF followed by the actual information, encoded in UTF-16BE.
I have tested a little bit in this area, here is my current take:
- Py2 and Py3 handle strings and unicode differently. This is a complication.
- In order to specify a unicode string to PDF, it must apparently be provided as hexadecimal data. So e.g. instead of specifying ``/Author(Jorj McKie)`` in metadata one would have to specify ``/Author<feff004a006f0072006a0020004d0063004b00690065>``.

When implementing this, we need to take care of Python 2/3 differences. And we maybe want to switch over to unicode only when we must ...

Please let me know your reaction.

**Comment by rk700** [comment]
I just tried `getToC()` to get the outline items:
```
liuruikai756@mbp:~/tmp$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
>>> doc=fitz.Document('arm_linux.pdf')
>>> toc=doc.getToC()
>>> print toc[0]
[1, '\xe5\xb0\x81\xe9\x9d\xa2', 1]
>>> print toc[0][1]
封面
>>> s='封面'
>>> type(s)
<type 'str'>
>>> s
'\xe5\xb0\x81\xe9\x9d\xa2'
```

As you can see, the item title is encoded in UTF-8 and can be printed correctly in Chinese. So I'm not quiet sure that I get the point.

**Comment by JorjMcKie** [comment]
What happens if you try to change the TOC with ``setToC`` and enter a title in Chinese?

**Comment by rk700** [comment]
Right, the Chinese characters cannot be show correctly.

**Comment by rk700** [comment]
It seems that the characters can be shown by encoding them in UTF-16:
```
liuruikai756@mbp:~/tmp$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
>>> doc=fitz.Document('arm_linux.pdf')
>>> toc=doc.getToC()
>>> print toc[0]
[1, '\xe5\xb0\x81\xe9\x9d\xa2', 1]
>>> toc[0][1]='测试'.decode('utf-8').encode('utf-16')
>>> print toc[0]
[1, '\xff\xfeKm\xd5\x8b', 1]
>>> doc.setToC(toc)
309
>>> doc.save('1.pdf')
0
```

What I did was:

- decode the utf-8 string to unicode
- encode the unicode with utf-16

The conversion should be put in `setToC()` so that users only need to provide a utf-8 string.

Also, as you mentioned, Python 3 handles string in a different way. Though I haven't tried yet, the following snippet should work in Python 3:
```
>>> '测试'.encode('utf-16')
b'\xff\xfeKm\xd5\x8b'
```

We can get Python version from `sys.version_info[0]`. So the code might look like this:
```
if sys.version_info[0]==2:
    utitle = title.decode('utf-8').encode('utf-16')
else:
    utitle = title.encode('utf-16')
...
```

**Comment by JorjMcKie** [comment]
Ok, good. I'll be working on it and come back with something hopefully usefull.
Same considerations apply to metadata updates.
One more complication with Py3 is that ``x.encode()`` yields ``bytes`` not ``str``, as our SWIG interface expects. So the result of ``x.encode()`` needs to be converted back to some ``str`` before invoking SWIG functions ...
In essence I am back to handing over a utf-16BE **string** prefixed with 0xfeff, but converted to hexadecimal string characters ``EFFF...`` like in the above ``/Author`` example.
This is a regrettable waste of space in many cases. However, PDF internally stores strings in that format anyway that contains characters beyond the 8-bit range ...

**Comment by JorjMcKie** [comment]
I think I'm done. Successfully tested the following code under Py2 and Py3:


    a = "बाह्यसम्पर्कतन्तु, आर्थिककेन्द्रत्वेन वर्तते"        # sanskrit
    b = "normal ascii"                      # normal ascii
    c = "sòmé lâtîn!"                       # latin-1 
    e = "Euro sign €"                       # ascii and 1 unicode char
    f = "测试"                               # Chinese
    g = "Фёдор Михайлович Достоевский"      # Russian
    
    import fitz
    doc = fitz.open("test.pdf")
    m = {"author": b, "producer": c, "subject": e, "title": f, "creator": g,
         "keywords": a}
    
    doc.setMetadata(m)
    
    toc = [[1, a, 1],
           [1, b, 2],
           [1, c, 3],
           [1, e, 4],
           [1, f, 5],
           [1, g, 6],
          ]
          
    doc.setToC(toc)
    
    doc.save("testmeta.pdf", garbage=3)

I will upload the fix during the day.
