### ISSUE TITLE
Calling fitz.open() using the stream and streamlen parameters with Python 3.4

### ISSUE THREAD

**Issue by david-hughes** [rk700/PyMuPDF#64]

**Comment by david-hughes** [comment]
Oops! Using the stream parameter works OK in Python 2.7 (the stream is extracted from an in-memory pdf file object created using ReportLab) because the stream is <type 'str'> but in Python 3.4 the type is <class 'bytes'> - which is rejected by fitz.open().

None of my attempts to convert the type to str using decode() seem to work and a conversion using 
        stream = ''.join(list(map(chr, list(stream))))
which produces a byte-for-byte identical stream produces errors like:

error: cannot recognize xref format
error: cannot read xref (ofs=19037)
error: cannot read xref at offset 19037
warning: trying to repair broken xref
error: bad data in a85d: ''
warning: read error; treating as end of file
warning: premature end of data in flate filter
error: bad data in a85d: ''
warning: read error; treating as end of file
warning: premature end of data in flate filter
error: bad data in a85d: '­'
warning: read error; treating as end of file.......

Any suggestions, please?   - David

**Comment by david-hughes** [comment]
Er, the stream types got omitted above, probably because they were enclosed in angle brackets. 
The stream type created in in Python 2.7 is **type str** but in 3.4 the type is **class bytes**

**Comment by JorjMcKie** [comment]
@david-hughes  - this has changed, see ``Bytearray API changes #61``. What you need to do is
``stream = bytearray(open(<pdffile.pdf>, "rb").read())``.
This should give you a bytearray in Python 3 versions.
Then ``doc = fitz.open("x.pdf", stream)`` should indeed work. Just tested it (again).

**Comment by JorjMcKie** [comment]
The above should BTW of course also work under Python 2.
Independently, reportlab may have produced an illformed PDF structure, so MuPDF complaints may still appear on SYSERR, and doc.openErrCode may be > 0 after fitz.open.

**Comment by JorjMcKie** [comment]
Maybe you need to compile the current version of PyMuPDF (not MuPDF). The problem you mention actually was the motivation behind #61.

**Comment by david-hughes** [comment]
Providing the stream as a bytearray - and installing the latest PyMuPDF - works with both Python 2 and 3 and without any SYSERR
However, calling fitz.open( pdf-file-pathname, None) crashes python in both versions here.

**Comment by JorjMcKie** [comment]
I am glad you have a solution.
The crash you mention is as it should be! However, I could have created a graceful exception ... :-)
fitz.open has two overloaded __init__()s: (1) open with a filename (1 arg), or (2) open with filetype and bytearray (2 args). So, if you use 2 args, this init assumes arg2 is indeed a bytearray!
I will implement a better exception handling to make sure, the programmer gets informed adequately.

**Comment by JorjMcKie** [comment]
BTW: if error messages do occur on SYSERR, then the PDF contains more or less severe structural problems, that the underlying MuPDF library detected during open. The last of such messages is always contained in doc.openErrMsg, and doc.openErrCode is set > 0.

You can still work with the document in a normal way even if this happens. MuPDF will raise an exception ("cannot load document ...") if any such errors are too severe. The only difference is, that you cannot use incremental save when saving the document: it must happen to a new file (which will then contained a "healed" PDF document).

**Comment by JorjMcKie** [comment]
uploaded version with a ValueException when fitz.open is called with 2 args and arg2 is not type bytearray.

**Comment by david-hughes** [comment]
OK, I see. I was using the same call to try and achieve both actions, depending on the presence of a bytearray or None, rather like the 1 arg + 2 optional keyword args (stream & streamlen) in the original implementation. That seems more Pythonic to me - but I'm happy to make two separate calls with different signatures depending on the circumstances. I have done so and it all works fine, thanks.
This code is going into wx.lib.pdfviewer in the new Phoenix version of wxPython and the installation of PyMuPDF will be one of the optional requirements for this. To ensure that the version containing these latest changes is used, will it be sufficient to document a requirement for version 1.9.2 or later?

**Comment by JorjMcKie** [comment]
I am very pleased to hear that PyMuPDF will be used in wxPython!
As per your final question: yes that should be sufficient.

**Comment by david-hughes** [comment]
Thanks for your prompt help resolving this
