### ISSUE TITLE
New branch / release v1.9.2

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#65]
@rk700 - I have tested the new code in branch 1.9.2 under Windows for Python 2 and 3, 32bit and 64bit.
It is ready to be tested under other platforms now. After successful tests on other platforms, the new prepared release v1.9.2 can be published.

Changes or enhancements have been made at the following places:

1. New document method ``insertPDF()`` which inserts pages from another PDF into this one.
1. A new, empty PDF document can be crated with ``fitz.Document()`` (or ``fitz.open()``). Currently, useful only with above new method (as done in example program PDFjoiner.py).
1. When opening a memory-resident document with statements like ``doc = fitz.open("x.pdf", stream)``, ``stream`` can be of type ``str`` (Python 2 only), ``bytes`` (Python 3 only) or ``bytearray`` (any Python version). So, result of e.g. ``open("file.xxx", "rb").read()`` can be directly used in any Python version without first converting it to a bytearray.
1. Documentation is up-to-date. Low-level methods are now documented as well.

Relevant programs in *example* directory have been accordingly adjusted, too. Specifically ``PDFjoiner.py`` and ``PDFoutline.py`` are now "self-sufficient", meaning they have no other dependency apart from PyMuPDF (and the GUI manager wxPython).

It is your choosing when you want to officially publish this new release and make its branch the new master.

**Comment by rk700** [comment]
OK, I'll take a look at the other platforms and publish the release when finished.

**Comment by rk700** [comment]
Version 1.9.2 works on Linux and Mac.

**Comment by JorjMcKie** [comment]
Thank you!
