### ISSUE TITLE
Bitmap in PDF appearing as a black rectangle when viewed or printed using OS X

### ISSUE THREAD

**Issue by david-hughes** [rk700/PyMuPDF#69]
A user of wx.lib.pdfviewer sent me a file that was printing incorrectly when rendered using PyPDF2 under Windows. I checked it using the PyMuPDF option with both Windows and OS X and everything was fine except for the signature bitmap, which appears as a black rectangle with OS X (It renders OK using Windows). A copy of the file is attached. The details in it have been massaged by the user and do not refer to real people. Are you able to reproduce the problem?
[SignedLetter.pdf](https://github.com/rk700/PyMuPDF/files/453301/SignedLetter.pdf)

**Comment by JorjMcKie** [comment]
@rk700 - I have re-tested this case under Windows Py2 and Py3, with and without wxPython. Can confirm David's findings: everything works as expected.
Can you try on your OS X? Don't know whether you have wxPython on it, but any result without wx should help, too.

**Comment by rk700** [comment]
Yes I can reproduce the issue on OSX, which seems to be related with JPEG library version. The output of running `demo.py` is as follows:

```
liuruikai756@mbp:~/Downloads$ ~/src/PyMuPDF/demo/demo.py SignedLetter.pdf 2 100 0 1.png a
producer: ReportLab PDF Library - www.reportlab.com
format: PDF 1.4
author: (anonymous)
title: (anonymous)
creationDate: D:20160901151010+05'00'
creator: (unspecified)
subject: (unspecified)
No outline available
error: jpeg error: Wrong JPEG library version: library is 80, caller expects 90
warning: read error; treating as end of file
warning: padding truncated image
```

Then I updated the `setup.py` and use the 3rd party libraries shipped with MuPDF instead: https://github.com/rk700/PyMuPDF/commit/d07f74d21f4114bfafdbc36933b24e6fd5871c15
And now the signature can be rendered correctly.

Therefore, for OSX users, the right way to install PyMuPDF is updated:
1. install mupdf-tools with brew
2. export ARCHFLAGS='-arch x86_64'
3. run `python setup.py install`

**Comment by david-hughes** [comment]
That works for me - after, ahem, remembering to delete the build directory before running setup.py
Thank you for your fast response
