### ISSUE TITLE
question regarding garbage document.save garbage param

### ISSUE THREAD

**Issue by itatarevic** [rk700/PyMuPDF#71]
Hi, 

I have huge PDF file (600 MB) which have lot of duplicate objects (same fonts and same images). If I run mutools.exe version 1.8 x64 on windows with following params 

mutools clean -ggg -d -s - d -z 600mb.pdf out.pdf

File is almost the same size.

I get same results with following code :
import fitz
file = "c:/temp/600mb.pdf"
doc = fitz.Document(file)
doc.save(filename=new_file, garbage=3, clean=1, deflate=1, expand=1, linear=0)
doc.close()

But, if I run 
mutools clean -g -gg -ggg -d -s - d -z 600mb.pdf out.pdf

I get file which is only 150mb and I dont know how to do it in pyMuPDF, which options shoud I use?

Kind regards;
Igor

**Comment by JorjMcKie** [comment]
Hi Igor,
amazing findings, indeed!
I looked at the C code of MuPDF. Specifying -ggg, -gg, -g multiple times should not change the overall effect of garbage collection, but it does! I used a 18.9 MB PDF and came down to 16.5 MB with ``-ggg -z -s``, and to 16.3 MB with ``-g -gg -ggg -z -s`` (this also happened with -ggg...g).

Deeper in the MuPDF code, the following checks are performed in this sequence when it comes to saving a PDF:

1. garbage >= 3: remove duplicate objects
2. garbage >= 2: compact xref

No check is being made how many more than 3 ``g`` options you specify.

The best result I can get with PyMuPDF is using ``doc.save(outfile, garbage = 3, clean = 1, deflate = 1)``. It is (at least) as good as anything I can get from mutool clean with all the examples I have been using.
Again, specifying ``garbage = 255`` is syntactically correct and (should) yield the same result.

I think your case is worth submitting to MuPDF's issue tracker. The question is whether you could put your mega PDF online for them to access ...?

**Comment by itatarevic** [comment]
Hi Jorj, 

Thank you for your quick answer. 

My huge file is created by merging large amount of more-or-less same files so it end up with lot of duplicate objects in pdf (same fonts and images).

It seems that -ggg does not remove duplicate objects, but -gggg does, same thing with pyMuPDF, garbage=4 removes duplicate objects.

I wrote little sample which merge 10 copies of PyMuPDF.pdf manual / documentation and then runs a cleaning process with different values of garabage param / number of g-s in mutool. Merged file is 11.75 MB big, file cleaned with garbage=3 is 11.24 MB and file with garbage=4 param is 5 MB!!!

Here is the code:

```
def test_g(file, copies=5, garbage=4):
    from pdfrw import PdfReader, PdfWriter
    import fitz
    import subprocess

    pdf_out = PdfWriter()
    for a in range(0, copies):
        pdf_in = PdfReader(file)
        pdf_out.addpages(pdf_in.pages)

    base_file = file.replace("pdf", "")
    combined_file = base_file + "copies_{0}".format(copies) + ".pdf"
    pdf_out.write(combined_file)

    for g in range (1, garbage + 1):
        shrinked_file_py = base_file + "g{0}.c1.d1.e1.py.pdf".format(g)
        shrinked_file_exe = base_file + "g{0}.c1.d1.e1.exe.pdf".format(g)

        doc = fitz.Document(combined_file)
        doc.save(filename=shrinked_file_py, garbage=g,  clean=1, deflate=1, expand=1)
        doc.close()

        args = ["mutool.exe", "clean", "-{0}".format("g" * g), "-s", "-d", "-z", combined_file, shrinked_file_exe]
        subprocess.call(args)
```

If you agree I will send this as issue to http://bugs.ghostscript.com/

**Comment by JorjMcKie** [comment]
Hi Igor,
interesting stuff! Thanks a lot for digging into this.
The MuPDF guys will of course only accept issues related to their stuff, i.e. mutool - not PyMuPDF.
So please do go ahead with that.
What I could do in the meantime as a quick solution is increasing the garbage parameter "behind the scenes". The logic could be: If garbage > 0 then add 1 to garbage.

**Comment by JorjMcKie** [comment]
Hi again,
I just tried other numbers for the garbage parameter in PyMuPDF:
It seems you have detected a larger issue (or even feature?) in MuPDF. Increasing the garbage parameter (or the ``-g`` option of mutool clean) keeps decreasing the output for at least two levels more. Meaning, sizes of garbage=5 are better than 4, 6 is better than 5.
Only 7 and up does not further shrink the output (in this example ...).
Garbage-collecting the 11.5 MB with ``garbage = 6+`` or ``-gggggg...`` yields a size of 2.84 MB.

@rk700 - I would like to get you in the loop here. Obviously MuPDF has an issue, at least in terms of documentation. We do not know **how** they react to the issue and **when**.
I would like to get PyMuPDF out of this somehow.

A solution coming to my mind is changing the garbage parameter from the numeric value range (0, 1, 2, 3) to a boolean parameter (True or False - 1 or 0).

This would mean: either you want to garbage-collect or you don't. If you do, then all the possible would be done (delete unused objects, join duplicates, clean up the xref). A sub-selection would no longer be possible (like delete the unused but keep the duplicates, etc.).
The API for current users would remain stable: anything other than ``garbage=0`` would automatically mean ``garbage = True``.

**Comment by itatarevic** [comment]
Hi Jorj, 

I have posted issue on muPDF tracker (http://bugs.ghostscript.com/show_bug.cgi?id=697194) and they commented that -gggg is normal behaviour.

They said they will change documentation.

Btw, I couldnt reproduce your results with 5 & 6  letter "g" nor with garbage param in pyMuPDF

Kind regards;
Igor

**Comment by JorjMcKie** [comment]
Thanks for the info. These MuPDF guys are amazing sometimes ...
I will try again what I told you. If it can be reconfirmed, I will expand your issue at MuPDF.

**Comment by JorjMcKie** [comment]
I could not re-create the situation either I mentioned earlier (5+ ``g`` options make any difference, etc.).

Artifex / MuPDF has already updated its documentation for ``mutool clean``:

Option `-gggg` means **"in addition to -ggg check streams for duplication"**.

I am updating our documentation accordingly.

Thanks again @itatarevic.
I am closing this issue now.
