### ISSUE TITLE
opening document from stream

### ISSUE THREAD

**Issue by itatarevic** [rk700/PyMuPDF#72]
Hi, 

As I wrote before - I have really huge file which is created by merging lot of similar pdf files into one big file. This file have lot of duplicate objects so I would like to clean it with PyMuPDF. 
Writing file onto disk and loading it in PyMuPDF works fine (with garbage = 4 param), but I would like to skip this writing / reading from disk and I tried to save file to stream and open that stream in PyMuPDF.

I was following sample from documentation but I am getting error "cannot load document 'application/pdf'. I am guessing that problem has something to do with fact that I am using Paython 3.5 and BytesIO stream :-(

Code:

```
def test_stream(file, copies=5, garbage=1):
    from pdfrw import PdfReader, PdfWriter
    from io import BytesIO
    import fitz
    import subprocess

    pdf_out = PdfWriter()
    for a in range(0, copies):
        pdf_in = PdfReader(file)
        pdf_out.addpages(pdf_in.pages)

    base_file = file[:-3]
    combined_file = base_file + "copies_{0}".format(copies) + ".pdf"
    s = BytesIO()
    pdf_out.write(s)

    for g in range (1, garbage + 1):
        shrinked_file_py = base_file + "g{0}.c1.d1.e1.py.pdf".format(g)

        doc = fitz.Document(filename="application/pdf", stream=s.getbuffer())
        doc.save(filename=shrinked_file_py, garbage=g,  clean=1, deflate=1, expand=1)
        doc.close()
```

Kind regards;
Igor

**Comment by JorjMcKie** [comment]
Depending on your platform, another option to concatenate PDFs temporarily in memory is using the [pdftk tool kit](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/) on Windows. It supports SYSOUT for output which could then be used as memory area input to PyMuPDF.

**Comment by itatarevic** [comment]
Hi Jorj, 

Thank you for your answer. 

I have changed procedure the way you proposed - merge is done by PyMuPDF instead of pdfrw :-)

Kind regards;
Igor

**Comment by JorjMcKie** [comment]
Great!
As I said - if you need help with concatenated tables of content, let me know.
Please close the issue if all is fine.
