### ISSUE TITLE
re-generate the PDF  only with standard non-embedded fonts

### ISSUE THREAD

**Issue by wanghaisheng** [rk700/PyMuPDF#73]
i got thousands of pdf files ,many of them have a few embedding fonts,can
i transform orginal pdf to a new one ,all the texts or characters are
using one of the 5 standard font families(Times, Helvetica, Courier,
Symbol and ZapfDingbats.)

these  original pdf files are coming from other places, which out of
my  control. if some character use a embedding font ,i want to render these
characters using  standard fonts  instead of embedding font

can  pymupdf do this kind thing?

**Comment by rk700** [comment]
AFAIK,  MuPDF cannot do that.

**Comment by JorjMcKie** [comment]
Sorry for the late reply - didn't see my comment was requested.

No, I have been digging a while in the library without success.

Meanwhile, we have rudimentary possiblities to update PDF objects directly via changing the "source code" of the PDF object definition - ``Document._updateObject(xref, obj_str)``.

I image a program could be written that scans through all object definitions (via the XREF using ``Document._getObjectString(xref)``), checks if an object is a font definition and whether it is a standard font. If not, then relplace that font with a related standard font definition.

Alternatively, checks for fonts on every page (see demo program) and replace any references to unwanted fonts directly by changing the page object source code.

@wanghaisheng  - please let me know if any of these ideas come close to what you want ...

**Comment by wanghaisheng** [comment]
@JorjMcKie the first one is  the one i have imagined

**Comment by JorjMcKie** [comment]
@wanghaisheng  - Had not heard from you quite some time, so I decided to close the issue.
# More detailed reasoning
I have done some investigation on this problem: there seems to be broad agreement in the PDF user arena: There simply is **no way** to do that automatically. At least in a way that lets the PDF afterwards look similar like before.
There are some solutions that work on a single file basis, but most of them imply costs. E.g. you can convert a PDF to MS Word and then edit the Word document as desired. Under Windows there exists a nice free program, AbleWord (http://www.ableword.net/downloads.html), that can do this. Probably you can use it on other operating systems as well if using WINE.

My "idea" from before would require a **lot of effort** to come anyway near to a solution.

So, for the time being, I have to say "sorry" :-(

**Comment by JorjMcKie** [comment]
hm, you keep me thinking about this ...

# Another wild high-level idea
* Do you really need your "thousands" of PDFs as PDF? If not, you could extract the text, page by page and store that in a trivial text file. This would be very easy to do. In fact, we have such a program already in the examples directory.
* If you absolutely need to maintain a PDF:
    * extract the text of each page with JSON or XML output option. These will give you positioning info either for a piece of text ("span") in case of JSON, or even for a single character position together with font information (!) in case of XML.
    * determine the image(s) on the page together with their positioning info (which we do not have currently)
    * use reportlab to rebuild the page in a new PDF using the info from above, but replacing unwanted fonts by other ones ...

**Comment by wanghaisheng** [comment]
thx for your advice.
these special pdf comes from external  systems  and what  i want is the data in them ,right now  the program to extract the information  we are using rely on pdf. what i do is to transform this pdf into json/html ,then re-organize the data  element .unfortunately some pdfs which have  embedding fonts but not the right fonts (for example ,some embedding font can't  express Chinese characters ).currently  i transform this kind pdf into image and using OCRMYpdf to transform  image into pdf

**Comment by JorjMcKie** [comment]
I see.

But I do not understand yet, how a font change to standard fonts would help you: If an embedded font does not support Chinese characters, then I guess this information is just not there in the PDF. And a change to a standard font would not re-create it, or would it?

Have you ever tried the text extraction methods of PyMuPDF? They do support Chinese characters, when they occur in the PDF. See this text file - it has been extracted from first PDF page of the "Beijing / Peking" article of the German Wikipedia with output format "plain text" chosen. Other options (JSON and XML) would present Chinese characters as their unicode codes ...
[page1.txt](https://github.com/rk700/PyMuPDF/files/661278/page1.txt)
