### ISSUE TITLE
ParseTable should support multilines cell

### ISSUE THREAD

**Issue by malaterre** [rk700/PyMuPDF#74]
It would make sense to have `ParseTable.py` handle multiline cells. For instance take page 59 of this [document](http://www.hitachimed.com/idc/groups/hitachimedical/documents/supportingdocumentpdf/poc_013216.pdf).

Using `TableExtract.py`, I get:

```
Attribute Name
||NaviInitialGatePosition |(0029,xx2c) ||DS |From Application |
||NaviFinalGatePosition |(0029,xx2d) ||DS |From Application |
||NaviAverageGatePosition |(0029,xx2e) ||DS |From Application |
||ImageAppData |(0029,xx2f) ||OB |From Application |
||DiffusionBValue |(0029,xx30) ||FD |The value is same as Diffusion b-value |
||||||of MR Diffusion Macro |

```

while I would have expected something like:

```
Attribute Name
||NaviInitialGatePosition |(0029,xx2c) ||DS |From Application |
||NaviFinalGatePosition |(0029,xx2d) ||DS |From Application |
||NaviAverageGatePosition |(0029,xx2e) ||DS |From Application |
||ImageAppData |(0029,xx2f) ||OB |From Application |
||DiffusionBValue |(0029,xx30) ||FD |The value is same as Diffusion b-value \n of MR Diffusion Macro|
```

**Comment by JorjMcKie** [comment]
Table extraction from documents actually is a quite complex matter. To my knowledge, there is no satisfactory solution on the market - not even a commercial one.

Most of the complexity comes from the fact, that most tables (in PDFs) are coded just as normal text pieces ("spans") with position information - not as "tables" per se (we are not talking about images or embedded documents here).

In my example application, I am therefore forced to use some type of "intelligence" to map an unstructured collection of text spans to a table-like structure. This is how far this logic goes currently:

1. **Rows:** "spans" are one hierarchy level below "lines". So I replace the vertical position of each span with that of its line (this takes care of e.g. subscripts and superscripts) to define table rows.
2. **Columns:** I either accept each left horizontal value of spans as the start of a new column, or I take a parameter-provided list of column starts to find the right column for each span.

That said, I cannot think of a stable and reliable way recognizing that (in your example) text span "``of MR Diffusion Macro``" actually belongs to the table cell above and should not be part of a new table row.

BTW: the many table columns you are getting originate from my above point 1: the table header has centered title spans, therefore they each define a column by its left coordinate, while the rest of the table cells look quite decently left aligned.

If you use the "wxTableExtract.py" program (or if you provide a list of integer pixel values as column left borders), you can control the number of columns generated.

**Comment by malaterre** [comment]
I understand. Closing as invalid.
