### ISSUE TITLE
> 1.0GB memory usage

### ISSUE THREAD

**Issue by mozbugbox** [rk700/PyMuPDF#76]
When my mupdf app open a largish (>100MB) PDF file with full of images, like a scanned book/magazine, the memory consumption can grow up to over > 1GB. That's just too much for a single file.

From [Embedding MuPDF doc](http://twiki.ghostscript.com/do/view/MuPDF/EmbeddingMuPDF) and [content.h](http://mupdf.com/docs/browse/include/mupdf/fitz/context.h#135), it seems that PyMuPDF was using the unlimited cache store to open the fz_context. unlimited cache store basically keeps all the cache as long as there are available memory on the system. 

I hope the default 256MB cache store was used instead or an interface was provided to change the cache store a fz_context opened with.

**Comment by JorjMcKie** [comment]
I am certainly volunteering to implement such an interface. 
But I want to confirm your consent on this, @rk700.
Maybe, limiting the ctx would be the best, otherwise, an API or installation procedure changes are inevitable.

I never did a formal investigation on how much memory is used, when certain coding guidelines are being observed.

When I ran into memory issues, I was usually able to fix these by freeing large memory consumers as early as ever possible. These are typically pixmaps - they consume space for every image in uncompressed ``width x height x pixelsize`` chunks. But also Page objects and can get memory hogs.

**Comment by rk700** [comment]
Yes I agree that limiting the cache size would be the best. So @mozbugbox could you please try replacing `FZ_STORE_UNLIMITED` with `FZ_STORE_DEFAULT` and monitor the memory usage on the same large PDF file?

**Comment by JorjMcKie** [comment]
@rk700 - I just did the test you suggested. These are the results:

**Input:**
test.pdf, a scanned-in book with 99 MB, 45 pages.

**Script:**
Walks through the file creating a pixmap for each page using a magnification factor of 3. This yields pixmap sizes of 18 MB.

    from __future__ import print_function
    import fitz, time
    doc = fitz.open("test.pdf")
    mat = fitz.Matrix(3, 3)
    t0 = time.clock()
    for i in range(len(doc)):
        pix = doc.getPagePixmap(i, matrix=mat)
        print("processing page", i)
        print("pixmap size", len(pix))
        pix = None
    t1 = time.clock()
    print("processing time", t1-t0)
    x = raw_input("waiting: ")

**Observations for unlimited global context:**
1. Runtime 26 - 27 seconds
2. Memory size grows up to 1.6 GB (!!)

**Observations for defaulted global context:**
1. Runtime 26 - 27 seconds
2. Memory size grows up to 280 MB

So in effect, @mozbugbox has a very valid point here and I took the liberty to immediately create and upload a new version with default global context size.

Please download at your discretion and let me know any further issues. Such issues might arise when several documents are being processing in parallel - though I doubt we will really see them ...

Awaiting your feedback.

**Comment by JorjMcKie** [comment]
I have repeated the above tests with Python 3 (3.5 and 3.6) versions on x64 Windows.

Results are very similar and underpin the statements above. Limiting global context size is a justified, even necessary action and has so far not shown any visible effects on performance.

As a side remark: the above script runs almost 20% faster under Python 3.5 64bit ... 21.5 versus 26.5 seconds with Python 2.7 32bit ...

**Comment by rk700** [comment]
Great! I've also tested my application and no issues found up to now. Thank you @mozbugbox and @JorjMcKie for such a good point.

**Comment by JorjMcKie** [comment]
@mozbugbox - I suggest to close this for now. Your reaction?

**Comment by mozbugbox** [comment]
Sorry for the late reply and thanks for the fix.

I was struggling with another bug in my program that kept mem usage high. 

At the end, I was able to track it down to a Gtk related bug: (https://bugzilla.gnome.org/show_bug.cgi?id=774471). This bug kept all the pixbuf data of PDF page rendering through out my app. I was able to come up a work around finally.

@JorjMcKie Thanks you again!
