### ISSUE TITLE
MuPDF v1.10-rc1

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#77]
@rk700  - just want to let you know that I have started working on MuPDF v1.10.

While this is still a pre-release, we can expect the final one soon ...

This time, changes are quite significant! Some of them will have impact on the API we present to our users, for example the **linkDest class is completely gone** having big impact on ``outline`` and ``Link``.

The alpha channel in pixmaps is **now optional**, which also causes some impact on our API.

New configuration options allow us to reduce our binary size by about 50%.

I am preparing a write-up of the details for our Wiki.

Other than that, I am testing a PyMuPDF v1.10.0 and will soon publish it in a branch.

**Comment by rk700** [comment]
Great! Is there anything I can help?

**Comment by JorjMcKie** [comment]
Technically, I am fine so far.

I will come back with a few design decisions we have to make, though.

There are a few bugs in MuPDF v1.10-rc1. They have cut back link & outline destination information **very** much: we only can find out whether a destination is external or not, and even that does not work correctly yet. There is no information detail about where a link / outline exactly points to - just the page number, no target coordinates, no zoom information, etc. ... what do we want to do with this, etc.

And other things like that.

But let me put together a decision sheet. I also hope that the final release will improve things somewhat.

**Comment by JorjMcKie** [comment]
@rk700  - here is a document with a high level description of MuPDF v1.10 changes, and design decisions I am proposing in response to those changes. My suggestions are tick-marked for easy recognition.
Please have a look at them and let me know what you think.
Overall, I am a little disappointed with this new release:
* the memory savings are fine and so is a cleaner code at various places
* easier and more complete handling of annotations is good news, too
* but the loss of functionality in the area of links / destinations is a bitter pill.

[v110-changes.pdf](https://github.com/rk700/PyMuPDF/files/595925/v110-changes.pdf)

**Comment by rk700** [comment]
Looks good to me. Do we need to remove class `linkDest` and add the interpreted information in `Link` and `Outline`?

**Comment by JorjMcKie** [comment]
I think so, yes. This is because literally nothing is left from linkDest: `dest`, `fileSpec`, `flags`, `isMap`, `isUri`, `kind`, `lt`, `named`, `newWindow`, `page`, `rb `are all gone and cannot be reconstructed from the information that is still there (just `uri`), or at least for the most part. And `uri `is now a part of `Link`.

And wouldn't it be problematic in the long term to have a PyMuPDF class with no counterpart on the MuPDF side?

But let's go through this in some more detail, because you are the one to decide this:
`dest`:  **cannot** be reconstructed, could set to always empty
`isMap`: **cannot** be reconstructed, could be set to always `False`
`newWindow`: **cannot** be reconstructed, could be set to always `False`
`lt`: **cannot** be reconstructed, could be set to always `0`
`rb`: **cannot** be reconstructed, could be set to always `0`
`named`: **cannot** be reconstructed for external links, could be set to always empty
`flags`: **cannot** be reconstructed, could be set to always `0`
`page`: exists for internal links. Could be reconstructed for external from trailing `#n`, but only works for PDF
`fileSpec`: can be reconstructed from uri (with some uncertainty - still buggy in MuPDF)
`isUri`: can be reconstructed from uri (with some uncertainty - still buggy in MuPDF)
`kind`: can be reconstructed (with mentioned uncertainties for external)

Also note that all the names  for `kind `and `flags` (`LINK_GOTOR`, `LINK_LAUNCH`, etc. and all `LINK_FLAG_*`) are no longer contained in MuPDF and would therefore have to be maintained by us in PyMuPDF.

So my feelings are:
We can construct a `linkDest` (on the PyMuPDF side only), to maintain low v1.10 impact for our current users, though it would be full of default values (8 out of 12 properties).

It may be, that other members of the MuPDF community voice enough complaints (I have seen a few), such that link information is enriched again at some time ...

**Comment by JorjMcKie** [comment]
After thinking about your hesitant reaction concerning `linkDest`, I decided to create our own new `linkDest` class in PyMuPDF 1.10.0.

It does have the above mentioned drawbacks (2/3 of the properties are meaningless), but it also has advantages: old code dealing with Links and Outlines won't break!

This is especially true for my own code in `getToC`, `setToC` and `insertPDF`: they all run immediately with the new version ...

Whenever MuPDF should decide to enrich their link information again, we have a single place where to adjust our stuff.

@rk700 - If you do not have other remarks, I will continue developing PyMuPDF v1.10.0.

There are places worthwhile spending effort: The new version will contain significant enhancements around annotations.

**Comment by rk700** [comment]
Nice. So let's keep it for backward compatibility.

Thank you!

**Comment by JorjMcKie** [comment]
As if we had had a premonition: the second release candidate, MuPDF v1.10-rc2 is out ... guess what:
They have extended the link information in the uri: 

* It now has the form `#n,x,y` for internal links, where as before `#n` is the 1-based page number and the other two mean target destination coordinates in pixels - IAW the `fitz.Point` information we need for `linkDest.lt`.
* For external links to PDF files only, `uri` may now include the suffix `#page=n` to specify a destination 1-based page number. So we can differentiate again between `LAUNCH` and `GOTOR`.

**Comment by rk700** [comment]
Great. So that's almost all we need.

**Comment by JorjMcKie** [comment]
The final v1.10a (includes a small bug fix) is out since 2016-11-28. Nothing has changed concerning links compared to my last post.
I have finalized a preliminary PyMuPDF v1.10.0 and opened a new branch for it. 
I suggest to make the new release out of v1.10.0 (and not **release** v1.9.3 separately - it should stay in its branch however).
Version 1.10.0 contains many new features around annotations: they can be accessed much like links and all their characteristics can be interrogated. In addition pixmaps can be created from them. I have also added methods to **change** annotations: one can for example update the information dictionary und the rectangle (i.e. move an annotation around on its page and change its size).
The following is a simple example that displays some info and changes the author for all annotations of page 1 and shrinks them by 20% vertically:

    doc = fitz.open("test.pdf")
    matrix = fitz.Matrix(1, 0.8)
    page = doc[0]
    annot = page.firstAnnot
    while annot:
        print(annot.type, annot.lineEnds)
        m = annot.info
        m["title"] = "Jorj X. McKie"
        annot.setInfo(m)
        r = annot.rect
        r = r * matrix
        annot.setRect(r)
        annot = annot.next
    doc.saveInr() # do an incremental save
Please have a look if you find the time and let me know what you think (and of course any issues ...).

A technical issue I am still having:
When I change an annotation (different border thickness, colors, text, line end styles etc.), these changes work and are correctly stored in the PDF, but the appearance **does not change!** 
The exception to that is changing the rectangle: this does change how the annotation looks like.
Any idea? I know, I should change the content of the `/AP` entry of the annotation object, but I don't know how to do that ...

**Comment by rk700** [comment]
Is https://github.com/rk700/PyMuPDF/issues/60 related to this one? It seems that we can edit annotations in v1.10, though the appearance doesn't change immediately.

And how about re-runing the page after editing?

**Comment by JorjMcKie** [comment]
"Yes" to both of your questions ...
1. The whole effort with annotations goes back to the request in #60 by @mozbugbox. And I believe, I have come far with responding to it: It is possible now to extract the most interesting information from annotations, including creating pixmaps. Any comments, @mozbugbox? Can we close #60?
2. **Changing** annotations turns out to be a quite complex task. While it is fairly easy to change many of the annotation's attributes in its defining PDF object (which I have mostly finished), creating a full-blown annotation editor is **really** hard. I don't want to do that ... at this moment.

The /AP entry in an annotation references objects that control the **N** (normal), **R** (rollover) and **D** (down) appearances. The issue I mentioned above obviously has the reason, that any changes done to the **annotation** object do not change the **N** appearance object. Therefore, any color, border, ... changes do not show in normal appearance, but they do when the annotation is clicked with a suitable PDF viewer software. Also, any of my textual changes ("content", "subject", "title" (=author), "creationDate", "modDate") do appear in the annotation's popup.

So in wrapping up, I guess I need to find a way to modify the appearance object referenced under **N** in the /AP dictionary ...

**Comment by JorjMcKie** [comment]
# Update
As I suspected: the key to having annotation images react to changes made in the annotation object, lies in modifying the formXObject(s) referenced by the annotation's **/AP** dictionary. The xobject is referenced by an annotation's **annot->ap**, whose PDF object **annot->ap->obj** contains a (compressed) stream of PDF operators (an PDF-specific mini-language) that describe what graphically should happen.

The PDF operator syntax is very low-level, but powerful.

# Implemented Annotation Change Support
I am going to implement support for **border and color changes only** as a first step. If any changes to general or fill colors were made, or border width was changed, these modifications can be copied into the annotation's image by a calling the new method **updateImage()**. This method will read the current state of color and border values from the annotation object and modify the annotation's **/AP** accordingly. As a result of this, re-running the page will show a changed annotation image.

**Comment by rk700** [comment]
Done. The master branch is up-to-date with 1.10.0 now.
