### ISSUE TITLE
Unable to install on linux; no "fitz.h" file present.

### ISSUE THREAD

**Issue by somu1795** [rk700/PyMuPDF#78]
I'm unable to install using "python setup.py install" since during compilation a file required "fitz.h" is not present in the repository!

**Comment by JorjMcKie** [comment]
This sounds like you do not have MuPDF on your machine (or its location is not correctly specified in your `setup.py`). File `fitz.h` is part of it and can be found in directory `mupdf/include/mupdf`.

**Comment by JorjMcKie** [comment]
@somu1795 - out of curiosity: is your issue solved now? Do you need more help?
Please otherwise close the issue or have me close it for you.

**Comment by MartinThoma** [comment]
On Ubunut: `sudo apt-get install libmupdf-dev`
