### ISSUE TITLE
Function doc.setTOC( ) didn't work

### ISSUE THREAD

**Issue by sheldon66** [rk700/PyMuPDF#80]
Hi guys, need your help. There is a problem while using setTOC() to create table of contents for a pdf file. The setTOC function return the number of items I have added. Then I use getTOC() to get the file's TOC, it will work. But when I use PDF viewer to actually view the PDF file, the TOC is still missing. 
The file download link: https://www.jianguoyun.com/p/DfLEFC0QouCYBhjxqiM
![screen shot 2016-12-18 at 3 24 39 pm](https://cloud.githubusercontent.com/assets/13678642/21292173/2cf48d18-c536-11e6-8fb9-c07cc0318b0a.png)

**Comment by JorjMcKie** [comment]
looks awkward ... I am just downloading the file. I'll let you know what I can find out.

**Comment by JorjMcKie** [comment]
@sheldon66 I just have worked a bit with your PDF, added a few lines of TOC, saved it, etc.
All worked fine. See the screen print ...

![resulting-pdf](https://cloud.githubusercontent.com/assets/8290722/21292962/76b1d63a-c4ec-11e6-8860-af5210768c19.PNG)

Can you send me the complete script you were using?

**Comment by sheldon66** [comment]
I use your document PyMuPDF.pdf to test. There is my code:
```
import fitz
doc = fitz.open('./PyMuPDF.pdf')
test_TOC = [[1, 'title', 1],[1, 'preface', 2]]
doc.setToC(test_TOC)
doc.getToC()
doc.save('PyMuPDF2.pdf')
doc.close()
```
And extract the TOC:
```
doc = fitz.open('./PyMuPDF2.pdf')
doc.getToC()

output:
[[1, 'title', 1], [1, 'preface', 2]]
```
And the screen Shot:
![screen shot 2016-12-18 at 6 50 36 pm](https://cloud.githubusercontent.com/assets/13678642/21293016/00a683ca-c553-11e6-9d57-314c828b45c1.png)

**Comment by sheldon66** [comment]
@JorjMcKie  Could you show me your code? Maybe I use the setToC( ) in the wrong way...

**Comment by sheldon66** [comment]
@JorjMcKie I think I find the answer. I forgot the parameter garbage of save( ). My new code there:
```
import fitz
doc = fitz.open('./PyMuPDF.pdf')
test_TOC = [[1, 'title', 1],[1, 'preface', 2]]
doc.setToC(test_TOC)
doc.save('PyMuPDF2.pdf', garbage = 4)
doc.close()
```
It finally worked!!! My goal is to repairing the ToC of this book. Now it's done. I'm very happy.  Thank you! !!!

**Comment by JorjMcKie** [comment]
This is weird. Did you have a look at the output PDF with a line or hex editor? To see whether the bookmark entries are really there?
It would probably be easier to do an incremental save: then the new TOC entries are at the end of the file together with the other changes.
But see what happened on my computer.
Script:
[test.txt](https://github.com/rk700/PyMuPDF/files/659374/test.txt)
Screen print after running it:
![test](https://cloud.githubusercontent.com/assets/8290722/21293104/f2e26fa4-c4f0-11e6-842c-d95a3aa50adf.png)

**Comment by JorjMcKie** [comment]
Good to hear that!
Though, actually, ... the garbage parameter just optimizes the file. Omitting it should not prevent you from seeing your new TOC.
Anyway - have fun with PyMuPDF!
BTW: have you tried the PDFoutline.py script? It only works with wxPython, but otherwise should help you a lot.

**Comment by JorjMcKie** [comment]
@sheldon66 
Is the following what you are looking for (more or less)?
[toc.txt](https://github.com/rk700/PyMuPDF/files/659426/toc.txt)

**Comment by sheldon66** [comment]
Yes, and I have add it to the database book. If the parameter garbage is not the point, then I don't know why. But the garbage seemed to solve the problem.
