### ISSUE TITLE
Installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by gileadslostson** [rk700/PyMuPDF#81]
I installed MuPDF on Ubuntu 16.04 using `ppa:ubuntuhandbook1/apps` and managed to install PyMuPDF. When I try to import `fitz` in the interpreter, however, I get `ImportError: No module named _fitz`.

Have I missed something obvious?

**Comment by JorjMcKie** [comment]
Are you sure you have compatible versions of MuPDF and PyMuPDF?
I.e. MuPDF = v1.10a and PyMuPDF = v1.10.0?
Otherwise I am not a Linux guy, but Iam sure @rk700 will respond soon - he is, and he knows which MuPDF versions arer available from Linux software databases.

**Comment by gileadslostson** [comment]
Thanks for the reply!

Definitely the right versions (I went searching to make sure). I have it working on windows 10 with no problems.

Fitz shows up installed in pip but I can't import it.

**Comment by JorjMcKie** [comment]
Just as a matter of interest: did you use the binaries repo for Windows 10?

In order to shorten turnaround time when @rk700 is stepping in: Could you please post an installation protocol for your Ubuntu installation? He should be able to see any (probable) library problem with this in hand ...

**Comment by gileadslostson** [comment]
I used the binaries for Windows 10. It was extremely quick and simple. Cheers!

And sorry, but I am fairly new to Linux. Is the protocol something generated or do you mean the steps I took?

**Comment by rk700** [comment]
@gileadslostson, it seems that the PyMuPDF module is not found in the python library path. Could you please take a look at the directory(something like `/usr/lib/<your python>/site-packages/`) and see if the module `fitz` is there?

**Comment by gileadslostson** [comment]
Yup, it's there 
![image](https://cloud.githubusercontent.com/assets/698090/21448645/503931b8-c8e5-11e6-987e-2af705f2c3f2.png)

**Comment by rk700** [comment]
Hmm, then what files are in that directory? Is `_fitz.so` there?

And could you please show me the whole exception info as well as the python version?

**Comment by gileadslostson** [comment]
Ok, this is strange. I am now getting a completely different exception. (Previously is was that there was no module __fitz):
![image](https://cloud.githubusercontent.com/assets/698090/21448837/3e6b0a36-c8e7-11e6-90e2-a0038d1cc216.png)

You can see the path in the image.

**Comment by gileadslostson** [comment]
No `_fitz.so` but there is `_fitz.cpython-35m-x86_64-linux-gnu.so`

**Comment by rk700** [comment]
OK, so the `.so` library can be located, though something went wrong when importing that library. Actually I'm not quite sure why the library name differs, but it would be fine as long as the module not found exception doesn't happen again.

Now let's focus on the symbol issue. It complains that `fz_identity` could not be found, which is defined in `MuPDF`'s libraries. In PyMuPDF's `setup.py` file, we told the compiler where to find those libraries and their names by `library_dirs` and `libraries`. So first please make sure that the libraries are properly installed(package like `libmupdf`), and then make sure that the library path and names are correctly set in the `setup.py`.

A quick experiment may be take a look at the `.so` file size. Usually it should be around 20-30MB.

**Comment by gileadslostson** [comment]
I don't have `libmupdf`.

The `setup.py` looks like this (I have commented and uncommented libraries various times trying different combinations):
![image](https://cloud.githubusercontent.com/assets/698090/21449432/89d56d1c-c8ed-11e6-9031-689a721e2d0b.png)

**Comment by gileadslostson** [comment]
Oh and I figured out why I was getting the `no module...` error. I needed to deactivate the virtualenv, or open another shell, before trying to import it.

**Comment by rk700** [comment]
All right, then I think it's the missing `libmupdf` that results in the exception. I'm not familiar with  Ubuntu, but I guess the package has a name `libmupdf-dev_1.10a-0build1~ubuntu16.04_amd64.deb` after I did a little search: https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/apps/+packages?field.name_filter=mupdf&field.status_filter=published&field.series_filter=

After installing it, please check `/usr/lib/mupdf` or `/usr/local/lib/mupdf` and see if the MuPDF libraries are there. Then put the directory path in `library_dirs` accordingly and build again.

**Comment by gileadslostson** [comment]
It was already installed, I didn't check for libmupdf-dev, sorry!

In `/usr/lib/mupdf` the only file is `mupdf-x11` and in `/usr/local/lib/mupdf` only `python2.7/` and `python3.5/`.

`libmupdf.a` is under `/usr/lib`

**Comment by rk700** [comment]
Can you find these 2 files?
1. /usr/lib/libmupdf.a
2. /usr/lib/libmupdfthird.a

If so, then update `setup.py` as follows:
```
library_dirs=['/usr/lib']
libraries=['mupdf', 'mupdfthird']
```
Then build and install PyMuPDF again.

If the problem persists, please run `readelf -s _fitz.so |  grep fz_identity` and see what the output is.

**Comment by gileadslostson** [comment]
Still the same, sorry. Here's the output:
![image](https://cloud.githubusercontent.com/assets/698090/21450751/da415570-c8f9-11e6-8df1-8464b9fd6faf.png)

**Comment by rk700** [comment]
@gileadslostson @JorjMcKie Last night I tried on my Linux machine and got the same error with python3.5. I'll take a deeper look at the recent commits and try to find out the reason.

**Comment by rk700** [comment]
@gileadslostson Could you please take the following steps?
1. Compare the two `.so` files, `Fitz.so` and `_fitz.so`. Are these two the same?
2. Get the size of the `_fitz.so`. Is it small?
3. run `readelf -s _fitz.so > symbols.txt` and upload the `symbols.txt`
4. Remove the `build` directory under PyMuPDF and run `python setup.py build` again. Then post the output during building.

These would be really helpful. Thanks.

**Comment by gileadslostson** [comment]
I will do but it probably won't be until Monday if that's ok? I'll try and get it done today though.

**Comment by gileadslostson** [comment]
Really sorry! I have been off ill. I will get to this today!

**Comment by gileadslostson** [comment]
Ok, 
    1. The files differ but have the same size - 760kb
    2. See 1
    3. [symbols.txt](https://github.com/rk700/PyMuPDF/files/680476/symbols.txt)
    4. When running `build` I got an error. [error.txt](https://github.com/rk700/PyMuPDF/files/680477/error.txt)

Sorry and thanks for your help!

**Comment by rk700** [comment]
The `.so` file is small and there are lots of undefined symbols(UND), therefore `_fitz.so` is not linked properly.

According to error.txt, the failure happens when building for Python 2.7 instead of Python 3.5(`... -o build/lib.linux-x86_64-2.7/fitz/_fitz.so`). So is it another issue? 

Also the error info is not included in error.txt. Could you please provide some more details?

**Comment by gileadslostson** [comment]
Sorry about that, I just wrote the output to file.

I was looking at it though and it seems the error might come from a problem with how I compiled something. It states that I should `recompile with -fPIC` but I am not sure what. (Sorry again!)

Here is the full output for `build`:
`running build
running build_py
creating build
creating build/lib.linux-x86_64-3.5
creating build/lib.linux-x86_64-3.5/fitz
copying fitz/__init__.py -> build/lib.linux-x86_64-3.5/fitz
copying fitz/fitz.py -> build/lib.linux-x86_64-3.5/fitz
copying fitz/utils.py -> build/lib.linux-x86_64-3.5/fitz
running build_ext
building 'fitz._fitz' extension
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/fitz
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/mupdf -I/usr/local/thirdparty/zlib -I/usr/include/python3.5m -I/home/marc/.virtualenvs/mupdfenv/include/python3.5m -c fitz/fitz_wrap.c -o build/temp.linux-x86_64-3.5/fitz/fitz_wrap.o
fitz/fitz_wrap.c: In function ‘getPDFstr’:
fitz/fitz_wrap.c:3163:42: warning: passing argument 2 of ‘PyBytes_AsStringAndSize’ from incompatible pointer type [-Wincompatible-pointer-types]
         ok = PyBytes_AsStringAndSize(me, &nc, psize);
                                          ^
In file included from /usr/include/python3.5m/Python.h:76:0,
                 from fitz/fitz_wrap.c:149:
/usr/include/python3.5m/bytesobject.h:89:17: note: expected ‘char **’ but argument is of type ‘unsigned char **’
 PyAPI_FUNC(int) PyBytes_AsStringAndSize(
                 ^
fitz/fitz_wrap.c:3172:42: warning: pointer targets in passing argument 1 of ‘PyUnicode_FromStringAndSize’ differ in signedness [-Wpointer-sign]
         me = PyUnicode_FromStringAndSize(nc, *psize);      // assumes nc is UTF
                                          ^
In file included from /usr/include/python3.5m/Python.h:77:0,
                 from fitz/fitz_wrap.c:149:
/usr/include/python3.5m/unicodeobject.h:711:23: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
 PyAPI_FUNC(PyObject*) PyUnicode_FromStringAndSize(
                       ^
fitz/fitz_wrap.c:3185:38: warning: passing argument 2 of ‘PyBytes_AsStringAndSize’ from incompatible pointer type [-Wincompatible-pointer-types]
     ok = PyBytes_AsStringAndSize(uc, &nc, psize);
                                      ^
In file included from /usr/include/python3.5m/Python.h:76:0,
                 from fitz/fitz_wrap.c:149:
/usr/include/python3.5m/bytesobject.h:89:17: note: expected ‘char **’ but argument is of type ‘unsigned char **’
 PyAPI_FUNC(int) PyBytes_AsStringAndSize(
                 ^
fitz/fitz_wrap.c:3215:30: warning: pointer targets in return differ in signedness [-Wpointer-sign]
     if (have_uc == 1) return nc;            // have large code points: done
                              ^
fitz/fitz_wrap.c:3225:12: warning: pointer targets in return differ in signedness [-Wpointer-sign]
     return nc;
            ^
fitz/fitz_wrap.c: In function ‘page_merge’:
fitz/fitz_wrap.c:3337:40: warning: unused variable ‘subt’ [-Wunused-variable]
     pdf_obj *obj = NULL, *ref = NULL, *subt = NULL;
                                        ^
fitz/fitz_wrap.c: In function ‘retainpages’:
fitz/fitz_wrap.c:3709:9: warning: unused variable ‘argidx’ [-Wunused-variable]
     int argidx = 0;
         ^
fitz/fitz_wrap.c: In function ‘new_fz_document_s’:
fitz/fitz_wrap.c:4171:49: warning: pointer targets in passing argument 2 of ‘fz_open_memory’ differ in signedness [-Wpointer-sign]
                     data = fz_open_memory(gctx, streamdata, streamlen);
                                                 ^
In file included from /usr/include/mupdf/fitz.h:26:0,
                 from fitz/fitz_wrap.c:3034:
/usr/include/mupdf/fitz/stream.h:71:12: note: expected ‘unsigned char *’ but argument is of type ‘char *’
 fz_stream *fz_open_memory(fz_context *ctx, unsigned char *data, size_t len);
            ^
fitz/fitz_wrap.c: In function ‘fz_document_s_write’:
fitz/fitz_wrap.c:4512:51: warning: pointer targets in passing argument 1 of ‘PyByteArray_FromStringAndSize’ differ in signedness [-Wpointer-sign]
                 r = PyByteArray_FromStringAndSize(c, len);
                                                   ^
In file included from /usr/include/python3.5m/Python.h:75:0,
                 from fitz/fitz_wrap.c:149:
/usr/include/python3.5m/bytearrayobject.h:44:24: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
 PyAPI_FUNC(PyObject *) PyByteArray_FromStringAndSize(const char *, Py_ssize_t);
                        ^
fitz/fitz_wrap.c: In function ‘fz_document_s__readPageText’:
fitz/fitz_wrap.c:4717:21: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
                 res = readPageText(page, output);
                     ^
fitz/fitz_wrap.c: In function ‘fz_document_s__getXrefStream’:
fitz/fitz_wrap.c:5056:47: warning: pointer targets in passing argument 1 of ‘PyBytes_FromStringAndSize’ differ in signedness [-Wpointer-sign]
                 r = PyBytes_FromStringAndSize(c, len);
                                               ^
In file included from /usr/include/python3.5m/Python.h:76:0,
                 from fitz/fitz_wrap.c:149:
/usr/include/python3.5m/bytesobject.h:51:24: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
 PyAPI_FUNC(PyObject *) PyBytes_FromStringAndSize(const char *, Py_ssize_t);
                        ^
fitz/fitz_wrap.c: In function ‘fz_page_s__readPageText’:
fitz/fitz_wrap.c:5176:30: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
             fz_try(gctx) res = readPageText(self, output);
                              ^
fitz/fitz_wrap.c: In function ‘new_fz_pixmap_s__SWIG_2’:
fitz/fitz_wrap.c:5370:77: warning: pointer targets in passing argument 7 of ‘fz_new_pixmap_with_data’ differ in signedness [-Wpointer-sign]
              pm = fz_new_pixmap_with_data(gctx, cs, w, h, alpha, stride, data);
                                                                          ^
In file included from /usr/include/mupdf/fitz.h:35:0,
                 from fitz/fitz_wrap.c:3034:
/usr/include/mupdf/fitz/pixmap.h:102:12: note: expected ‘unsigned char *’ but argument is of type ‘char *’
 fz_pixmap *fz_new_pixmap_with_data(fz_context *ctx, fz_colorspace *colorspace, 
            ^
fitz/fitz_wrap.c: In function ‘new_fz_pixmap_s__SWIG_4’:
fitz/fitz_wrap.c:5411:52: warning: pointer targets in passing argument 2 of ‘fz_new_image_from_data’ differ in signedness [-Wpointer-sign]
                 img = fz_new_image_from_data(gctx, data, size);
                                                    ^
In file included from /usr/include/mupdf/fitz.h:38:0,
                 from fitz/fitz_wrap.c:3034:
/usr/include/mupdf/fitz/image.h:81:11: note: expected ‘unsigned char *’ but argument is of type ‘char *’
 fz_image *fz_new_image_from_data(fz_context *ctx, unsigned char *data, size_t l
           ^
fitz/fitz_wrap.c: In function ‘fz_pixmap_s_getPNGData’:
fitz/fitz_wrap.c:5514:51: warning: pointer targets in passing argument 1 of ‘PyByteArray_FromStringAndSize’ differ in signedness [-Wpointer-sign]
                 r = PyByteArray_FromStringAndSize(c, len);
                                                   ^
In file included from /usr/include/python3.5m/Python.h:75:0,
                 from fitz/fitz_wrap.c:149:
/usr/include/python3.5m/bytearrayobject.h:44:24: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
 PyAPI_FUNC(PyObject *) PyByteArray_FromStringAndSize(const char *, Py_ssize_t);
                        ^
fitz/fitz_wrap.c: In function ‘fz_annot_s__getAP’:
fitz/fitz_wrap.c:5761:47: warning: pointer targets in passing argument 1 of ‘PyBytes_FromStringAndSize’ differ in signedness [-Wpointer-sign]
                 r = PyBytes_FromStringAndSize(c, (Py_ssize_t) len);
                                               ^
In file included from /usr/include/python3.5m/Python.h:76:0,
                 from fitz/fitz_wrap.c:149:
/usr/include/python3.5m/bytesobject.h:51:24: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
 PyAPI_FUNC(PyObject *) PyBytes_FromStringAndSize(const char *, Py_ssize_t);
                        ^
fitz/fitz_wrap.c: In function ‘fz_annot_s__setAP’:
fitz/fitz_wrap.c:5794:40: warning: pointer targets in passing argument 2 of ‘deflatebuf’ differ in signedness [-Wpointer-sign]
                 res = deflatebuf(gctx, c, (size_t) len);
                                        ^
fitz/fitz_wrap.c:3113:12: note: expected ‘unsigned char *’ but argument is of type ‘char *’
 fz_buffer *deflatebuf(fz_context *ctx, unsigned char *p, size_t n)
            ^
fitz/fitz_wrap.c: In function ‘fz_annot_s_setInfo’:
fitz/fitz_wrap.c:6033:24: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
                     uc = getPDFstr(value, &i, "content");
                        ^
fitz/fitz_wrap.c:6036:65: warning: pointer targets in passing argument 3 of ‘pdf_new_string’ differ in signedness [-Wpointer-sign]
                                       pdf_new_string(gctx, pdf, uc, i));
                                                                 ^
In file included from /usr/include/mupdf/pdf.h:11:0,
                 from fitz/fitz_wrap.c:3035:
/usr/include/mupdf/pdf/object.h:20:10: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
 pdf_obj *pdf_new_string(fz_context *ctx, pdf_document *doc, const char *str, si
          ^
fitz/fitz_wrap.c:6043:24: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
                     uc = getPDFstr(value, &i, "title");
                        ^
fitz/fitz_wrap.c:6046:65: warning: pointer targets in passing argument 3 of ‘pdf_new_string’ differ in signedness [-Wpointer-sign]
                                       pdf_new_string(gctx, pdf, uc, i));
                                                                 ^
In file included from /usr/include/mupdf/pdf.h:11:0,
                 from fitz/fitz_wrap.c:3035:
/usr/include/mupdf/pdf/object.h:20:10: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
 pdf_obj *pdf_new_string(fz_context *ctx, pdf_document *doc, const char *str, si
          ^
fitz/fitz_wrap.c:6053:24: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
                     uc = getPDFstr(value, &i, "creationDate");
                        ^
fitz/fitz_wrap.c:6056:66: warning: pointer targets in passing argument 3 of ‘pdf_new_string’ differ in signedness [-Wpointer-sign]
                                        pdf_new_string(gctx, pdf, uc, i));
                                                                  ^
In file included from /usr/include/mupdf/pdf.h:11:0,
                 from fitz/fitz_wrap.c:3035:
/usr/include/mupdf/pdf/object.h:20:10: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
 pdf_obj *pdf_new_string(fz_context *ctx, pdf_document *doc, const char *str, si
          ^
fitz/fitz_wrap.c:6063:24: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
                     uc = getPDFstr(value, &i, "modDate");
                        ^
fitz/fitz_wrap.c:6066:65: warning: pointer targets in passing argument 3 of ‘pdf_new_string’ differ in signedness [-Wpointer-sign]
                                       pdf_new_string(gctx, pdf, uc, i));
                                                                 ^
In file included from /usr/include/mupdf/pdf.h:11:0,
                 from fitz/fitz_wrap.c:3035:
/usr/include/mupdf/pdf/object.h:20:10: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
 pdf_obj *pdf_new_string(fz_context *ctx, pdf_document *doc, const char *str, si
          ^
fitz/fitz_wrap.c:6073:24: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
                     uc = getPDFstr(value, &i, "subject");
                        ^
fitz/fitz_wrap.c:6076:66: warning: pointer targets in passing argument 3 of ‘pdf_new_string’ differ in signedness [-Wpointer-sign]
                                        pdf_new_string(gctx, pdf, uc, i));
                                                                  ^
In file included from /usr/include/mupdf/pdf.h:11:0,
                 from fitz/fitz_wrap.c:3035:
/usr/include/mupdf/pdf/object.h:20:10: note: expected ‘const char *’ but argument is of type ‘unsigned char *’
 pdf_obj *pdf_new_string(fz_context *ctx, pdf_document *doc, const char *str, si
          ^
fitz/fitz_wrap.c: In function ‘fz_annot_s_border’:
fitz/fitz_wrap.c:6089:23: warning: unused variable ‘blank_py’ [-Wunused-variable]
             PyObject *blank_py = PyString_FromString("");
                       ^
fitz/fitz_wrap.c:6088:23: warning: unused variable ‘emptylst_py’ [-Wunused-variable]
             PyObject *emptylst_py = PyList_New(0);
                       ^
fitz/fitz_wrap.c: In function ‘fz_annot_s_getPixmap’:
fitz/fitz_wrap.c:6243:22: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
             else ctm = &fz_identity;
                      ^
fitz/fitz_wrap.c:6253:20: warning: ‘pix’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             return pix;
                    ^
fitz/fitz_wrap.c: In function ‘fz_document_s__getXrefStream’:
fitz/fitz_wrap.c:5059:20: warning: ‘r’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             return r;
                    ^
fitz/fitz_wrap.c: In function ‘fz_page_s__readPageText’:
fitz/fitz_wrap.c:5178:20: warning: ‘res’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             return res;
                    ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/fitz/fitz_wrap.o -lmupdf -lmupdfthird -o build/lib.linux-x86_64-3.5/fitz/_fitz.cpython-35m-x86_64-linux-gnu.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libmupdf.a(output.o): relocation R_X86_64_PC32 against undefined symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**Comment by rk700** [comment]
It says that the file `libmupdf.a(output.o)` is not compiled with `-fPIC`. This option instructs the compiler to generate position independent code(PIC), which is required by PyMuPDF.

Since the file `libmupdf.a` is provided by the packge `libmupdf-dev`, I think you'll have to uninstall it and compile MuPDF from source. By default, libmupdf.a is not compiled with `-fPIC` when building MuPDF, so it should be set explicitly:

```
cd <MuPDF source dir>
CFLAGS+=' -fPIC'
CXXFLAGS+=' -fPIC'
export CFLAGS CXXFLAGS
make build=release
```

After building MuPDF, run `make build=release prefix=/usr install` to install the header files and libraries. Then build PyMuPDF again and the libraries should be linked successfully.

**Comment by gileadslostson** [comment]
I'll try it either today or tomorrow depending on time.

And thank you, I really appreciate your patience.

**Comment by gileadslostson** [comment]
Still getting the `recompile with -fPIC` error. The `Makefile` for mupdf says that `CFLAGS` should not be set, rather `XCFLAGS` I tried that too but no luck.

Here is the end of the error output:
`x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/fitz/fitz_wrap.o -lmupdf -lmupdfthird -o build/lib.linux-x86_64-3.5/fitz/_fitz.cpython-35m-x86_64-linux-gnu.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libmupdf.a(buffer.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libmupdf.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**Comment by rk700** [comment]
Hmm, that' weird. Here's what I did:
1. Download MuPDF source code('https://mupdf.com/downloads/mupdf-1.10a-source.tar.gz) and unzip the archive
2. cd the MuPDF source dir and run `export XCFLAGS='-fPIC'`
3. run `make build=release` within the same terminal so that the env `XCFLAGS` is set.
4. run `make build=release prefix=/usr install` to install MuPDF
5. run `python setup.py build` to build PyMuPDF

There's no ld error in step 5. If I unset `XCFLAGS` and build MuPDF again, then there would be lots of ld errors complaining for `-fPIC` at step 5.

**Comment by gileadslostson** [comment]
I will try and remove everything again and build mupdf from the github repo. If that doesn't work I will try a fresh VM.

**Comment by gileadslostson** [comment]
I am now getting
`running build
running build_py
creating build
creating build/lib.linux-x86_64-3.5
creating build/lib.linux-x86_64-3.5/fitz
copying fitz/__init__.py -> build/lib.linux-x86_64-3.5/fitz
copying fitz/fitz.py -> build/lib.linux-x86_64-3.5/fitz
copying fitz/utils.py -> build/lib.linux-x86_64-3.5/fitz
running build_ext
building 'fitz._fitz' extension
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/fitz
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/include/mupdf -I/usr/local/thirdparty/zlib -I/usr/include/python3.5m -I/home/marc/.virtualenvs/mupdfenv/include/python3.5m -c fitz/fitz_wrap.c -o build/temp.linux-x86_64-3.5/fitz/fitz_wrap.o
In file included from fitz/fitz_wrap.c:3034:0:
/usr/lib/include/mupdf/fitz.h:8:32: fatal error: mupdf/fitz/version.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

The file `/usr/lib/include/mupdf/fitz.h` is there.

**Comment by rk700** [comment]
Usually the header files are in `/usr/include` instead of `/usr/lib/include`, so I think the `include_dirs` in setup.py should be something like `/usr/include/mupdf`. 

As of the file `/usr/lib/include/mupdf/fitz.h`, maybe it was copied there by mistake? You can take a look at `/usr/include/mupdf` and see if the header files are there.

**Comment by gileadslostson** [comment]
I am setting up a new VM just now. Once I have checked there I will go back and have a look and let you know.

**Comment by gileadslostson** [comment]
Ok, on the new machine I am once again getting:
`x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/fitz/fitz_wrap.o -lmupdf -lmupdfthird -o build/lib.linux-x86_64-3.5/fitz/_fitz.cpython-35m-x86_64-linux-gnu.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libmupdf.a(output-png.o): relocation R_X86_64_32 against '.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libmupdf.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1'

But mupdf is definitely compiled with `XCFLAGS=' -fPIC'. I am not using a virtualenv this time but still `python3.5.2`.

Also, if I try to build with `python2.7` it throws an exception immediately.

**Comment by gileadslostson** [comment]
I managed to get it installed after adding `-fPIC` directly to the `CFLAGS` in the `Makerules`. Setup seemed to work but still can't import `fitz`.

I tried to find it and it wasn't under `/usr/lib/python3.5` but rather
![image](https://cloud.githubusercontent.com/assets/698090/21640666/27393ce0-d277-11e6-8bad-26b072051f71.png)
So it would seem that, again, it isn't on the pythonpath. Could it be a problem with the python install?

**Comment by gileadslostson** [comment]
I have it working on `Ubuntu 16.10` with `python 3.5.2`.

I added `-fPIC` to `Makerules`, compiled then ran `setup.py build` and then `install`.

I must have made some stupid mistake on 16.04. I will keep looking for it and let you know if you want. Thank you for the help!

**Comment by JorjMcKie** [comment]
Congratulations!
I am sure @rk700 will agree that we always welcome experiences regarding PyMuPDF's installation on all the many platforms.

Why don't you create a little write-up in our Wiki? You should have access ...

So far, I am the only author there and I do feel a little lonely :-)

Please also close the issue once you are sure you are done.

**Comment by gileadslostson** [comment]
Thank you! I will try and write something this week.

**Comment by gileadslostson** [comment]
@JorjMcKie Just so you know, I haven't forgotten about the write-up! I need to setup on another server this week and I will write down the steps and explain the issues I had (even the stupid ones =D )

**Comment by JorjMcKie** [comment]
That's good ;-) ... thank you in advance, and I am hoping you otherwise enjoy working with the software.

If there is anything you would like to see in PyMuPDF - do not hesitate to submit an issue.

**Comment by gileadslostson** [comment]
Cheers! (And it is absolutely brilliant.)
