### ISSUE TITLE
Building with python 3.6

### ISSUE THREAD

**Issue by gileadslostson** [rk700/PyMuPDF#82]
When trying to build with `python 3.6` I get the following error:
![image](https://cloud.githubusercontent.com/assets/698090/21676069/988cfc16-d334-11e6-802f-f4ca973cae42.png)
It is a fresh clone of `PyMuPDF` and I have it installed in `python 3.5` on the same machine.

Bonus: when I try to install via a virtualenv running `3.6` using `python setup.py build` `setup.py` thinks I am using `2.7` for some reason:
![venvpy36_error](https://cloud.githubusercontent.com/assets/698090/21676198/0ade75ec-d335-11e6-9070-557cb9d2f11d.PNG)

**Comment by gileadslostson** [comment]
`Python.h` for `3.5` is in `/usr/include/python3.5m` and the only `python3.6m` is in `/usr/bin`

**Comment by JorjMcKie** [comment]
Obviously, it must be a problem with your Python 3.6 installation - not a PyMuPDF problem. As a shortcut you might want to specify the Python include dir explicitely in the setup,py script (option `include_dirs`) and see if it helps.

I am not sure if it is significant, but sometimes I am seeing `Python3.6m` as a dir name and sometimes a `Python3.6-m` ...

**Comment by gileadslostson** [comment]
Ok, I'll do that. Thanks.

**Comment by rk700** [comment]
Missing libpython3.6-dev: http://packages.ubuntu.com/yakkety/amd64/libpython3.6-dev/filelist

**Comment by gileadslostson** [comment]
@rk700 I should have thought of that! Thanks!
