### ISSUE TITLE
pymupdf installed ok but test.py got error

### ISSUE THREAD

**Issue by joylix** [rk700/PyMuPDF#84]
my system environment is Windows 7 professional  X64 with sp1,  I download pymupdf-1.10.0.0-py35-x64.zip and installed  pymupdf with no error,  but my simple file test.py (only one line:  import fitz) got error message like this:

C:\Users\Administrator\AppData\Local\Programs\Python\Python35\python.exe E:/pymupdf/examples/test.py
Traceback (most recent call last):
  File "E:\pymupdf\fitz\fitz.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "frozen importlib._bootstrap>", line 986, in _gcd_import
  File "frozen importlib._bootstrap>", line 969, in _find_and_load
  File "frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'fitz._fitz'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "E:/pymupdf/examples/test.py", line 1, in module>
    import fitz
  File "E:\pymupdf\fitz\__init__.py", line 2, in module>
    from fitz.fitz import *
  File "E:\pymupdf\fitz\fitz.py", line 17, in module>
    _fitz = swig_import_helper()
  File "E:\pymupdf\fitz\fitz.py", line 16, in swig_import_helper
    return importlib.import_module('_fitz')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_fitz'

I don't know what's the matter

**Comment by JorjMcKie** [comment]
Assuming everything went well with your Windows and Python installations, your problem probably indicates a mismatch with the Windows common runtime (CRT).

I am trying to prevent this by generating the `_fitz.pyd` binary as a self-contained file preventing the automatic inclusion of the standard runtime module (`/NODEFAULTLIB:MSVCRT` linker parameter). That should normally work (and it always has). I am certainly interested to know, when this still can go wrong.

In tracing down the error, please:
1. can you start  a command window and proceed exactly as indicated in my session below and provide me with the same image from your side. As you see, I am (successfully) doing there what your test script does.
2. is there anything special in your environment (Windows and / or Python)? Official Windows version? Virtual Python environment? Etc.
3. what does the generation time stamp of PyMuPDF say? This is `VersionDate` in line 101 of `fitz.py`.

![session](https://cloud.githubusercontent.com/assets/8290722/23162526/dd2b169c-f804-11e6-81ad-e8fb62847441.PNG)

**Comment by JorjMcKie** [comment]
As a reference you may want to look at issue #58. That is why I am suspecting you have a similar problem.

**Comment by JorjMcKie** [comment]
Looking again at your test run, I realized that `E:\pymupdf\fitz\fitz.py` was invoked as the PyMuPDF module. It should however be `C:\Users\Administrator\AppData\Local\Programs\Python\Python35\Lib\site-packages\fitz\fitz.py`.
You must not `import fitz` from the installation directory ... I think this is the problem ...

**Comment by JorjMcKie** [comment]
Hi @joylix - any news from your side? Were you able to fix your issue with the provided information?

**Comment by joylix** [comment]
Hi @JorjMcKie , I'am sorry to response late for a business trip.  
I just now change my  test.py to a new directory, not the installation directory, it really do work now!
think y

**Comment by joylix** [comment]
Hi @JorjMcKie , I'am sorry to response late for a business trip.
I just now change my test.py to a new directory, not the installation directory, it really do work now!
thank you very much for your help!

**Comment by JorjMcKie** [comment]
Your are welcome, glad to hear that. Enjoy PyMuPDF :-), and do not hesitate submit improvement or feature requests, or contributing to e.g. the Wiki.

I am closing this issue then.

**Comment by sunnek007** [comment]
Thank you for the quick respond. Actually I did't run the script in virtual environment. My system is Windows 7 X64. But I was running it in my company's computer. Maybe there is some IT restriction strategry policy running in the computer to cause this issue. Let me try it in my own computer later and feed back to you. thanks.
