### ISSUE TITLE
Low resolution of rasterised pages

### ISSUE THREAD

**Issue by jkeuskamp** [rk700/PyMuPDF#88]
Is it possible to influence the .dpi when rasterising pdfiles with PyMuPDF?

I have written something along the lines of:

```
doc = fitz.open(input_file)
page = doc.loadPage(page_number)
pix= page.getPixmap()
pix.writePNG("output.png")
```
This works fine, but generates a file with a very low resolution. 
While the command line version of MuPDF has an option to specify the resolution for rasterisation, 
I cannot find any equivalent specification in the PyMuPDF documentation.

**Comment by JorjMcKie** [comment]
I suppose you are referring to the `-r` parameter of `mutool draw`?
If you e.g. want to achieve the same result of `mutool draw -o <...> -r 150 ...`, 
define the following zoom matrix in PyMuPDF and render the pages with it:

    zoom = 150. / 72.
    mat = fitz.Matrix(zoom, zoom)
    ...
    pix = page.getPixmap(matrix = mat)

**Comment by JorjMcKie** [comment]
@jkeuskamp - did this tackle your problem?

**Comment by jkeuskamp** [comment]
Yes I did, I tried your solution today and it worked.
Thanks!
