### ISSUE TITLE
MuPDF 1.11

### ISSUE THREAD

**Issue by JorjMcKie** [rk700/PyMuPDF#89]
Hi PyMuPDF users,
as I mentioned in the [News Wiki](https://github.com/rk700/PyMuPDF/wiki/Change-and-News-Log), MuPDF published its new v1.11.
I have ported PyMuPDF to it, and successfully did some tests. So we are positioned to support that version already.
"Ported" means indeed, that our source must be changed (only a little bit though) to become compatible.
My question: How should we proceed here?
Background: per announcement, v1.11 is "mainly a bugfix release". But there is brand new support for PDF portfolios contained in it (PDF supporting incorporation of arbitrary other files - much like ZIP).

1. We could simply ignore v1.11 and wait for the next release
2. I could open a new branch to contain a v1.11.0 of PyMuPDF and step by step include portfolio functionality. But leave it in this branch for an indefinite time ... the reason for this is that anyone using PyMuPDF must get the right MuPDF version, too - and this is not always simple on the non-Windows platforms ...
3. The optional material repo (with its binaries for Windows) could step over to a v1.11.0 version without problem, because obviously it contains MuPDF.

Any opinion from your side?

**Comment by rk700** [comment]
I think it's not a must to export the PDF portfolio utility in PyMuPDF until someone really needs it.
