### ISSUE TITLE
Build failure - macOS Sierra 10.12.4

### ISSUE THREAD

**Issue by jtlz2** [rk700/PyMuPDF#94]
I can't get PyMuPDF to build:

cd PyMuPDF
sudo python setup.py build

running build
running build_py
running build_ext
building 'fitz._fitz' extension
gcc -fno-strict-aliasing -fno-common -dynamic -g -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include/mupdf -I/usr/local/include -I/Applications/Canopy.app/appdata/canopy-1.7.4.3348.macosx-x86_64/Canopy.app/Contents/include/python2.7 -c fitz/fitz_wrap.c -o build/temp.macosx-10.6-x86_64-2.7/fitz/fitz_wrap.o
fitz/fitz_wrap.c:3064:82: error: too few arguments to function call, expected 5,
      have 4
  ...= pdf_load_link_annots(gctx, page->doc, annots_arr, &page_ctm);
       ~~~~~~~~~~~~~~~~~~~~                                       ^
/usr/local/include/mupdf/pdf/annot.h:127:1: note: 'pdf_load_link_annots'
      declared here
fz_link *pdf_load_link_annots(fz_context *ctx, pdf_document *, pdf_obj *...
^

Any ideas?
Thanks!

**Comment by JorjMcKie** [comment]
Please provide versions of MuPDF and PyMuPDF.
Looks like you took MuPDF source from GitHub - instead of from the official download page.
The version on GitHub is "the latest development version" and therefore prone to contain differences ...

I checked your case, and indeed: you have detected such a difference :-)

**Comment by jtlz2** [comment]
Thanks -

> mutool -v
mutool version 1.11

PyMuPDF README.rst:

PyMuPDF 1.11.0
================

Release date: May 1, 2017

**Comment by JorjMcKie** [comment]
You should be ok with MuPDF v1.11 source from here: https://mupdf.com/downloads/

**Comment by JorjMcKie** [comment]
I think I should include an explicit warning in the installation to **not** use the GitHub version ...

**Comment by rk700** [comment]
@jtlz2 Did you install mupdf-tools with brew or build from source?

**Comment by jtlz2** [comment]
@JorjMcKie I used brew

Still no luck via MuPDF v1.11 source from https://mupdf.com/downloads :

mupdf-1.11-source jtlz2$ sudo make prefix=/usr/local install
    MKDIR build/release/thirdparty/freetype
    CC build/release/thirdparty/freetype/ftbase.o
In file included from thirdparty/freetype/src/base/ftbase.c:32:
In file included from thirdparty/freetype/src/base/ftrfork.c:32:
thirdparty/freetype/src/base/ftbase.h:38:3: warning: unused function
      'open_face_PS_from_sfnt_stream' [-Wunused-function]
  open_face_PS_from_sfnt_stream( FT_Library     library,
  ^
thirdparty/freetype/src/base/ftbase.h:49:3: warning: unused function
      'open_face_from_buffer' [-Wunused-function]
  open_face_from_buffer( FT_Library   library,
  ^
In file included from thirdparty/freetype/src/base/ftbase.c:32:
thirdparty/freetype/src/base/ftrfork.c:436:3: warning: unused function
      'ft_raccess_rule_by_darwin_vfs' [-Wunused-function]
  ft_raccess_rule_by_darwin_vfs( FT_Library  library,
  ^
3 warnings generated.
    CC build/release/thirdparty/freetype/ftbbox.o
    CC build/release/thirdparty/freetype/ftbitmap.o
    CC build/release/thirdparty/freetype/ftdebug.o
    CC build/release/thirdparty/freetype/ftfntfmt.o
    CC build/release/thirdparty/freetype/ftgasp.o
    CC build/release/thirdparty/freetype/ftglyph.o
    CC build/release/thirdparty/freetype/ftinit.o
    CC build/release/thirdparty/freetype/ftstroke.o
    CC build/release/thirdparty/freetype/ftsynth.o
    CC build/release/thirdparty/freetype/ftsystem.o
    CC build/release/thirdparty/freetype/fttype1.o
    CC build/release/thirdparty/freetype/cff.o
    CC build/release/thirdparty/freetype/psaux.o
    CC build/release/thirdparty/freetype/pshinter.o
    CC build/release/thirdparty/freetype/psnames.o
    CC build/release/thirdparty/freetype/raster.o
    CC build/release/thirdparty/freetype/sfnt.o
    CC build/release/thirdparty/freetype/smooth.o
    CC build/release/thirdparty/freetype/truetype.o
    CC build/release/thirdparty/freetype/type1.o
    CC build/release/thirdparty/freetype/type1cid.o
    MKDIR build/release/thirdparty/harfbuzz
    CC build/release/thirdparty/harfbuzz/hb-blob.o
    CC build/release/thirdparty/harfbuzz/hb-buffer.o
    CC build/release/thirdparty/harfbuzz/hb-buffer-serialize.o
    CC build/release/thirdparty/harfbuzz/hb-common.o
    CC build/release/thirdparty/harfbuzz/hb-face.o
    CC build/release/thirdparty/harfbuzz/hb-fallback-shape.o
    CC build/release/thirdparty/harfbuzz/hb-font.o
    CC build/release/thirdparty/harfbuzz/hb-ft.o
    CC build/release/thirdparty/harfbuzz/hb-ot-font.o
    CC build/release/thirdparty/harfbuzz/hb-ot-layout.o
    CC build/release/thirdparty/harfbuzz/hb-ot-map.o
    CC build/release/thirdparty/harfbuzz/hb-ot-shape-complex-arabic.o
    CC build/release/thirdparty/harfbuzz/hb-ot-shape-complex-default.o
    CC build/release/thirdparty/harfbuzz/hb-ot-shape-complex-hangul.o
    CC build/release/thirdparty/harfbuzz/hb-ot-shape-complex-hebrew.o
    CC build/release/thirdparty/harfbuzz/hb-ot-shape-complex-indic-table.o
    CC build/release/thirdparty/harfbuzz/hb-ot-shape-complex-indic.o
    CC build/release/thirdparty/harfbuzz/hb-ot-shape-complex-myanmar.o
    CC build/release/thirdparty/harfbuzz/hb-ot-shape-complex-thai.o
    CC build/release/thirdparty/harfbuzz/hb-ot-shape-complex-tibetan.o
    CC build/release/thirdparty/harfbuzz/hb-ot-shape-complex-use-table.o
    CC build/release/thirdparty/harfbuzz/hb-ot-shape-complex-use.o
    CC build/release/thirdparty/harfbuzz/hb-ot-shape-fallback.o
    CC build/release/thirdparty/harfbuzz/hb-ot-shape-normalize.o
    CC build/release/thirdparty/harfbuzz/hb-ot-shape.o
    CC build/release/thirdparty/harfbuzz/hb-ot-tag.o
    CC build/release/thirdparty/harfbuzz/hb-set.o
    CC build/release/thirdparty/harfbuzz/hb-shape-plan.o
    CC build/release/thirdparty/harfbuzz/hb-shape.o
    CC build/release/thirdparty/harfbuzz/hb-shaper.o
    CC build/release/thirdparty/harfbuzz/hb-ucdn.o
    CC build/release/thirdparty/harfbuzz/hb-unicode.o
    CC build/release/thirdparty/harfbuzz/hb-warning.o
    MKDIR build/release/thirdparty/jbig2dec
    CC build/release/thirdparty/jbig2dec/jbig2.o
    CC build/release/thirdparty/jbig2dec/jbig2_arith.o
    CC build/release/thirdparty/jbig2dec/jbig2_arith_iaid.o
    CC build/release/thirdparty/jbig2dec/jbig2_arith_int.o
    CC build/release/thirdparty/jbig2dec/jbig2_generic.o
    CC build/release/thirdparty/jbig2dec/jbig2_halftone.o
    CC build/release/thirdparty/jbig2dec/jbig2_huffman.o
    CC build/release/thirdparty/jbig2dec/jbig2_image.o
    CC build/release/thirdparty/jbig2dec/jbig2_metadata.o
    CC build/release/thirdparty/jbig2dec/jbig2_mmr.o
    CC build/release/thirdparty/jbig2dec/jbig2_page.o
    CC build/release/thirdparty/jbig2dec/jbig2_refinement.o
    CC build/release/thirdparty/jbig2dec/jbig2_segment.o
    CC build/release/thirdparty/jbig2dec/jbig2_symbol_dict.o
    CC build/release/thirdparty/jbig2dec/jbig2_text.o
    MKDIR build/release/thirdparty/libjpeg
    CC build/release/thirdparty/libjpeg/jaricom.o
    CC build/release/thirdparty/libjpeg/jcomapi.o
    CC build/release/thirdparty/libjpeg/jdapimin.o
    CC build/release/thirdparty/libjpeg/jdapistd.o
    CC build/release/thirdparty/libjpeg/jdarith.o
    CC build/release/thirdparty/libjpeg/jdatadst.o
    CC build/release/thirdparty/libjpeg/jdatasrc.o
    CC build/release/thirdparty/libjpeg/jdcoefct.o
    CC build/release/thirdparty/libjpeg/jdcolor.o
    CC build/release/thirdparty/libjpeg/jddctmgr.o
    CC build/release/thirdparty/libjpeg/jdhuff.o
    CC build/release/thirdparty/libjpeg/jdinput.o
    CC build/release/thirdparty/libjpeg/jdmainct.o
    CC build/release/thirdparty/libjpeg/jdmarker.o
    CC build/release/thirdparty/libjpeg/jdmaster.o
    CC build/release/thirdparty/libjpeg/jdmerge.o
    CC build/release/thirdparty/libjpeg/jdpostct.o
    CC build/release/thirdparty/libjpeg/jdsample.o
    CC build/release/thirdparty/libjpeg/jdtrans.o
    CC build/release/thirdparty/libjpeg/jerror.o
    CC build/release/thirdparty/libjpeg/jfdctflt.o
    CC build/release/thirdparty/libjpeg/jfdctfst.o
    CC build/release/thirdparty/libjpeg/jfdctint.o
    CC build/release/thirdparty/libjpeg/jidctflt.o
    CC build/release/thirdparty/libjpeg/jidctfst.o
    CC build/release/thirdparty/libjpeg/jidctint.o
    CC build/release/thirdparty/libjpeg/jmemmgr.o
    CC build/release/thirdparty/libjpeg/jquant1.o
    CC build/release/thirdparty/libjpeg/jquant2.o
    CC build/release/thirdparty/libjpeg/jutils.o
    MKDIR build/release/thirdparty/mujs
    CC build/release/thirdparty/mujs/one.o
    MKDIR build/release/thirdparty/openjpeg
    CC build/release/thirdparty/openjpeg/bio.o
    CC build/release/thirdparty/openjpeg/cidx_manager.o
    CC build/release/thirdparty/openjpeg/cio.o
    CC build/release/thirdparty/openjpeg/dwt.o
    CC build/release/thirdparty/openjpeg/event.o
    CC build/release/thirdparty/openjpeg/function_list.o
    CC build/release/thirdparty/openjpeg/image.o
    CC build/release/thirdparty/openjpeg/invert.o
    CC build/release/thirdparty/openjpeg/j2k.o
    CC build/release/thirdparty/openjpeg/jp2.o
    CC build/release/thirdparty/openjpeg/mct.o
    CC build/release/thirdparty/openjpeg/mqc.o
    CC build/release/thirdparty/openjpeg/openjpeg.o
    CC build/release/thirdparty/openjpeg/phix_manager.o
    CC build/release/thirdparty/openjpeg/pi.o
    CC build/release/thirdparty/openjpeg/ppix_manager.o
    CC build/release/thirdparty/openjpeg/raw.o
    CC build/release/thirdparty/openjpeg/t1.o
    CC build/release/thirdparty/openjpeg/t2.o
    CC build/release/thirdparty/openjpeg/tcd.o
    CC build/release/thirdparty/openjpeg/tgt.o
    CC build/release/thirdparty/openjpeg/thix_manager.o
    CC build/release/thirdparty/openjpeg/tpix_manager.o
    CC build/release/thirdparty/openjpeg/thread.o
    MKDIR build/release/thirdparty/zlib
    CC build/release/thirdparty/zlib/adler32.o
    CC build/release/thirdparty/zlib/compress.o
    CC build/release/thirdparty/zlib/crc32.o
    CC build/release/thirdparty/zlib/deflate.o
    CC build/release/thirdparty/zlib/inffast.o
    CC build/release/thirdparty/zlib/inflate.o
thirdparty/zlib/inflate.c:1491:61: warning: shifting a negative signed value is
      undefined [-Wshift-negative-value]
    if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;
                                                        ~~~ ^
1 warning generated.
    CC build/release/thirdparty/zlib/inftrees.o
    CC build/release/thirdparty/zlib/trees.o
    CC build/release/thirdparty/zlib/uncompr.o
    CC build/release/thirdparty/zlib/zutil.o
    CC build/release/thirdparty/zlib/gzlib.o
    CC build/release/thirdparty/zlib/gzwrite.o
    CC build/release/thirdparty/zlib/gzclose.o
    CC build/release/thirdparty/zlib/gzread.o
    RM build/release/libmupdfthird.a
    AR build/release/libmupdfthird.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: build/release/libmupdfthird.a(hb-warning.o) has no symbols
xcrun ranlib 
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: no archives specified
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib [-sactfqLT] [-] archive [...]
make: *** [build/release/libmupdfthird.a] Error 1

**Comment by rk700** [comment]
@jtlz2 Installing `mupdf-tool` with brew is preferred for Mac users. However the header file `annot.h` on my machine looks different from yours, though I also use brew:

```
liuruikai756@mbp:~$ brew info mupdf-tools
mupdf-tools: stable 1.11 (bottled), HEAD
Lightweight PDF and XPS viewer
https://mupdf.com/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mupdf-tools.rb
liuruikai756@mbp:~$ brew install --force mupdf-tools
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Downloading https://homebrew.bintray.com/bottles/mupdf-tools-1.11.sierra.bottle.tar.gz
Already downloaded: /Users/liuruikai756/Library/Caches/Homebrew/mupdf-tools-1.11.sierra.bottle.tar.gz
==> Pouring mupdf-tools-1.11.sierra.bottle.tar.gz
�  /usr/local/Cellar/mupdf-tools/1.11: 100 files, 145MB
liuruikai756@mbp:~$ brew ls -l mupdf-tools | grep annot.h
/usr/local/Cellar/mupdf-tools/1.11/include/mupdf/pdf/annot.h
liuruikai756@mbp:~$ grep pdf_load_link_annots /usr/local/Cellar/mupdf-tools/1.11/include/mupdf/pdf/annot.h
fz_link *pdf_load_link_annots(fz_context *ctx, pdf_document *, pdf_obj *annots, const fz_matrix *page_ctm);
```

Take a look at the last `grep` command, `pdf_load_link_annots` takes 4 args instead of 5.

**Comment by jtlz2** [comment]
@rk700 Many thanks - it's basically working now - conflicting versions I think...
