### ISSUE TITLE
ImportError: No module named _fitz

### ISSUE THREAD

**Issue by mpvillafranca** [rk700/PyMuPDF#95]
Hi,

just installed PyMuPDF on my Linux Mint inside a virtualenv following the Ubuntu instructions. Everything was looking good until I called the "import fitz", geting this error:

```
>>> import fitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fitz/__init__.py", line 2, in <module>
    from fitz.fitz import *
  File "fitz/fitz.py", line 17, in <module>
    _fitz = swig_import_helper()
  File "fitz/fitz.py", line 16, in swig_import_helper
    return importlib.import_module('_fitz')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _fitz
```
Do you know what could be wrong? I didn't get any kind of error during the building process so I suppose everything went fine on that stage...

Hope you can help me.

**Comment by JorjMcKie** [comment]
I am no Linux guy - so @rk700 will need to step in.

But in the meantime can you find out, where in fact the generated _fitz.so has landed? It must exist somewhere, given you setup went correctly.

Are you sure you invoke the interpreter in the exact same environment, where PyMuPDF was generated?

A setup.py protocol would be helpful, too ...

Thanks!

**Comment by rk700** [comment]
Hi,

I guess you are running python in PyMuPDF's root dir @mpvillafranca . If so, please `cd` into some other directory and try again.

**Comment by mpvillafranca** [comment]
Hi,

I followed the Ubuntu steps for the installation. Here is my `setup.py`:

```
from distutils.core import setup, Extension
import sys, os

# check the platform
if sys.platform.startswith('linux'):
    module = Extension('fitz._fitz', # name of the module
                       ['fitz/fitz_wrap.c'], # C source file
                       include_dirs=['/usr/local/include/mupdf',    # we need the path of the MuPDF and zlib$
                                     '/usr/local/thirdparty/zlib',  # '/usr/include/mupdf',
                                    ],
                       #library_dirs=['<mupdf_and_3rd_party_libraries_dir>'],
                       libraries=[
                           'mupdf',
                           #'crypto', #openssl is required by mupdf on archlinux
                           #'jbig2dec', 'openjp2', 'jpeg', 'freetype',
                           'mupdfthird',
                           ], # the libraries to link with
                      )
elif sys.platform.startswith('darwin'):
    module = Extension('fitz._fitz', # name of the module
                       ['fitz/fitz_wrap.c'], # C source file
                       # this are directories containing mupdf's and zlib's header files
                       include_dirs=['/usr/local/include/mupdf', '/usr/local/include'],
                       # libraries should already be linked here by brew
                       library_dirs=['/usr/local/lib'],
                       #library_dirs=['/usr/local/Cellar/mupdf-tools/1.8/lib/',
                                    #'/usr/local/Cellar/openssl/1.0.2g/lib/',
                                    #'/usr/local/Cellar/jpeg/8d/lib/',
                                    #'/usr/local/Cellar/freetype/2.6.3/lib/',
                                    #'/usr/local/Cellar/jbig2dec/0.12/lib/'
                           #],
                       libraries=['mupdf', 'mupdfthird']
                      )

else:
#===============================================================================
# This will build / set up PyMuPDF under Windows.
# For details consult the documentation.
#===============================================================================
    module = Extension('fitz._fitz',
                       include_dirs=[ # we need the path of the MuPDF's headers
                                     './mupdf/include',
                                     './mupdf/include/mupdf',
                                     './mupdf/thirdparty/zlib', 
                                    ],
                       libraries=[ # these are needed in Windows
                                  'libmupdf', 'libfonts',
                                  'libthirdparty',
                                 ],
                       extra_link_args=['/NODEFAULTLIB:MSVCRT'],
                                     # x86 dir of libmupdf.lib etc.
                       library_dirs=['./mupdf/platform/win32/Release'],
                                     # x64 dir of libmupdf.lib etc.
                       #library_dirs=['./mupdf/platform/win32/x64/Release'],
                       sources=['./fitz/fitz_wrap.c',])

setup(name = 'fitz',
      version = "1.10.0",
      description = 'Python bindings for the PDF rendering library MuPDF',
      classifiers = ['Development Status :: 5 - Production/Stable',
                     'Environment :: Console',
                     'Intended Audience :: Developers',
                     'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
                     'License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)',
                     'Operating System :: WINDOWS',
                     'Operating System :: POSIX :: Linux',
                     'Operating System :: MacOS',
                     'Programming Language :: C',
                     'Programming Language :: Python :: 2.7',
                     'Programming Language :: Python :: 3',
                     'Topic :: Utilities'],
      url = 'https://github.com/rk700/PyMuPDF',
      author = 'Ruikai Liu',
      author_email = 'lrk700@gmail.com',
      license = 'GPLv3+',
      ext_modules = [module],
      py_modules = ['fitz.fitz', 'fitz.utils'])
```

The files get copied to my virtualenv path (/home/vens/ljenv/lib/python2.7/site-packages).

I tried runing it from a new terminal typing `$ python` and then:

```
$ python 
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vens/ljenv/local/lib/python2.7/site-packages/fitz/__init__.py", line 2, in <module>
    from fitz.fitz import *
  File "/home/vens/ljenv/local/lib/python2.7/site-packages/fitz/fitz.py", line 17, in <module>
    _fitz = swig_import_helper()
  File "/home/vens/ljenv/local/lib/python2.7/site-packages/fitz/fitz.py", line 16, in swig_import_helper
    return importlib.import_module('_fitz')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _fitz
```

**Comment by rk700** [comment]
If installed successfully, then `_fitz.so` and other `.py` files should be copied to the python lib directory. So you can take a look at the folder `/home/vens/ljenv/local/lib/python2.7/site-packages/fitz/` and see if `_fitz.so` is there.

**Comment by mpvillafranca** [comment]
Yes, I've got everything inside that folder

![seleccion_568](https://user-images.githubusercontent.com/5960630/27787169-3e49cd5a-5fe4-11e7-80f0-c9a7fc4715ab.png)

But when I activate de virtualenv and try to call the library I get that error... It's weird.

**Comment by rk700** [comment]
It's weird. If python can find the `.py` files, then it should be able to import the `.so` library in the same folder as well.

Could you take a look at `_fitz.so`? Or try installing and running without virtualenv again?

**Comment by gileadslostson** [comment]
You don't seem to have the `library_dirs` set:
`#library_dirs=['<mupdf_and_3rd_party_libraries_dir>'],`

**Comment by insideable** [comment]
@mpvillafranca I get same error if I'm trying to run python from PyMuPDF sources directory, but import works fine from any other folder.

```
cd /tmp/fitz/PyMuPDF/
(env) [vagrant@arch PyMuPDF]$ python
Python 3.6.1 (default, Mar 27 2017, 00:27:06) 
[GCC 6.3.1 20170306] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
Traceback (most recent call last):
  File "/tmp/fitz/PyMuPDF/fitz/fitz.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/vagrant/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fitz._fitz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/fitz/PyMuPDF/fitz/__init__.py", line 2, in <module>
    from fitz.fitz import *
  File "/tmp/fitz/PyMuPDF/fitz/fitz.py", line 17, in <module>
    _fitz = swig_import_helper()
  File "/tmp/fitz/PyMuPDF/fitz/fitz.py", line 16, in swig_import_helper
    return importlib.import_module('_fitz')
  File "/home/vagrant/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_fitz'
>>> 
```

```
(env) [vagrant@arch PyMuPDF]$ cd ~
(env) [vagrant@arch ~]$ python
Python 3.6.1 (default, Mar 27 2017, 00:27:06) 
[GCC 6.3.1 20170306] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fitz
>>> 

```

**Comment by JorjMcKie** [comment]
1. If you start python inside a directory, any `__init__.py` there will **not** be executed.
2. And of course, any `import` or other statements resulting in file lookups will first check this directory if not otherwise instructed.

So in total, the situation becomes quite fuzzy when doing this. PyMuPDF - like many other packages - does crucial things in its `__init__.py`. It cannot work without them.

**Comment by jayjb** [comment]
@mpvillafranca: did you ever figure a resolution to this issue? Im hitting it currently with trying to make a 1.18.0 build for Ubuntu

**Comment by JorjMcKie** [comment]
> @mpvillafranca: did you ever figure a resolution to this issue? Im hitting it currently with trying to make a 1.18.0 build for Ubuntu

Just for fun? Why don't you use one of the wheels?

**Comment by jayjb** [comment]
Hi @JorjMcKie,

Haha, no definitely not for fun. I did try to use the wheels that you folks provided but there was an issue when installing it into an ubuntu enviroment (something like about the linux distro not being supported).. 

I then saw that there were Ubuntu build instructions that I followed and ended up here. I understand that the python3 version works but we need a python2 version.

**Comment by JorjMcKie** [comment]
Ahhh, someone with a zombie Python! That indeed is no fun 🤣.
But seriously: you can not use v1.18.5+ any longer for Python2. You must fall back to v1.18.4 or earlier b/o source code incompatibilities stating with 1.18.5.
I have a few zombie wheels on my machine:
```
PyMuPDF-1.18.1-cp27-cp27m-macosx_10_9_x86_64.whl
PyMuPDF-1.18.1-cp27-cp27m-manylinux2010_x86_64.whl
PyMuPDF-1.18.1-cp27-cp27m-win32.whl
PyMuPDF-1.18.1-cp27-cp27m-win_amd64.whl
PyMuPDF-1.18.1-cp27-cp27mu-manylinux2010_x86_64.whl
PyMuPDF-1.18.1-cp35-cp35m-macosx_10_9_x86_64.whl
PyMuPDF-1.18.1-cp35-cp35m-manylinux2010_x86_64.whl
PyMuPDF-1.18.1-cp35-cp35m-win32.whl
PyMuPDF-1.18.1-cp35-cp35m-win_amd64.whl
PyMuPDF-1.18.2-cp27-cp27m-macosx_10_9_x86_64.whl
PyMuPDF-1.18.2-cp27-cp27m-manylinux2010_x86_64.whl
PyMuPDF-1.18.2-cp27-cp27m-win32.whl
PyMuPDF-1.18.2-cp27-cp27m-win_amd64.whl
PyMuPDF-1.18.2-cp27-cp27mu-manylinux2010_x86_64.whl
PyMuPDF-1.18.2-cp35-cp35m-macosx_10_9_x86_64.whl
PyMuPDF-1.18.2-cp35-cp35m-manylinux2010_x86_64.whl
PyMuPDF-1.18.2-cp35-cp35m-win32.whl
PyMuPDF-1.18.2-cp35-cp35m-win_amd64.whl
PyMuPDF-1.18.3-cp27-cp27m-macosx_10_9_x86_64.whl
PyMuPDF-1.18.3-cp27-cp27m-manylinux2010_x86_64.whl
PyMuPDF-1.18.3-cp27-cp27m-win32.whl
PyMuPDF-1.18.3-cp27-cp27m-win_amd64.whl
PyMuPDF-1.18.3-cp27-cp27mu-manylinux2010_x86_64.whl
PyMuPDF-1.18.3-cp35-cp35m-macosx_10_9_x86_64.whl
PyMuPDF-1.18.3-cp35-cp35m-manylinux2010_x86_64.whl
PyMuPDF-1.18.3-cp35-cp35m-win32.whl
PyMuPDF-1.18.3-cp35-cp35m-win_amd64.whl
PyMuPDF-1.18.4-cp27-cp27m-macosx_10_9_x86_64.whl
PyMuPDF-1.18.4-cp27-cp27m-manylinux2010_x86_64.whl
PyMuPDF-1.18.4-cp27-cp27m-win32.whl
PyMuPDF-1.18.4-cp27-cp27m-win_amd64.whl
PyMuPDF-1.18.4-cp27-cp27mu-manylinux2010_x86_64.whl
PyMuPDF-1.18.4-cp35-cp35m-macosx_10_9_x86_64.whl
PyMuPDF-1.18.4-cp35-cp35m-manylinux2010_x86_64.whl
PyMuPDF-1.18.4-cp35-cp35m-win32.whl
PyMuPDF-1.18.4-cp35-cp35m-win_amd64.whl
```
If one of those is good for you let me know and I will upload it to this thread ...

**Comment by jayjb** [comment]
Haha zombie python - i like that (and unfortunately yes!). 

Ye so actually ive been trying to build it from 1.18.0 just to be sure (it did require some manual changes to `setup.py` as well), but once everything is successfully compiled, built and installed, I hit the `ModuleNotFoundError: No module named '_fitz'` when trying to `import fitz`.

Are these older `.whl` different from the ones on your github releases page (under assets). As an example i tried downloading 
```
$ wget https://github.com/pymupdf/PyMuPDF/releases/download/1.18.3/PyMuPDF-1.18.3-cp27-cp27m-manylinux2010_x86_64.whl
$ pip install PyMuPDF-1.18.3-cp27-cp27m-manylinux2010_x86_64.whl
PyMuPDF-1.18.3-cp27-cp27m-manylinux2010_x86_64.whl is not a supported wheel on this platform.
```

Im quickly going to the `mu` vs `m` version and see if there is some difference.

**Comment by JorjMcKie** [comment]
Are you sure you have the most current pip for Python2?

**Comment by jayjb** [comment]
Ye we not using the most current, but we aren't using the oldest. It actually looks like the `mu` version is working for `1.18.3` (I had tried the `1.18.4` version previously to no avail). 

Thanks for getting me to a working version! And also great job on this project. I really wish I had found it earlier - it works great!

**Comment by MoTechStore** [comment]
I hope you're dealing PDF in Python using PyMuPDF. Just install PyMuPDF by command - pip install PyMuPDF. Then import it before using it.

import fitz
pdf_file = fitz.open('1.pdf') # Opening PDF file using fitz


Then go on writing your code .....

**Comment by jmblanco1961** [comment]
Muy buen dìa, a pesar de tener instalado PyMuPDF cuando corro mi programa me aparece el siguiente error, tenia instalado la version 3.9 de python, la desinstale porque al parecer esta funcionalidad no corria en version 3.9, ahora tengo instalada version 3.8 y tampocosigue el error   ModuleNotFoundError: No module named 'fitz', 
ya esta instalado asi:
Package       Version
------------- -------
pip           21.0.1
PyMuPDF       1.18.10
como podrìa solucionarlo, ya llevo varios dìas sin poderlo solucionar,
Gracias.

**Comment by JorjMcKie** [comment]
@jmblanco1961 - cual es tu 
* método de instalación: `python -m pip install pymupdf`?
* operating system: Windows, Linux, Mac OSX?
* bitness: 64bit, 32bit?

**_Siempre_** sigue la recomendación: `python -m pip install ...` y **_nunca_** simplemente `pip install ...`!
