### ISSUE TITLE
compile fail

### ISSUE THREAD

**Issue by julienfr112** [rk700/PyMuPDF#99]
`python setup.py build`

fail with

`fitz/fitz_wrap.c:8021:1: error: format not a string literal and no format arguments [-Werror=format-security]`

**Comment by JorjMcKie** [comment]
please let me know more:
your system (OS, bitness), Python version / bitness, PyMuPDF version including the version string in `fitz.py` line 106.

**Comment by JorjMcKie** [comment]
Hi, you may want to download a new version. It should address your problem - also pls. see issue #102.
